// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  CreateAFileData,
  CreateAFileErrors,
  CreateAFileResponses,
  DeleteAFileData,
  DeleteAFileErrors,
  DeleteAFileResponses,
  GetAFileData,
  GetAFileErrors,
  GetAFileResponses,
  GetAllFilesData,
  GetAllFilesErrors,
  GetAllFilesResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Get all Files
 *
 * Retrieves all files.
 *
 * ### Filtering
 *
 * For general filtering syntax, see [Filtering](/guides/Getting-Started/filtering).
 *
 * The following operators and attributes are available when filtering on this endpoint.
 *
 * | Attribute             | Type      | Operators           | Example |
 * |:----------------------|:----------|:--------------------------|:-------------|
 * | `id`                  | `string`  | `in`                      | `in(id,file-id-1,file-id-2,file-id-3)` |
 * | `file_name`           | `string`  | `eq` / `like`             | `eq(file_name, my_image.jpg)` |
 * | `width`               | `integer` | `gt` / `ge` / `lt` / `le` | `gt(width,200)` |
 * | `height`              | `integer` | `gt` / `ge` / `lt` / `le` | `lt(height,500)` |
 * | `file_size`           | `integer` | `gt` / `ge` / `lt` / `le` | `le(file_size,20953)` |
 *
 * #### Bulk File Retrieval
 *
 * To retrieve multiple files by their IDs in a single request, use the `in` operator with a comma-separated list of file IDs:
 *
 * ```
 * GET /v2/files?filter=in(id,06b881bd-f152-4c36-8658-7132a8fab49c,ec73567b-04e8-4000-a11a-7e1407cc2f21)
 * ```
 *
 * This is more efficient than making separate requests for each file and is recommended for bulk operations.
 *
 * **Note on invalid IDs**: If any IDs in the filter are missing, malformed, or do not exist in the store, they will be silently ignored. The response will only include files that were successfully found. For example, if you request 5 IDs but only 3 exist, the response will contain 3 files with `total: 3` in the metadata.
 *
 */
export const getAllFiles = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllFilesData, ThrowOnError>,
): RequestResult<GetAllFilesResponses, GetAllFilesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetAllFilesResponses,
    GetAllFilesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/files",
    ...options,
  })

/**
 * Create a File
 *
 * Create a File
 */
export const createAFile = <ThrowOnError extends boolean = false>(
  options: Options<CreateAFileData, ThrowOnError>,
): RequestResult<CreateAFileResponses, CreateAFileErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateAFileResponses,
    CreateAFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/files",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Delete a File
 *
 * Delete a File
 */
export const deleteAFile = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAFileData, ThrowOnError>,
): RequestResult<DeleteAFileResponses, DeleteAFileErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteAFileResponses,
    DeleteAFileErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/files/{fileID}",
    ...options,
  })

/**
 * Get a File
 *
 * Get a File
 */
export const getAFile = <ThrowOnError extends boolean = false>(
  options: Options<GetAFileData, ThrowOnError>,
): RequestResult<GetAFileResponses, GetAFileErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetAFileResponses,
    GetAFileErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/files/{fileID}",
    ...options,
  })
