// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from "@hey-api/client-fetch"
import type {
  DeleteV2SettingsData,
  DeleteV2SettingsResponse,
  DeleteV2SettingsError,
  GetV2SettingsData,
  GetV2SettingsResponse,
  GetV2SettingsError,
  PutV2SettingsData,
  PutV2SettingsResponse,
  PutV2SettingsError,
} from "./types.gen"

export const client = createClient(createConfig())

/**
 * Delete Project Settings
 * Deletes a store setting. Organization settings cannot be deleted.
 */
export const deleteV2Settings = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteV2SettingsData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteV2SettingsResponse,
    DeleteV2SettingsError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v2/settings",
  })
}

/**
 * Get Project Settings
 * You can get all of the project settings via one API call using a `client_credential` token. The response is in object format as shown in the following example.
 *
 * :::note
 *
 * The default `calculation_method` is `line`.
 *
 * :::
 */
export const getV2Settings = <ThrowOnError extends boolean = false>(
  options?: Options<GetV2SettingsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetV2SettingsResponse,
    GetV2SettingsError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v2/settings",
  })
}

/**
 * Update Project Settings
 * You can use the Settings endpoint to update your project settings at any time. These global settings take immediate effect.
 */
export const putV2Settings = <ThrowOnError extends boolean = false>(
  options?: Options<PutV2SettingsData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    PutV2SettingsResponse,
    PutV2SettingsError,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/v2/settings",
  })
}
