// This file is auto-generated by @hey-api/openapi-ts

import type {
  PostMultiSearchResponse,
  MultiSearchByCatalogReleaseResponse,
  SearchByContextResponse,
  SearchByCatalogReleaseResponse,
  ListStopwordSetsResponse2,
  CreateStopwordSetResponse,
  GetStopwordSetResponse,
  UpdateStopwordSetResponse,
  ListSynonymSetsResponse2,
  CreateSynonymSetResponse,
  GetSynonymSetResponse,
  UpdateSynonymSetResponse,
  ListSearchRuleGroupsResponse2,
  CreateSearchRuleGroupResponse,
  GetSearchRuleGroupResponse,
  UpdateSearchRuleGroupResponse,
  ListSearchRulesResponse2,
  CreateSearchRuleResponse,
  GetSearchRuleResponse,
  UpdateSearchRuleResponse,
  MoveSearchRuleResponse,
} from "./types.gen"

const textMatchInfoSchemaResponseTransformer = (data: any) => {
  if (data.num_tokens_dropped) {
    data.num_tokens_dropped = BigInt(data.num_tokens_dropped.toString())
  }
  return data
}

const hitSchemaResponseTransformer = (data: any) => {
  if (data.text_match_info) {
    data.text_match_info = textMatchInfoSchemaResponseTransformer(
      data.text_match_info,
    )
  }
  return data
}

const searchResultSchemaResponseTransformer = (data: any) => {
  if (data.hits) {
    data.hits = data.hits.map((item: any) => {
      return hitSchemaResponseTransformer(item)
    })
  }
  return data
}

const multiSearchResponseSchemaResponseTransformer = (data: any) => {
  if (data.results) {
    data.results = data.results.map((item: any) => {
      return searchResultSchemaResponseTransformer(item)
    })
  }
  return data
}

export const postMultiSearchResponseTransformer = async (
  data: any,
): Promise<PostMultiSearchResponse> => {
  data = multiSearchResponseSchemaResponseTransformer(data)
  return data
}

export const multiSearchByCatalogReleaseResponseTransformer = async (
  data: any,
): Promise<MultiSearchByCatalogReleaseResponse> => {
  data = multiSearchResponseSchemaResponseTransformer(data)
  return data
}

const searchResponseSchemaResponseTransformer = (data: any) => {
  data = searchResultSchemaResponseTransformer(data)
  return data
}

export const searchByContextResponseTransformer = async (
  data: any,
): Promise<SearchByContextResponse> => {
  data = searchResponseSchemaResponseTransformer(data)
  return data
}

export const searchByCatalogReleaseResponseTransformer = async (
  data: any,
): Promise<SearchByCatalogReleaseResponse> => {
  data = searchResponseSchemaResponseTransformer(data)
  return data
}

const stopwordSetMetaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at)
  data.updated_at = new Date(data.updated_at)
  if (data.last_synced_at) {
    data.last_synced_at = new Date(data.last_synced_at)
  }
  return data
}

const stopwordSetSchemaResponseTransformer = (data: any) => {
  data.meta = stopwordSetMetaSchemaResponseTransformer(data.meta)
  return data
}

const listStopwordSetsResponseSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    return stopwordSetSchemaResponseTransformer(item)
  })
  return data
}

export const listStopwordSetsResponseTransformer = async (
  data: any,
): Promise<ListStopwordSetsResponse2> => {
  data = listStopwordSetsResponseSchemaResponseTransformer(data)
  return data
}

const stopwordSetResponseSchemaResponseTransformer = (data: any) => {
  data.data = stopwordSetSchemaResponseTransformer(data.data)
  return data
}

export const createStopwordSetResponseTransformer = async (
  data: any,
): Promise<CreateStopwordSetResponse> => {
  data = stopwordSetResponseSchemaResponseTransformer(data)
  return data
}

export const getStopwordSetResponseTransformer = async (
  data: any,
): Promise<GetStopwordSetResponse> => {
  data = stopwordSetResponseSchemaResponseTransformer(data)
  return data
}

export const updateStopwordSetResponseTransformer = async (
  data: any,
): Promise<UpdateStopwordSetResponse> => {
  data = stopwordSetResponseSchemaResponseTransformer(data)
  return data
}

const synonymSetMetaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at)
  data.updated_at = new Date(data.updated_at)
  if (data.last_synced_at) {
    data.last_synced_at = new Date(data.last_synced_at)
  }
  return data
}

const synonymSetSchemaResponseTransformer = (data: any) => {
  data.meta = synonymSetMetaSchemaResponseTransformer(data.meta)
  return data
}

const listSynonymSetsResponseSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    return synonymSetSchemaResponseTransformer(item)
  })
  return data
}

export const listSynonymSetsResponseTransformer = async (
  data: any,
): Promise<ListSynonymSetsResponse2> => {
  data = listSynonymSetsResponseSchemaResponseTransformer(data)
  return data
}

const synonymSetResponseSchemaResponseTransformer = (data: any) => {
  data.data = synonymSetSchemaResponseTransformer(data.data)
  return data
}

export const createSynonymSetResponseTransformer = async (
  data: any,
): Promise<CreateSynonymSetResponse> => {
  data = synonymSetResponseSchemaResponseTransformer(data)
  return data
}

export const getSynonymSetResponseTransformer = async (
  data: any,
): Promise<GetSynonymSetResponse> => {
  data = synonymSetResponseSchemaResponseTransformer(data)
  return data
}

export const updateSynonymSetResponseTransformer = async (
  data: any,
): Promise<UpdateSynonymSetResponse> => {
  data = synonymSetResponseSchemaResponseTransformer(data)
  return data
}

const searchRuleGroupMetaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at)
  data.updated_at = new Date(data.updated_at)
  return data
}

const searchRuleGroupSchemaResponseTransformer = (data: any) => {
  data.meta = searchRuleGroupMetaSchemaResponseTransformer(data.meta)
  return data
}

const listSearchRuleGroupsResponseSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    return searchRuleGroupSchemaResponseTransformer(item)
  })
  return data
}

export const listSearchRuleGroupsResponseTransformer = async (
  data: any,
): Promise<ListSearchRuleGroupsResponse2> => {
  data = listSearchRuleGroupsResponseSchemaResponseTransformer(data)
  return data
}

const searchRuleGroupResponseSchemaResponseTransformer = (data: any) => {
  data.data = searchRuleGroupSchemaResponseTransformer(data.data)
  return data
}

export const createSearchRuleGroupResponseTransformer = async (
  data: any,
): Promise<CreateSearchRuleGroupResponse> => {
  data = searchRuleGroupResponseSchemaResponseTransformer(data)
  return data
}

export const getSearchRuleGroupResponseTransformer = async (
  data: any,
): Promise<GetSearchRuleGroupResponse> => {
  data = searchRuleGroupResponseSchemaResponseTransformer(data)
  return data
}

export const updateSearchRuleGroupResponseTransformer = async (
  data: any,
): Promise<UpdateSearchRuleGroupResponse> => {
  data = searchRuleGroupResponseSchemaResponseTransformer(data)
  return data
}

const searchRuleMetaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at)
  data.updated_at = new Date(data.updated_at)
  return data
}

const searchRuleSchemaResponseTransformer = (data: any) => {
  data.meta = searchRuleMetaSchemaResponseTransformer(data.meta)
  return data
}

const listSearchRulesResponseSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    return searchRuleSchemaResponseTransformer(item)
  })
  return data
}

export const listSearchRulesResponseTransformer = async (
  data: any,
): Promise<ListSearchRulesResponse2> => {
  data = listSearchRulesResponseSchemaResponseTransformer(data)
  return data
}

const searchRuleResponseSchemaResponseTransformer = (data: any) => {
  data.data = searchRuleSchemaResponseTransformer(data.data)
  return data
}

export const createSearchRuleResponseTransformer = async (
  data: any,
): Promise<CreateSearchRuleResponse> => {
  data = searchRuleResponseSchemaResponseTransformer(data)
  return data
}

export const getSearchRuleResponseTransformer = async (
  data: any,
): Promise<GetSearchRuleResponse> => {
  data = searchRuleResponseSchemaResponseTransformer(data)
  return data
}

export const updateSearchRuleResponseTransformer = async (
  data: any,
): Promise<UpdateSearchRuleResponse> => {
  data = searchRuleResponseSchemaResponseTransformer(data)
  return data
}

export const moveSearchRuleResponseTransformer = async (
  data: any,
): Promise<MoveSearchRuleResponse> => {
  data = searchRuleResponseSchemaResponseTransformer(data)
  return data
}
