// This file is auto-generated by @hey-api/openapi-ts

import type { PostMultiSearchResponse } from "./types.gen"

const textMatchInfoSchemaResponseTransformer = (data: any) => {
  if (data.num_tokens_dropped) {
    data.num_tokens_dropped = BigInt(data.num_tokens_dropped.toString())
  }
  return data
}

const hitSchemaResponseTransformer = (data: any) => {
  if (data.text_match_info) {
    data.text_match_info = textMatchInfoSchemaResponseTransformer(
      data.text_match_info,
    )
  }
  return data
}

const searchResultSchemaResponseTransformer = (data: any) => {
  if (data.hits) {
    data.hits = data.hits.map((item: any) => {
      return hitSchemaResponseTransformer(item)
    })
  }
  return data
}

const multiSearchResponseSchemaResponseTransformer = (data: any) => {
  if (data.results) {
    data.results = data.results.map((item: any) => {
      return searchResultSchemaResponseTransformer(item)
    })
  }
  return data
}

export const postMultiSearchResponseTransformer = async (
  data: any,
): Promise<PostMultiSearchResponse> => {
  data = multiSearchResponseSchemaResponseTransformer(data)
  return data
}
