// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  CreateAFieldData,
  CreateAFieldErrors,
  CreateAFieldResponses,
  CreateAFlowData,
  CreateAFlowErrors,
  CreateAFlowResponses,
  CreateAnEntryData,
  CreateAnEntryErrors,
  CreateAnEntryRelationshipData,
  CreateAnEntryRelationshipErrors,
  CreateAnEntryRelationshipResponses,
  CreateAnEntryResponses,
  DeleteAFieldData,
  DeleteAFieldErrors,
  DeleteAFieldResponses,
  DeleteAFlowData,
  DeleteAFlowErrors,
  DeleteAFlowResponses,
  DeleteAnEntryData,
  DeleteAnEntryErrors,
  DeleteAnEntryRelationshipData,
  DeleteAnEntryRelationshipErrors,
  DeleteAnEntryRelationshipResponses,
  DeleteAnEntryResponses,
  GetAFieldData,
  GetAFieldErrors,
  GetAFieldResponses,
  GetAFlowData,
  GetAFlowErrors,
  GetAFlowResponses,
  GetAllEntriesData,
  GetAllEntriesErrors,
  GetAllEntriesResponses,
  GetAllFieldsByFlowData,
  GetAllFieldsByFlowErrors,
  GetAllFieldsByFlowResponses,
  GetAllFieldsData,
  GetAllFieldsErrors,
  GetAllFieldsResponses,
  GetAllFlowsData,
  GetAllFlowsErrors,
  GetAllFlowsResponses,
  GetAnEntryData,
  GetAnEntryErrors,
  GetAnEntryResponses,
  UpdateAFieldData,
  UpdateAFieldErrors,
  UpdateAFieldResponses,
  UpdateAFlowData,
  UpdateAFlowErrors,
  UpdateAFlowResponses,
  UpdateAnEntryData,
  UpdateAnEntryErrors,
  UpdateAnEntryRelationshipData,
  UpdateAnEntryRelationshipErrors,
  UpdateAnEntryRelationshipResponses,
  UpdateAnEntryResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Get all Flows
 *
 * - For Commerce, this endpoint retrieves a list of flows.
 * - For Product Experience Manager, this endpoint retrieves a list of templates.
 *
 */
export const getAllFlows = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllFlowsData, ThrowOnError>,
): RequestResult<GetAllFlowsResponses, GetAllFlowsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetAllFlowsResponses,
    GetAllFlowsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows",
    ...options,
  })

/**
 * Create a Flow
 *
 * - For Commerce, this endpoint creates a flow.
 * - For Product Experience Manager, this endpoint creates a template.
 *
 * :::caution
 *
 * Custom names and values prefixed with $ are not supported.
 *
 * :::
 *
 */
export const createAFlow = <ThrowOnError extends boolean = false>(
  options: Options<CreateAFlowData, ThrowOnError>,
): RequestResult<CreateAFlowResponses, CreateAFlowErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateAFlowResponses,
    CreateAFlowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete a Flow
 *
 * - For Commerce, this endpoint deletes a flow. We recommend that you remove all the fields assigned to a flow before deleting a flow.
 * - For Product Experience Manager, this endpoint deletes a template. We recommend that you remove all the attributes assigned to a template before deleting a template.
 *
 */
export const deleteAFlow = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAFlowData, ThrowOnError>,
): RequestResult<DeleteAFlowResponses, DeleteAFlowErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteAFlowResponses,
    DeleteAFlowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowID}",
    ...options,
  })

/**
 * Get a Flow
 *
 * - For Commerce, this endpoint retrieves a flow.
 * - For Product Experience Manager, this endpoint retrieves a template.
 *
 */
export const getAFlow = <ThrowOnError extends boolean = false>(
  options: Options<GetAFlowData, ThrowOnError>,
): RequestResult<GetAFlowResponses, GetAFlowErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetAFlowResponses,
    GetAFlowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowID}",
    ...options,
  })

/**
 * Update a Flow
 *
 * - For Commerce, this endpoint updates a flow.
 * - For Product Experience Manager, this endpoint updates a template.
 *
 * Specify whichever attributes you want to change. The values of the other attributes remain the same. If the attributes section is empty, the flow/template is not updated.
 *
 */
export const updateAFlow = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAFlowData, ThrowOnError>,
): RequestResult<UpdateAFlowResponses, UpdateAFlowErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateAFlowResponses,
    UpdateAFlowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get all Fields
 *
 * - For Commerce, this endpoint retrieves all fields in a flow.
 * - For Product Experience Manager, this endpoint retrieves all attributes in a template.
 *
 */
export const getAllFields = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllFieldsData, ThrowOnError>,
): RequestResult<GetAllFieldsResponses, GetAllFieldsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetAllFieldsResponses,
    GetAllFieldsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/fields",
    ...options,
  })

/**
 * Create a Field
 *
 * - For Commerce, this endpoint creates a field.
 * - For Product Experience Manager, this endpoint creates an attribute.
 *
 */
export const createAField = <ThrowOnError extends boolean = false>(
  options: Options<CreateAFieldData, ThrowOnError>,
): RequestResult<CreateAFieldResponses, CreateAFieldErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateAFieldResponses,
    CreateAFieldErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/fields",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete a Field
 *
 * - For Commerce, this endpoint deletes a field.
 * - For Product Experience Manager, this endpoint deletes an attribute.
 *
 */
export const deleteAField = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAFieldData, ThrowOnError>,
): RequestResult<DeleteAFieldResponses, DeleteAFieldErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteAFieldResponses,
    DeleteAFieldErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/fields/{flowFieldID}",
    ...options,
  })

/**
 * Get a Field
 *
 * - For Commerce, this endpoint retrieves a field.
 * - For Product Experience Manager, this endpoint retrieves an attribute.
 *
 */
export const getAField = <ThrowOnError extends boolean = false>(
  options: Options<GetAFieldData, ThrowOnError>,
): RequestResult<GetAFieldResponses, GetAFieldErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetAFieldResponses,
    GetAFieldErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/fields/{flowFieldID}",
    ...options,
  })

/**
 * Update a Field
 *
 * - For Commerce, this endpoint updates a field.
 * - For Product Experience Manager, this endpoint updates an attribute.
 *
 * Specify whichever attributes you want to change. The values of the other attributes remain the same. If the attributes section is empty, the field/attribute is not updated.
 *
 */
export const updateAField = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAFieldData, ThrowOnError>,
): RequestResult<UpdateAFieldResponses, UpdateAFieldErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateAFieldResponses,
    UpdateAFieldErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/fields/{flowFieldID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get all Entries
 *
 * - For Commerce, this endpoint retrieves all entries for a flow.
 * - For Product Experience Manager, this endpoint retrieves all entries for a template.
 *
 */
export const getAllEntries = <ThrowOnError extends boolean = false>(
  options: Options<GetAllEntriesData, ThrowOnError>,
): RequestResult<GetAllEntriesResponses, GetAllEntriesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetAllEntriesResponses,
    GetAllEntriesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/entries",
    ...options,
  })

/**
 * Create an Entry
 *
 * - For Commerce, this endpoint creates an entry for a flow.
 * - For Product Experience Manager, this endpoint creates an entry for a template.
 *
 */
export const createAnEntry = <ThrowOnError extends boolean = false>(
  options: Options<CreateAnEntryData, ThrowOnError>,
): RequestResult<CreateAnEntryResponses, CreateAnEntryErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateAnEntryResponses,
    CreateAnEntryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/entries",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete an Entry
 *
 * - For Commerce, this endpoint deletes an entry from a flow.
 * - For Product Experience Manager, this endpoint deletes an entry from a template.
 *
 */
export const deleteAnEntry = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAnEntryData, ThrowOnError>,
): RequestResult<DeleteAnEntryResponses, DeleteAnEntryErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteAnEntryResponses,
    DeleteAnEntryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/entries/{flowEntryID}",
    ...options,
  })

/**
 * Get an Entry
 *
 * - For Commerce, this endpoint retrieves an entry from a flow.
 * - For Product Experience Manager, this endpoint retrieves an entry from a template.
 *
 */
export const getAnEntry = <ThrowOnError extends boolean = false>(
  options: Options<GetAnEntryData, ThrowOnError>,
): RequestResult<GetAnEntryResponses, GetAnEntryErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetAnEntryResponses,
    GetAnEntryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/entries/{flowEntryID}",
    ...options,
  })

/**
 * Update an Entry
 *
 * - For Commerce, this endpoint updates an entry for a flow.
 * - For Product Experience Manager, this endpoint updates an entry for a template.
 *
 */
export const updateAnEntry = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAnEntryData, ThrowOnError>,
): RequestResult<UpdateAnEntryResponses, UpdateAnEntryErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateAnEntryResponses,
    UpdateAnEntryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/entries/{flowEntryID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete an Entry Relationship
 *
 * - In Commerce, deletes an entry relationship to one or more resources.
 * - In Product Experience Manager, deletes an entry relationship with the product to which you want to associate the template.
 *
 */
export const deleteAnEntryRelationship = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAnEntryRelationshipData, ThrowOnError>,
): RequestResult<
  DeleteAnEntryRelationshipResponses,
  DeleteAnEntryRelationshipErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteAnEntryRelationshipResponses,
    DeleteAnEntryRelationshipErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/entries/{flowEntryID}/relationships/{flowFieldSlug}",
    ...options,
  })

/**
 * Create an Entry Relationship
 *
 * - In Commerce, create an entry relationship to one or more resources. If any relationships already exist, the ones made in the request are added to them.
 * - In Product Experience Manager, create an entry relationship with the product to which you want to associate the template.
 *
 */
export const createAnEntryRelationship = <ThrowOnError extends boolean = false>(
  options: Options<CreateAnEntryRelationshipData, ThrowOnError>,
): RequestResult<
  CreateAnEntryRelationshipResponses,
  CreateAnEntryRelationshipErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateAnEntryRelationshipResponses,
    CreateAnEntryRelationshipErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/entries/{flowEntryID}/relationships/{flowFieldSlug}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update an Entry Relationship
 *
 * - In Commerce, updates an entry relationship to one or more resources. If any relationships already exist, the ones made in the request are added to them.
 * - In Product Experience Manager, updates an entry relationship with the product to which you want to associate the template.
 *
 */
export const updateAnEntryRelationship = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAnEntryRelationshipData, ThrowOnError>,
): RequestResult<
  UpdateAnEntryRelationshipResponses,
  UpdateAnEntryRelationshipErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateAnEntryRelationshipResponses,
    UpdateAnEntryRelationshipErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/entries/{flowEntryID}/relationships/{flowFieldSlug}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get all Fields by Flow
 *
 * Get all Fields by Flow
 */
export const getAllFieldsByFlow = <ThrowOnError extends boolean = false>(
  options: Options<GetAllFieldsByFlowData, ThrowOnError>,
): RequestResult<
  GetAllFieldsByFlowResponses,
  GetAllFieldsByFlowErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAllFieldsByFlowResponses,
    GetAllFieldsByFlowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/flows/{flowSlug}/fields",
    ...options,
  })
