extends:
  - recommended

apis:
  cart-checkout@v1:
    root: ../cart_checkout.yaml
    output: ../bundled/cart_checkout.yaml
    decorators:
      override/operation-property-override:
        operationIds:
          getACart: ../overrides/getACart.yaml
  catalog_view@v1:
    output: ../bundled/catalog_view.yaml
    root: ../catalog_view.yaml
    decorators:
      override/component-merge:
        mergeRef: ../overrides/catalog_view_components.yaml
      override/operation-property-override:
        operationIds:
          getByContextProduct: ../overrides/getByContextProduct.yaml


plugins:
  - ../plugins/override.js

decorators:
  override/component-merge:
    mergeRef: ../overrides/security-schemes.yaml