extends:
  - recommended

apis:
  cart-checkout@v1:
    root: ../cart_checkout.yaml
    output: ../bundled/cart_checkout.yaml
    decorators:
      override/component-merge:
        mergeRef: ../overrides/cart_checkout_components.yaml
      override/operation-property-override:
        operationIds:
          getACart: ../overrides/getACart.yaml
          getCustomerOrders: ../overrides/getCustomerOrders.yaml
          getAnOrder: ../overrides/getAnOrder.yaml
      ops-extras/prefix-components:
        prefix: CartCheckout
        targets:
          - schemas
        filterKeys:
          - Timestamps
  authentication@v1:
    root: ../authentication.yaml
    output: ../bundled/authentication.yaml
    decorators:
      override/operation-property-override:
        operationIds:
          CreateAnAccessToken: ../overrides/createAnAccessToken.yaml
      ops-extras/prefix-components:
        prefix: Authentication
        targets:
          - responses
        filterKeys:
          - InternalServerError
  catalog_view@v1:
    output: ../bundled/catalog_view.yaml
    root: ../catalog_view.yaml
  subscriptions@v1:
    output: ../bundled/subscriptions.yaml
    root: ../subscriptions.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
      ops-extras/prefix-paths:
        prefix: /v2
      ops-extras/remove-v2-server: true
      ops-extras/prefix-components:
        prefix: Subscriptions
        targets:
          - schemas
          - parameters
          - responses
        filterKeys:
          - Filter
          - PageLimit
          - PageOffset
          - TransactionResponse
          - Timestamps
          - ErrorResponse
          - Error
          - UUID
          - NotFoundError
          - ValidationError
          - InternalServerError
          - SingleRelationship
  inventories@v1:
    output: ../bundled/inventories.yaml
    root: ../inventories.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
      ops-extras/prefix-paths:
        prefix: /v2
      ops-extras/remove-v2-server: true
      ops-extras/prefix-components:
        prefix: Inventories
        targets:
          - schemas
          - parameters
          - responses
        filterKeys:
          - Filter
          - PageLimit
          - PageOffset
          - TransactionResponse
          - Timestamps
          - ErrorResponse
          - Error
          - UUID
          - NotFoundError
          - ValidationError
      ops-extras/prefix-tags:
        prefix: Inventories
        filterTags:
          - Transactions
  account_management@v1:
    output: ../bundled/account_management.yaml
    root: ../account_management.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
      ops-extras/prefix-components:
        prefix: AccountManagement
        targets:
          - schemas
          - responses
        filterKeys:
          - Error
          - MetaTimestamps
          - InternalServerError
          - BadRequestError
          - ErrorResponse
          - UnauthorizedError
  account_addresses@v1:
    output: ../bundled/account-addresses.yaml
    root: ../account-addresses.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
      ops-extras/prefix-components:
        prefix: AccountAddresses
        targets:
          - schemas
          - responses
        filterKeys:
          - Error
          - MetaTimestamps
          - ErrorResponse
  authentication_realms@v1:
    output: ../bundled/authentication-realms.yaml
    root: ../authentication-realms.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
  currencies@v1:
    output: ../bundled/currencies.yaml
    root: ../currencies.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
  files@v1:
    output: ../bundled/files.yaml
    root: ../files.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
      ops-extras/prefix-components:
        prefix: Files
        targets:
          - schemas
          - responses
          - parameters
        filterKeys:
          - Links
          - Error
          - UUID
          - ForbiddenError
          - InternalServerError
          - NotFoundError
          - filter
          - page-limit
          - page-offset
          - ErrorResponse
  catalog_search@v1:
    output: ../bundled/catalog_search.yaml
    root: ../catalog_search.yaml
    preprocessors:
      ops-extras/prefix-components:
        prefix: CatalogSearch
        targets:
          - schemas
          - responses
        filterKeys:
          - Error
          - InternalServerError
          - ErrorResponse
          - Product
plugins:
  - ../plugins/override.js
  - ../plugins/ops-extra.js

decorators:
  override/component-merge:
    mergeRef: ../overrides/security-schemes.yaml
  remove-x-internal: on