extends:
  - recommended

apis:
  cart-checkout@v1:
    root: ../cart_checkout.yaml
    output: ../bundled/cart_checkout.yaml
    decorators:
      override/component-merge:
        mergeRef: ../overrides/cart_checkout_components.yaml
      override/operation-property-override:
        operationIds:
          getACart: ../overrides/getACart.yaml
      ops-extras/prefix-components:
        prefix: CartCheckout
        targets:
          - schemas
        filterKeys:
          - Timestamps
  authentication@v1:
    root: ../authentication.yaml
    output: ../bundled/authentication.yaml
    decorators:
      override/operation-property-override:
        operationIds:
          CreateAnAccessToken: ../overrides/createAnAccessToken.yaml
      ops-extras/prefix-components:
        prefix: Authentication
        targets:
          - responses
        filterKeys:
          - InternalServerError
  catalog_view@v1:
    output: ../bundled/catalog_view.yaml
    root: ../catalog_view.yaml
    decorators:
      override/component-merge:
        mergeRef: ../overrides/catalog_view_components.yaml
      override/operation-property-override:
        operationIds:
          getByContextProduct: ../overrides/getByContextProduct.yaml
          getByContextAllProducts: ../overrides/getByContextAllProducts.yaml
          getByContextProductsForNode: ../overrides/getByContextProductsForNode.yaml
  subscriptions@v1:
    output: ../bundled/subscriptions.yaml
    root: ../subscriptions.yaml
    decorators:
      override/operation-property-override:
        operationIds:
          GetProduct: ../overrides/getSubscriptionProduct.yaml
          ListProducts: ../overrides/listSubscriptionProducts.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
      ops-extras/prefix-paths:
        prefix: /v2
      ops-extras/remove-v2-server: true
      ops-extras/prefix-components:
        prefix: Subscriptions
        targets:
          - schemas
          - parameters
          - responses
        filterKeys:
          - Filter
          - PageLimit
          - PageOffset
          - TransactionResponse
          - Timestamps
          - ErrorResponse
          - Error
          - UUID
          - NotFoundError
          - ValidationError
          - InternalServerError
  inventories@v1:
    output: ../bundled/inventories.yaml
    root: ../inventories.yaml
    preprocessors:
      ops-extras/filter-operations-by-extension:
        extensionName: x-sdk-filter
        extensionValues:
          - shopper
      ops-extras/prefix-paths:
        prefix: /v2
      ops-extras/remove-v2-server: true
      ops-extras/prefix-components:
        prefix: Inventories
        targets:
          - schemas
          - parameters
          - responses
        filterKeys:
          - Filter
          - PageLimit
          - PageOffset
          - TransactionResponse
          - Timestamps
          - ErrorResponse
          - Error
          - UUID
          - NotFoundError
          - ValidationError
      ops-extras/prefix-tags:
        prefix: Inventories
        filterTags:
          - Transactions

plugins:
  - ../plugins/override.js
  - ../plugins/ops-extra.js

decorators:
  override/component-merge:
    mergeRef: ../overrides/security-schemes.yaml