openapi: 3.1.0
jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema"
info:
  title: User Authentication Password Profiles API
  version: "1.0.0"
  description: >
    API for managing user authentication password profile info.
    This API provides endpoints to list, retrieve, create, update, and delete
    user authentication password profile info objects.
  contact:
    name: Elastic Path
    url: 'https://www.elasticpath.com'
    email: support@elasticpath.com
  license:
    name: MIT
    url: 'https://elasticpath.dev'
servers:
  - url: 'https://useast.api.elasticpath.com'
    description: US East
  - url: 'https://euwest.api.elasticpath.com'
    description: EU West
paths:
  /v2/authentication-realms/{realmId}/user-authentication-info/{userAuthenticationInfoId}/user-authentication-password-profile-info:
    parameters:
      - name: realmId
        in: path
        required: true
        description: The identifier for the authentication realm.
        schema:
          type: string
      - name: userAuthenticationInfoId
        in: path
        required: true
        description: The identifier for the user authentication info.
        schema:
          type: string
    get:
      summary: Get all user authentication password profile info
      operationId: listPasswordProfileInfos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of password profile info objects.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordProfileInfoListResponse'
    post:
      summary: Create a new user authentication password profile info
      operationId: createPasswordProfileInfo
      security:
        - bearerAuth: []
      requestBody:
        description: The password profile info to create.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/PasswordProfileInfoCreateRequest'
              required:
                - data
      responses:
        '201':
          description: The created password profile info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordProfileInfoResponse'
  /v2/authentication-realms/{realmId}/user-authentication-info/{userAuthenticationInfoId}/user-authentication-password-profile-info/{userAuthenticationPasswordProfileInfoId}:
    parameters:
      - name: realmId
        in: path
        required: true
        description: The identifier for the authentication realm.
        schema:
          type: string
      - name: userAuthenticationInfoId
        in: path
        required: true
        description: The identifier for the user authentication info.
        schema:
          type: string
      - name: userAuthenticationPasswordProfileInfoId
        in: path
        required: true
        description: The identifier for the user authentication password profile info.
        schema:
          type: string
    get:
      summary: Get a specific user authentication password profile info
      operationId: getPasswordProfileInfo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A single password profile info object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordProfileInfoResponse'
        '404':
          description: Password profile info not found.
    put:
      summary: Update a user authentication password profile info
      operationId: updatePasswordProfileInfo
      security:
        - bearerAuth: []
      requestBody:
        description: The updated password profile info.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/PasswordProfileInfoUpdateRequest'
              required:
                - data
      responses:
        '200':
          description: The updated password profile info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordProfileInfoResponse'
        '404':
          description: Password profile info not found.
    delete:
      summary: Delete a user authentication password profile info
      operationId: deletePasswordProfileInfo
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Password profile info deleted successfully.
        '404':
          description: Password profile info not found.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    PasswordProfileInfo:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the password profile info.
        username:
          type: string
        meta:
          type: object
          properties:
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
          description: Timestamps for creation and last update.
        type:
          type: string
          enum: ["user_authentication_password_profile_info"]
        password_profile_id:
          type: string
          description: Identifier for the associated password profile.
      required:
        - id
        - username
        - meta
        - type
        - password_profile_id
    PasswordProfileInfoResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/PasswordProfileInfo'
        links:
          type: object
          properties:
            self:
              type: string
          description: URL to the resource.
      required:
        - data
    PasswordProfileInfoListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PasswordProfileInfo'
        links:
          type: object
          properties:
            self:
              type: string
          description: URL to the list resource.
    PasswordProfileInfoCreateRequest:
      type: object
      properties:
        type:
          type: string
          enum: ["user_authentication_password_profile_info"]
        username:
          type: string
        password:
          type: string
        password_profile_id:
          type: string
      required:
        - type
        - username
        - password
        - password_profile_id
    PasswordProfileInfoUpdateRequest:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: ["user_authentication_password_profile_info"]
        username:
          type: string
        password:
          type: string
      required:
        - id
        - type
        - username
        - password
