// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | "https://useast.api.elasticpath.com"
    | "https://euwest.api.elasticpath.com"
    | (string & {})
}

export type AuthenticationRealm = {
  /**
   * Specifies the type of object. Set this value to `authentication-realm`.
   */
  type: "authentication-realm"
  /**
   * Specifies the name of the authentication realm.
   */
  name: string
  /**
   * The values permitted for this parameter are, `allowed` or `api_only`. In Single Sign On (SSO) each user in the Identity Provider (IdP) has a unique identifier, but different IdPs might differ in whether distinct users can share the same email address. For the `allowed` setting, when a user with a new unique identifier signs in through SSO for the first time, the system creates a new user. However, for the `api_only` setting, the system assigns the new unique identifier to the existing user in the system, in this case both the old and new unique identifier from the IdP points to the same user in Commerce. The `api_only` setting is recommended only when all configured identity providers treat e-mail address as a unique identifier for the user, otherwise a user might get access to another user’s account and data. Thus the `api_only` value can simplify administration of users.
   */
  duplicate_email_policy?: "allowed" | "disallowed" | "api_only"
  /**
   * An array of Storefront URIs that can start Single Sign On authentication. These URIs must follow the rules for [redirection endpoints in OAuth 2.0.](https://tools.ietf.org/html/rfc6749#section-3.1.2) All URIs must start with https:// except for http://localhost.
   */
  redirect_uris?: Array<string>
  /**
   * Specifies the relationships for this authentication realm.
   */
  relationships?: {
    origin?: {
      data?: {
        /**
         * The ID of the origin entity.
         */
        id?: string
        /**
         * The type of the origin entity.
         */
        type?:
          | "customer-authentication-settings"
          | "merchant-realm-mappings"
          | "account_authentication_settings"
      }
    }
  }
}

/**
 * The unique identifier.
 */
export type Uuid = string

export type MetaTimestamps = {
  /**
   * The date the resource is created.
   */
  created_at?: string
  /**
   * The date the resource is updated.
   */
  updated_at?: string
}

export type AuthenticationRealmResponse = AuthenticationRealm & {
  /**
   * The unique identifier for an Authentication Realm.
   */
  id?: Uuid
  /**
   * Additional information for this realm.
   */
  meta?: MetaTimestamps
  links?: {
    /**
     * A URL to the specific resource.
     */
    self?: string
  }
}

export type MetaListPage = {
  /**
   * The maximum number of records per page for this response. You can set this value up to 100.
   */
  limit?: number
  /**
   * The current page.
   */
  current?: number
  /**
   * The current offset by number of records, not pages. Offset is zero-based.
   */
  offset?: number
  /**
   * The total page count.
   */
  total?: number
}

export type MetaListResults = {
  /**
   * The total number of results after applying filters, if any, or all results.
   */
  total?: number
}

export type MetaList = {
  page?: MetaListPage
  results?: MetaListResults
}

export type Error = {
  /**
   * A brief summary of the error.
   */
  title: string
  /**
   * The HTTP response code of the error.
   */
  status: string
  /**
   * Optional additional detail about the error.
   */
  detail?: string
}

export type SelfLink = {
  /**
   * A URL to the specific resource.
   */
  self?: string
}

export type ErrorResponse = {
  errors: Array<Error>
  links?: SelfLink
}

export type OidcProfile = {
  /**
   * Specifies the type of object. Set this value to `oidc-profile`.
   */
  type: "oidc-profile"
  /**
   * Specifies the name of the OIDC profile.
   */
  name: string
  /**
   * The OIDC discovery URL.
   */
  discovery_url?: string
  /**
   * The client ID for the OpenID Provider.
   */
  client_id?: string
  /**
   * The client secret for the OpenID Provider.
   */
  client_secret?: string
}

export type OidcProfileResponse = OidcProfile & {
  /**
   * The unique identifier for an OIDC Profile.
   */
  id?: Uuid
  meta?: {
    /**
     * The date the resource is created.
     */
    created_at?: string
    /**
     * The date the resource is updated.
     */
    updated_at?: string
    /**
     * The OIDC issuer URL.
     */
    issuer?: string
  }
  links?: {
    /**
     * A URL to the specific resource.
     */
    self?: string
    /**
     * The authorization endpoint URL.
     */
    "authorization-endpoint"?: string
    /**
     * The callback endpoint URL.
     */
    "callback-endpoint"?: string
    /**
     * The client discovery URL.
     */
    "client-discovery-url"?: string
  }
}

export type PaginationLinks = {
  /**
   * The current page of data.
   */
  current?: string
  /**
   * The first page of data.
   */
  first?: string | null
  /**
   * The last page of data.
   */
  last?: string | null
  /**
   * The next page of data.
   */
  next?: string | null
  /**
   * The previous page of data.
   */
  prev?: string | null
  /**
   * The current resource URL.
   */
  self?: string
}

export type PaginationMeta = {
  page?: {
    /**
     * The current page number.
     */
    current?: number
    /**
     * The number of items per page.
     */
    limit?: number
    /**
     * The number of items to offset by.
     */
    offset?: number
    /**
     * The total number of pages.
     */
    total?: number
  }
  results?: {
    /**
     * The total number of results after applying filters, if any, or all results.
     */
    total?: number
  }
}

export type OidcProfileLinks = SelfLink & {
  /**
   * The link that front-end applications should use to authenticate the OpenID Connect profile. The front-end application is responsible for appending all of the [required parameters](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) to the request. The endpoint also forwards some optional parameters, `display`, `prompt` and `ui_locales` to the configured Identity Provider. These parameters allow you to control the behavior of the authentication process on the Identity Provider. Additionally the query parameter `ep_report_callback_replay_error` can be set to `true` in which case if the user revisits the `callback-endpoint` multiple times (e.g., if they hit their Back button), we will redirect the user back to the front end with an [Authentication error response](https://openid.net/specs/openid-connect-core-1_0.html#AuthError) of `callback_replay`.
   */
  "authorization-endpoint"?: string
  /**
   * The link that should be supplied as the callback URL to the upstream authentication provider.
   */
  "callback-endpoint"?: string
  /**
   * The link to the [OpenID Connect Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html) document for this provider, see [here](/docs/api/single-sign-on/get-oidc-idp-stores-store-id-authentication-realms-realm-id-well-known-openid-configuration).
   */
  "client-discovery-url"?: string
}

export type PasswordProfile = {
  /**
   * Specifies the type of object. Set this value to `password_profile`.
   */
  type: "password_profile"
  /**
   * Specifies the name of the password profile.
   */
  name: string
  /**
   * The format the `username` field must be in when creating or updating a [User Authentication Password Profile Info](/docs/api/single-sign-on/post-v-2-authentication-realms-realm-id-user-authentication-info-user-auth-info-id-user-authentication-password-profile-info). You can change the `username_format` setting, however, the changes apply only to the users created or updated after changing this setting. The new setting does not change the `username_format` for existing users.
   */
  username_format?: "email" | "any"
  /**
   * This enables one time password token requests and events for authentication. This feature is disabled by default.
   */
  enable_one_time_password_token?: boolean
}

export type PasswordProfileResponse = PasswordProfile & {
  /**
   * The unique identifier for a Password Profile.
   */
  id?: Uuid
  /**
   * Additional information for this password profile.
   */
  meta?: MetaTimestamps
  links?: {
    /**
     * A URL to the specific resource.
     */
    self?: string
  }
}

export type OneTimePasswordTokenRequestInput = {
  type: "one_time_password_token_request"
  /**
   * An information field indicating why the user submitted this request. Your [integration](/docs/api/integrations/integrations-introduction) can inspect this field and can change subsequent processing.
   */
  purpose: "reset_password" | "passwordless_authentication"
  /**
   * The username for the token request.
   */
  username: string
}

export type OneTimePasswordTokenRequestResponse =
  OneTimePasswordTokenRequestInput & {
    /**
     * The unique identifier for the one-time password token request.
     */
    id?: string
    /**
     * The generated one-time password token.
     */
    token?: string
    /**
     * The expiration time of the token.
     */
    expires_at?: string
    meta?: MetaTimestamps
  }

export type UserAuthenticationInfo = {
  /**
   * Specifies the type of object. Set this value to `user_authentication_info`.
   */
  type: "user_authentication_info"
  /**
   * Specifies the name of the user.
   */
  name: string
  /**
   * Specifies the given name of the user.
   */
  given_name?: string | null
  /**
   * Specifies the family name of the user.
   */
  family_name?: string | null
  /**
   * Specifies the given name of the user.
   */
  middle_name?: string | null
  /**
   * Specifies the email address of the user.
   */
  email: string
}

export type UserAuthenticationInfoResponse = UserAuthenticationInfo & {
  /**
   * The unique identifier for User Authentication Info.
   */
  id?: Uuid
  meta?: {
    /**
     * The date the resource is created.
     */
    created_at?: string
    /**
     * The last updated date of this `user-authentication-info` object. This value also changes if subresources such as the `user-authentication-oidc-profile-info`, or `user-authentication-password-profile-info` change.The last updated date of this `user-authentication-info` object. This value also changes if subresources such as the `user-authentication-oidc-profile-info`, or `user-authentication-password-profile-info` change.
     */
    updated_at?: string
    /**
     * The creation status of the user authentication info.
     */
    creation_status?: "COMPLETE" | "IN_PROGRESS"
  }
  links?: {
    /**
     * A URL to the specific resource.
     */
    self?: string
  }
}

export type UserAuthenticationPasswordProfileInfo = {
  /**
   * Specifies the type of object. Set this value to `user_authentication_password_profile_info`.
   */
  type: "user_authentication_password_profile_info"
  /**
   * The username used to authenticate.
   */
  username: string
  /**
   * The ID of the associated password profile.
   */
  password_profile_id: string
}

export type UserAuthenticationPasswordProfileInfoResponse =
  UserAuthenticationPasswordProfileInfo & {
    /**
     * The unique identifier for User Authentication Password Profile Info.
     */
    id?: Uuid
    /**
     * Additional information for this resource.
     */
    meta?: MetaTimestamps
    links?: {
      /**
       * A URL to the specific resource.
       */
      self?: string
    }
  }

export type UserAuthenticationPasswordProfileInfoInput =
  UserAuthenticationPasswordProfileInfo & {
    /**
     * The password used to authenticate.
     */
    password: string
  }

export type UserAuthenticationOidcProfileInfo = {
  /**
   * Specifies the type of object. Set this value to `user_authentication_oidc_profile_info`.
   */
  type: "user_authentication_oidc_profile_info"
  /**
   * The ID of the associated [OIDC profile](/docs/authentication/single-sign-on/openid-connect-profiles-api/openid-connect-profiles-api-overview).
   */
  oidc_profile_id: string
  /**
   * The identifier within the issuer for the `user-authentication-info` object. For more information, see the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) section.
   */
  subject?: string
  /**
   * The identifier for the issuer of the ID Token. For more information, see the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) section.
   */
  issuer?: string
}

export type UserAuthenticationOidcProfileInfoResponse =
  UserAuthenticationOidcProfileInfo & {
    /**
     * The unique identifier for User Authentication OIDC Profile Info.
     */
    id?: Uuid
    /**
     * Additional information for this resource.
     */
    meta?: MetaTimestamps
    links?: {
      /**
       * A URL to the specific resource.
       */
      self?: string
    }
  }

export type UserAuthenticationPasswordProfileInfoUpdateInput = {
  /**
   * The unique identifier for User Authentication Password Profile Info. Must match the id in the path.
   */
  id: string
  /**
   * Specifies the type of object. Set this value to `user_authentication_password_profile_info`.
   */
  type: "user_authentication_password_profile_info"
  /**
   * The username used to authenticate.
   */
  username?: string
  /**
   * The password used to authenticate.
   */
  password?: string
}

export type UserAuthenticationInfoUpdateInput = {
  /**
   * Specifies the type of object. Set this value to `user_authentication_info`.
   */
  type: "user_authentication_info"
  /**
   * Specifies the name of the user.
   */
  name?: string
  /**
   * Specifies the given name of the user.
   */
  given_name?: string | null
  /**
   * Specifies the family name of the user.
   */
  family_name?: string | null
  /**
   * Specifies the middle name of the user.
   */
  middle_name?: string | null
  /**
   * Specifies the email address of the user.
   */
  email?: string
}

export type AuthenticationRealmUpdateInput = {
  /**
   * The authentication realm ID. Optional. If present, it must match the ID in the path.
   */
  id?: string
  /**
   * Specifies the type of object. Set this value to `authentication-realm`.
   */
  type: "authentication-realm"
  /**
   * Specifies the name of the authentication realm.
   */
  name?: string
  /**
   * The values permitted for this parameter are, `allowed` or `api_only`. In Single Sign On (SSO) each user in the Identity Provider (IdP) has a unique identifier, but different IdPs might differ in whether distinct users can share the same email address. For the `allowed` setting, when a user with a new unique identifier signs in through SSO for the first time, the system creates a new user. However, for the `api_only` setting, the system assigns the new unique identifier to the existing user in the system, in this case both the old and new unique identifier from the IdP points to the same user in Commerce. The `api_only` setting is recommended only when all configured identity providers treat e-mail address as a unique identifier for the user, otherwise a user might get access to another user’s account and data. Thus the `api_only` value can simplify administration of users.
   */
  duplicate_email_policy?: "allowed" | "api_only"
  /**
   * An array of Storefront URIs that can start Single Sign On authentication. These URIs must follow the rules for [redirection endpoints in OAuth 2.0.](https://tools.ietf.org/html/rfc6749#section-3.1.2) All URIs must start with https:// except for http://localhost.
   */
  redirect_uris?: Array<string>
  /**
   * Specifies the relationships for this authentication realm.
   */
  relationships?: {
    origin?: {
      data?: {
        /**
         * The ID of the origin entity.
         */
        id?: string
        /**
         * The type of the origin entity.
         */
        type?:
          | "customer-authentication-settings"
          | "merchant-realm-mappings"
          | "account_authentication_settings"
      }
    }
  }
}

export type OidcProfileCreateInput = {
  /**
   * Specifies the type of object. Set this value to `oidc-profile`.
   */
  type: "oidc-profile"
  /**
   * Specifies the name of the OIDC profile.
   */
  name: string
  /**
   * The OIDC discovery URL.
   */
  discovery_url: string
  /**
   * The client ID for the OpenID Provider.
   */
  client_id: string
  /**
   * The client secret for the OpenID Provider.
   */
  client_secret: string
}

export type OidcProfileUpdateInput = {
  /**
   * The OIDC profile ID. Optional. If present, it must match the ID in the path.
   */
  id?: string
  /**
   * Specifies the type of object. Set this value to `oidc-profile`.
   */
  type: "oidc-profile"
  /**
   * Specifies the name of the OIDC profile.
   */
  name?: string
  /**
   * The OIDC discovery URL.
   */
  discovery_url?: string
  /**
   * The client ID for the OpenID Provider.
   */
  client_id?: string
  /**
   * The client secret for the OpenID Provider.
   */
  client_secret?: string
}

export type PasswordProfileUpdateInput = {
  /**
   * The password profile ID. Optional. If present, it must match the ID in the path.
   */
  id?: string
  /**
   * Specifies the type of object. Set this value to `password_profile`.
   */
  type: "password_profile"
  /**
   * Specifies the name of the password profile.
   */
  name?: string
  /**
   * The format the `username` field must be in when creating or updating a [User Authentication Password Profile Info](/docs/api/single-sign-on/post-v-2-authentication-realms-realm-id-user-authentication-info-user-auth-info-id-user-authentication-password-profile-info). You can change the `username_format` setting, however, the changes apply only to the users created or updated after changing this setting. The new setting does not change the `username_format` for existing users.
   */
  username_format?: "email" | "any"
  /**
   * This enables one time password token requests and events for authentication. This feature is disabled by default.
   */
  enable_one_time_password_token?: boolean
}

export type UserAuthenticationOidcProfileInfoCreateInput = {
  /**
   * Specifies the type of object. Set this value to `user_authentication_oidc_profile_info`.
   */
  type: "user_authentication_oidc_profile_info"
  /**
   * The ID of the associated [OIDC profile](/docs/authentication/single-sign-on/openid-connect-profiles-api/openid-connect-profiles-api-overview).
   */
  oidc_profile_id: string
  /**
   * The identifier within the issuer for the `user-authentication-info` object. For more information, see the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) section.
   */
  subject: string
  /**
   * The identifier for the issuer of the ID Token. For more information, see the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) section.
   */
  issuer: string
}

export type UserAuthenticationOidcProfileInfoUpdateInput = {
  /**
   * Specifies the type of object. Set this value to `user_authentication_oidc_profile_info`.
   */
  type: "user_authentication_oidc_profile_info"
  /**
   * The identifier within the issuer for the `user-authentication-info` object. For more information, see the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) section.
   */
  subject?: string
  /**
   * The identifier for the issuer of the ID Token. For more information, see the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) section.
   */
  issuer?: string
}

/**
 * The number of records per page.
 */
export type PageLimit = number

/**
 * The number of records to offset the results by.
 */
export type PageOffset = number

/**
 * Specifies the filter attributes.
 */
export type Filter = string

export type GetOidcIdpLoginStoresStoreIdAuthenticationRealmsRealmIdData = {
  body?: never
  path: {
    /**
     * The ID of the store.
     */
    storeId: string
    /**
     * The ID of the authentication realm.
     */
    realmId: string
  }
  query: {
    /**
     * The Client ID, for Account Management Authentication see the `meta.client_id` field on [Account Authentication Settings](/docs/api/accounts/get-v-2-settings-account-authentication).
     */
    client_id: string
    /**
     * Redirection URI to which the response will be sent. Must exactly match a pre-registered redirect URI for the client in the `redirect_uris` of the [Authentication Realm](/docs/api/single-sign-on/get-v-2-authentication-realms-realm-id).
     */
    redirect_uri: string
    /**
     * OIDC/OAuth 2.0 response type, this must be "code" in Commerce.
     */
    response_type: "code"
    /**
     * Space-delimited list of scopes. Must include "openid", "email", and "name".
     */
    scope: string
    /**
     * Opaque value used to maintain state between the request and the callback. Helps prevent CSRF.
     */
    state: string
    /**
     * [Proof Key for Code Exchange (PKCE)](https://datatracker.ietf.org/doc/html/rfc7636) transformation method that was used to derive code_challenge.
     */
    code_challenge_method: "S256" | "plain"
    /**
     * [Proof Key for Code Exchange (PKCE)](https://datatracker.ietf.org/doc/html/rfc7636) Code Challenge.
     */
    code_challenge: string
    /**
     * Space-delimited, case-sensitive list that specifies whether the Authorization Server prompts the End-User for re-authentication and consent.  This value is passed to the configured IdP. See [Section 3.1.2.1. Authentication Request - OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).
     */
    prompt?: string
    /**
     * ASCII string value that specifies how the Authorization Server displays the authentication and consent user interface. This value is passed to the configured IdP. See [Section 3.1.2.1. Authentication Request - OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).
     */
    display?: string
    /**
     * End-User's preferred languages and scripts for the user interface, represented as space-separated list of BCP47 language tag values. This value is forwarded to the configured IdP.  See [Section 3.1.2.1. Authentication Request - OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).
     */
    ui_locales?: string
    /**
     * Selects the specific OIDC Profile within the realm to use for authentication.
     */
    elasticpath_commerce_cloud_profile_id: string
    /**
     * Custom boolean flag. If true, if the user attempts to hit back in their browser, we will redirect them back to the store front
     */
    ep_report_callback_replay_error?: boolean
  }
  url: "/oidc-idp/login/stores/{storeId}/authentication-realms/{realmId}"
}

export type GetOidcIdpLoginStoresStoreIdAuthenticationRealmsRealmIdErrors = {
  /**
   * In some cases the OAuth 2.0 specification does not permit us to redirect the user back to the caller, in which case they will see a 4xx.
   *
   */
  400: {
    /**
     * OAuth 2.0 error code
     */
    error: string
    /**
     * Human-readable error description (camelCase)
     */
    errorDescription?: string
    /**
     * Human-readable error description (snake_case, OAuth 2.0 standard)
     */
    error_description?: string
  }
}

export type GetOidcIdpLoginStoresStoreIdAuthenticationRealmsRealmIdError =
  GetOidcIdpLoginStoresStoreIdAuthenticationRealmsRealmIdErrors[keyof GetOidcIdpLoginStoresStoreIdAuthenticationRealmsRealmIdErrors]

export type GetOidcIdpStoresStoreIdAuthenticationRealmsRealmIdWellKnownOpenidConfigurationData =
  {
    body?: never
    path: {
      /**
       * The ID of the store.
       */
      storeId: string
      /**
       * The ID of the authentication realm.
       */
      realmId: string
    }
    query?: {
      /**
       * The ID of the [OIDC profile](/docs/api/single-sign-on/oidc-profiles) that you would like to authenticate with
       */
      elasticpath_commerce_cloud_profile_id?: string
    }
    url: "/oidc-idp/stores/{storeId}/authentication-realms/{realmId}/.well-known/openid-configuration"
  }

export type GetOidcIdpStoresStoreIdAuthenticationRealmsRealmIdWellKnownOpenidConfigurationResponses =
  {
    /**
     * OK - OpenID Connect discovery document
     */
    200: {
      /**
       * The issuer identifier for this OIDC provider
       */
      issuer: string
      /**
       * URL of the authorization endpoint
       */
      authorization_endpoint: string
      /**
       * URL of the token endpoint, note that this endpoint is not public, and clients will not call it.
       */
      token_endpoint: string
      /**
       * URL of the JSON Web Key Set document
       */
      jwks_uri: string
      /**
       * List of OAuth 2.0 response_type values supported
       */
      response_types_supported: Array<string>
      /**
       * List of subject identifier types supported
       */
      subject_types_supported: Array<string>
      /**
       * List of JWS signing algorithms supported for ID Tokens
       */
      id_token_signing_alg_values_supported: Array<string>
      /**
       * List of OAuth 2.0 scope values supported
       */
      scopes_supported?: Array<string>
      /**
       * Authentication methods supported by the token endpoint
       */
      token_endpoint_auth_methods_supported?: string
    }
  }

export type GetOidcIdpStoresStoreIdAuthenticationRealmsRealmIdWellKnownOpenidConfigurationResponse =
  GetOidcIdpStoresStoreIdAuthenticationRealmsRealmIdWellKnownOpenidConfigurationResponses[keyof GetOidcIdpStoresStoreIdAuthenticationRealmsRealmIdWellKnownOpenidConfigurationResponses]

export type GetV2AuthenticationRealmsData = {
  body?: never
  path?: never
  query?: {
    /**
     * The number of records per page.
     */
    "page[limit]"?: number
    /**
     * The number of records to offset the results by.
     */
    "page[offset]"?: number
  }
  url: "/v2/authentication-realms"
}

export type GetV2AuthenticationRealmsErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Unauthorized
   */
  401: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type GetV2AuthenticationRealmsError =
  GetV2AuthenticationRealmsErrors[keyof GetV2AuthenticationRealmsErrors]

export type GetV2AuthenticationRealmsResponses = {
  /**
   * OK
   */
  200: {
    data?: Array<AuthenticationRealmResponse>
    meta?: MetaList
    links?: {
      /**
       * Always the current page.
       */
      current?: string
      /**
       * Always the first page.
       */
      first?: string
      /**
       * Always null if there is only one page.
       */
      last?: string | null
      /**
       * Always null if there is only one page.
       */
      next?: string | null
      /**
       * Always null if the user is on the first page.
       */
      prev?: string | null
    }
  }
}

export type GetV2AuthenticationRealmsResponse =
  GetV2AuthenticationRealmsResponses[keyof GetV2AuthenticationRealmsResponses]

export type GetV2AuthenticationRealmsRealmIdData = {
  body?: never
  path: {
    /**
     * The ID of the authentication realm to retrieve.
     */
    realmId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}"
}

export type GetV2AuthenticationRealmsRealmIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type GetV2AuthenticationRealmsRealmIdError =
  GetV2AuthenticationRealmsRealmIdErrors[keyof GetV2AuthenticationRealmsRealmIdErrors]

export type GetV2AuthenticationRealmsRealmIdResponses = {
  /**
   * OK
   */
  200: {
    data?: AuthenticationRealmResponse
    links?: SelfLink
  }
}

export type GetV2AuthenticationRealmsRealmIdResponse =
  GetV2AuthenticationRealmsRealmIdResponses[keyof GetV2AuthenticationRealmsRealmIdResponses]

export type PutV2AuthenticationRealmsRealmIdData = {
  body: {
    data: AuthenticationRealmUpdateInput
  }
  path: {
    /**
     * The ID of the authentication realm to update.
     */
    realmId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}"
}

export type PutV2AuthenticationRealmsRealmIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type PutV2AuthenticationRealmsRealmIdError =
  PutV2AuthenticationRealmsRealmIdErrors[keyof PutV2AuthenticationRealmsRealmIdErrors]

export type PutV2AuthenticationRealmsRealmIdResponses = {
  /**
   * OK
   */
  200: {
    data?: AuthenticationRealmResponse
    links?: SelfLink
  }
}

export type PutV2AuthenticationRealmsRealmIdResponse =
  PutV2AuthenticationRealmsRealmIdResponses[keyof PutV2AuthenticationRealmsRealmIdResponses]

export type GetV2AuthenticationRealmsRealmIdOidcProfilesData = {
  body?: never
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
  }
  query?: {
    /**
     * The number of records per page.
     */
    "page[limit]"?: number
    /**
     * The number of records to offset the results by.
     */
    "page[offset]"?: number
  }
  url: "/v2/authentication-realms/{realmId}/oidc-profiles"
}

export type GetV2AuthenticationRealmsRealmIdOidcProfilesErrors = {
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type GetV2AuthenticationRealmsRealmIdOidcProfilesError =
  GetV2AuthenticationRealmsRealmIdOidcProfilesErrors[keyof GetV2AuthenticationRealmsRealmIdOidcProfilesErrors]

export type GetV2AuthenticationRealmsRealmIdOidcProfilesResponses = {
  /**
   * OK
   */
  200: {
    data?: Array<OidcProfileResponse>
    links?: PaginationLinks
    meta?: PaginationMeta
  }
}

export type GetV2AuthenticationRealmsRealmIdOidcProfilesResponse =
  GetV2AuthenticationRealmsRealmIdOidcProfilesResponses[keyof GetV2AuthenticationRealmsRealmIdOidcProfilesResponses]

export type PostV2AuthenticationRealmsRealmIdOidcProfilesData = {
  body: {
    data: OidcProfileCreateInput
  }
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/oidc-profiles"
}

export type PostV2AuthenticationRealmsRealmIdOidcProfilesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type PostV2AuthenticationRealmsRealmIdOidcProfilesError =
  PostV2AuthenticationRealmsRealmIdOidcProfilesErrors[keyof PostV2AuthenticationRealmsRealmIdOidcProfilesErrors]

export type PostV2AuthenticationRealmsRealmIdOidcProfilesResponses = {
  /**
   * Created
   */
  201: {
    data?: OidcProfileResponse
    links?: OidcProfileLinks
  }
}

export type PostV2AuthenticationRealmsRealmIdOidcProfilesResponse =
  PostV2AuthenticationRealmsRealmIdOidcProfilesResponses[keyof PostV2AuthenticationRealmsRealmIdOidcProfilesResponses]

export type DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdData = {
  body?: never
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
    /**
     * The ID of the OIDC profile.
     */
    profileId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/oidc-profiles/{profileId}"
}

export type DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdError =
  DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors[keyof DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors]

export type DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses =
  {
    /**
     * No Content
     */
    204: void
  }

export type DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponse =
  DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses[keyof DeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses]

export type GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdData = {
  body?: never
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
    /**
     * The ID of the OIDC profile.
     */
    profileId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/oidc-profiles/{profileId}"
}

export type GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdError =
  GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors[keyof GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors]

export type GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses = {
  /**
   * OK
   */
  200: {
    data?: OidcProfileResponse
    links?: OidcProfileLinks
  }
}

export type GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponse =
  GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses[keyof GetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses]

export type PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdData = {
  body: {
    data: OidcProfileUpdateInput
  }
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
    /**
     * The ID of the OIDC profile.
     */
    profileId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/oidc-profiles/{profileId}"
}

export type PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdError =
  PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors[keyof PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdErrors]

export type PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses = {
  /**
   * OK
   */
  200: {
    data?: OidcProfileResponse
    links?: OidcProfileLinks
  }
}

export type PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponse =
  PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses[keyof PutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponses]

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesData = {
  body?: never
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
  }
  query?: {
    /**
     * The number of records per page.
     */
    "page[limit]"?: number
    /**
     * The number of records to offset the results by.
     */
    "page[offset]"?: number
  }
  url: "/v2/authentication-realms/{realmId}/password-profiles"
}

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesErrors = {
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesError =
  GetV2AuthenticationRealmsRealmIdPasswordProfilesErrors[keyof GetV2AuthenticationRealmsRealmIdPasswordProfilesErrors]

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesResponses = {
  /**
   * OK
   */
  200: {
    data?: Array<PasswordProfileResponse>
    links?: PaginationLinks
    meta?: PaginationMeta
  }
}

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesResponse =
  GetV2AuthenticationRealmsRealmIdPasswordProfilesResponses[keyof GetV2AuthenticationRealmsRealmIdPasswordProfilesResponses]

export type PostV2AuthenticationRealmsRealmIdPasswordProfilesData = {
  body: {
    data: PasswordProfile
  }
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/password-profiles"
}

export type PostV2AuthenticationRealmsRealmIdPasswordProfilesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type PostV2AuthenticationRealmsRealmIdPasswordProfilesError =
  PostV2AuthenticationRealmsRealmIdPasswordProfilesErrors[keyof PostV2AuthenticationRealmsRealmIdPasswordProfilesErrors]

export type PostV2AuthenticationRealmsRealmIdPasswordProfilesResponses = {
  /**
   * Created
   */
  201: {
    data?: PasswordProfileResponse
    links?: SelfLink
  }
}

export type PostV2AuthenticationRealmsRealmIdPasswordProfilesResponse =
  PostV2AuthenticationRealmsRealmIdPasswordProfilesResponses[keyof PostV2AuthenticationRealmsRealmIdPasswordProfilesResponses]

export type DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdData = {
  body?: never
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
    /**
     * The ID of the password profile.
     */
    profileId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/password-profiles/{profileId}"
}

export type DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdError =
  DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors[keyof DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors]

export type DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses =
  {
    /**
     * No Content
     */
    204: void
  }

export type DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponse =
  DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses[keyof DeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses]

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdData = {
  body?: never
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
    /**
     * The ID of the password profile.
     */
    profileId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/password-profiles/{profileId}"
}

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdError =
  GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors[keyof GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors]

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses =
  {
    /**
     * OK
     */
    200: {
      data?: PasswordProfileResponse
      links?: SelfLink
    }
  }

export type GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponse =
  GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses[keyof GetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses]

export type PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdData = {
  body: {
    data: PasswordProfileUpdateInput
  }
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
    /**
     * The ID of the password profile.
     */
    profileId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/password-profiles/{profileId}"
}

export type PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdError =
  PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors[keyof PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdErrors]

export type PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses =
  {
    /**
     * OK
     */
    200: {
      data?: PasswordProfileResponse
      links?: SelfLink
    }
  }

export type PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponse =
  PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses[keyof PutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponses]

export type CreateOneTimePasswordTokenRequestData = {
  body: {
    data: OneTimePasswordTokenRequestInput
  }
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
    /**
     * The ID of the password profile.
     */
    profileId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/password-profiles/{profileId}/one-time-password-token-request"
}

export type CreateOneTimePasswordTokenRequestErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type CreateOneTimePasswordTokenRequestError =
  CreateOneTimePasswordTokenRequestErrors[keyof CreateOneTimePasswordTokenRequestErrors]

export type CreateOneTimePasswordTokenRequestResponses = {
  /**
   * Created
   */
  201: {
    data?: OneTimePasswordTokenRequestResponse
  }
  /**
   * Accepted
   */
  202: unknown
}

export type CreateOneTimePasswordTokenRequestResponse =
  CreateOneTimePasswordTokenRequestResponses[keyof CreateOneTimePasswordTokenRequestResponses]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoData = {
  body?: never
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
  }
  query?: {
    /**
     * The number of records per page.
     */
    "page[limit]"?: number
    /**
     * The number of records to offset the results by.
     */
    "page[offset]"?: number
    /**
     * Specifies the filter attributes.
     */
    filter?: string
    /**
     * Specifies the order in which account members will be returned. For more information, see [Sorting](/guides/Getting-Started/sorting).
     */
    sort?:
      | "created_at"
      | "-created_at"
      | "id"
      | "-id"
      | "updated_at"
      | "-updated_at"
  }
  url: "/v2/authentication-realms/{realmId}/user-authentication-info"
}

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoError =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoErrors[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoErrors]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponses = {
  /**
   * OK
   */
  200: {
    data?: Array<UserAuthenticationInfoResponse>
    meta?: MetaList
    links?: {
      /**
       * Always the current page.
       */
      current?: string
      /**
       * Always the first page.
       */
      first?: string
      /**
       * Always null if there is only one page.
       */
      last?: string | null
      /**
       * Always null if there is only one page.
       */
      next?: string | null
      /**
       * Always null if the user is on the first page.
       */
      prev?: string | null
    }
  }
}

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponse =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponses[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponses]

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoData = {
  body: {
    data: UserAuthenticationInfo
  }
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/user-authentication-info"
}

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoError =
  PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoErrors[keyof PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoErrors]

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponses = {
  /**
   * Created
   */
  201: {
    data?: UserAuthenticationInfoResponse
    links?: {
      /**
       * A URL to the specific resource.
       */
      self?: string
    }
  }
}

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponse =
  PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponses[keyof PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponses]

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdData =
  {
    body?: never
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}"
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors =
  {
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdError =
  DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors[keyof DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors]

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses =
  {
    /**
     * No Content
     */
    204: void
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponse =
  DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses[keyof DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdData =
  {
    body?: never
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}"
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdError =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses =
  {
    /**
     * OK
     */
    200: {
      data?: UserAuthenticationInfoResponse
      links?: SelfLink
    }
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponse =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses]

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdData =
  {
    body: {
      data: UserAuthenticationInfoUpdateInput
    }
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}"
  }

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdError =
  PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors[keyof PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdErrors]

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses =
  {
    /**
     * OK
     */
    200: {
      data?: UserAuthenticationInfoResponse
      links?: SelfLink
    }
  }

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponse =
  PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses[keyof PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponses]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoData =
  {
    body?: never
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
    }
    query?: {
      /**
       * The number of records per page.
       */
      "page[limit]"?: number
      /**
       * The number of records to offset the results by.
       */
      "page[offset]"?: number
    }
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-password-profile-info"
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoErrors =
  {
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoError =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoErrors[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoErrors]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponses =
  {
    /**
     * OK
     */
    200: {
      data?: Array<UserAuthenticationPasswordProfileInfoResponse>
      links?: PaginationLinks
      meta?: PaginationMeta
    }
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponse =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponses[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponses]

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoData =
  {
    body: {
      data: UserAuthenticationPasswordProfileInfoInput
    }
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-password-profile-info"
  }

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoError =
  PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoErrors[keyof PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoErrors]

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponses =
  {
    /**
     * Created
     */
    201: {
      data?: UserAuthenticationPasswordProfileInfoResponse
      links?: {
        /**
         * A URL to the specific resource.
         */
        self?: string
      }
    }
  }

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponse =
  PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponses[keyof PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponses]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoData =
  {
    body?: never
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
    }
    query?: {
      /**
       * The number of records per page.
       */
      "page[limit]"?: number
      /**
       * The number of records to offset the results by.
       */
      "page[offset]"?: number
    }
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-oidc-profile-info"
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoErrors =
  {
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoError =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoErrors[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoErrors]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponses =
  {
    /**
     * OK
     */
    200: {
      data?: Array<UserAuthenticationOidcProfileInfoResponse>
      links?: PaginationLinks
      meta?: PaginationMeta
    }
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponse =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponses[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponses]

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoData =
  {
    body: {
      data: UserAuthenticationOidcProfileInfoCreateInput
    }
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-oidc-profile-info"
  }

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoError =
  PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoErrors[keyof PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoErrors]

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponses =
  {
    /**
     * Created
     */
    201: {
      data?: UserAuthenticationOidcProfileInfoResponse
      links?: SelfLink
    }
  }

export type PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponse =
  PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponses[keyof PostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponses]

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdData =
  {
    body?: never
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
      /**
       * The ID of the OIDC profile info.
       */
      oidcInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-oidc-profile-info/{oidcInfoId}"
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdError =
  DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors[keyof DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors]

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses =
  {
    /**
     * No Content
     */
    204: void
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponse =
  DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses[keyof DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdData =
  {
    body?: never
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
      /**
       * The ID of the OIDC profile info.
       */
      oidcInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-oidc-profile-info/{oidcInfoId}"
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdError =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses =
  {
    /**
     * OK
     */
    200: {
      data?: UserAuthenticationOidcProfileInfoResponse
      links?: SelfLink
    }
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponse =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses]

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdData =
  {
    body: {
      data: UserAuthenticationOidcProfileInfoUpdateInput
    }
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
      /**
       * The ID of the OIDC profile info.
       */
      oidcInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-oidc-profile-info/{oidcInfoId}"
  }

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdError =
  PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors[keyof PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdErrors]

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses =
  {
    /**
     * OK
     */
    200: {
      data?: UserAuthenticationOidcProfileInfoResponse
      links?: SelfLink
    }
  }

export type PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponse =
  PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses[keyof PutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponses]

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdData =
  {
    body?: never
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
      /**
       * The ID of the password profile info.
       */
      passwordProfileInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-password-profile-info/{passwordProfileInfoId}"
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdError =
  DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdErrors[keyof DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdErrors]

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponses =
  {
    /**
     * No Content
     */
    204: void
  }

export type DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponse =
  DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponses[keyof DeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponses]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdData =
  {
    body?: never
    path: {
      /**
       * The ID of the authentication realm.
       */
      realmId: string
      /**
       * The ID of the user authentication info.
       */
      userAuthInfoId: string
      /**
       * The ID of the password profile info.
       */
      passwordProfileInfoId: string
    }
    query?: never
    url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-password-profile-info/{passwordProfileInfoId}"
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdErrors =
  {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal server error.
     */
    500: ErrorResponse
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdError =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdErrors[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdErrors]

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponses =
  {
    /**
     * OK
     */
    200: {
      data?: UserAuthenticationPasswordProfileInfoResponse
      links?: SelfLink
    }
  }

export type GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponse =
  GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponses[keyof GetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponses]

export type UpdatePasswordProfileInfoData = {
  body: {
    data: UserAuthenticationPasswordProfileInfoUpdateInput
  }
  path: {
    /**
     * The ID of the authentication realm.
     */
    realmId: string
    /**
     * The ID of the user authentication info.
     */
    userAuthInfoId: string
    /**
     * The ID of the password profile info.
     */
    passwordProfileInfoId: string
  }
  query?: never
  url: "/v2/authentication-realms/{realmId}/user-authentication-info/{userAuthInfoId}/user-authentication-password-profile-info/{passwordProfileInfoId}"
}

export type UpdatePasswordProfileInfoErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse
  /**
   * Internal server error.
   */
  500: ErrorResponse
}

export type UpdatePasswordProfileInfoError =
  UpdatePasswordProfileInfoErrors[keyof UpdatePasswordProfileInfoErrors]

export type UpdatePasswordProfileInfoResponses = {
  /**
   * OK
   */
  200: {
    data?: UserAuthenticationPasswordProfileInfoResponse
    links?: SelfLink
  }
}

export type UpdatePasswordProfileInfoResponse =
  UpdatePasswordProfileInfoResponses[keyof UpdatePasswordProfileInfoResponses]
