// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod"

export const zAuthenticationRealm = z.object({
  type: z.literal("authentication-realm"),
  name: z.string(),
  duplicate_email_policy: z
    .enum(["allowed", "disallowed", "api_only"])
    .optional(),
  redirect_uris: z.array(z.string().url()).optional(),
  relationships: z
    .object({
      origin: z
        .object({
          data: z
            .object({
              id: z.string().optional(),
              type: z
                .enum([
                  "customer-authentication-settings",
                  "merchant-realm-mappings",
                  "account_authentication_settings",
                ])
                .optional(),
            })
            .optional(),
        })
        .optional(),
    })
    .optional(),
})

/**
 * The unique identifier.
 */
export const zUuid = z.string().uuid()

export const zMetaTimestamps = z.object({
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
})

export const zAuthenticationRealmResponse = zAuthenticationRealm.and(
  z.object({
    id: zUuid.optional(),
    meta: zMetaTimestamps.optional(),
    links: z
      .object({
        self: z.string().url().optional(),
      })
      .optional(),
  }),
)

export const zMetaListPage = z.object({
  limit: z.number().int().optional(),
  current: z.number().int().optional(),
  offset: z.number().int().optional(),
  total: z.number().int().optional(),
})

export const zMetaListResults = z.object({
  total: z.number().int().optional(),
})

export const zMetaList = z.object({
  page: zMetaListPage.optional(),
  results: zMetaListResults.optional(),
})

export const zError = z.object({
  title: z.string(),
  status: z.string(),
  detail: z.string().optional(),
})

export const zSelfLink = z.object({
  self: z.string().url().optional(),
})

export const zErrorResponse = z.object({
  errors: z.array(zError),
  links: zSelfLink.optional(),
})

export const zOidcProfile = z.object({
  type: z.literal("oidc-profile"),
  name: z.string(),
  discovery_url: z.string().url().optional(),
  client_id: z.string().optional(),
  client_secret: z.string().optional(),
})

export const zOidcProfileResponse = zOidcProfile.and(
  z.object({
    id: zUuid.optional(),
    meta: z
      .object({
        created_at: z.string().datetime().optional(),
        updated_at: z.string().datetime().optional(),
        issuer: z.string().url().optional(),
      })
      .optional(),
    links: z
      .object({
        self: z.string().url().optional(),
        "authorization-endpoint": z.string().url().optional(),
        "callback-endpoint": z.string().url().optional(),
        "client-discovery-url": z.string().url().optional(),
      })
      .optional(),
  }),
)

export const zPaginationLinks = z.object({
  current: z.string().url().optional(),
  first: z.string().url().nullish(),
  last: z.string().url().nullish(),
  next: z.string().url().nullish(),
  prev: z.string().url().nullish(),
  self: z.string().url().optional(),
})

export const zPaginationMeta = z.object({
  page: z
    .object({
      current: z.number().int().optional(),
      limit: z.number().int().optional(),
      offset: z.number().int().optional(),
      total: z.number().int().optional(),
    })
    .optional(),
  results: z
    .object({
      total: z.number().int().optional(),
    })
    .optional(),
})

export const zOidcProfileLinks = zSelfLink.and(
  z.object({
    "authorization-endpoint": z.string().url().optional(),
    "callback-endpoint": z.string().url().optional(),
    "client-discovery-url": z.string().url().optional(),
  }),
)

export const zPasswordProfile = z.object({
  type: z.literal("password_profile"),
  name: z.string(),
  username_format: z.enum(["email", "any"]).optional(),
  enable_one_time_password_token: z.boolean().optional(),
})

export const zPasswordProfileResponse = zPasswordProfile.and(
  z.object({
    id: zUuid.optional(),
    meta: zMetaTimestamps.optional(),
    links: z
      .object({
        self: z.string().url().optional(),
      })
      .optional(),
  }),
)

export const zOneTimePasswordTokenRequestInput = z.object({
  type: z.literal("one_time_password_token_request"),
  purpose: z.enum(["reset_password", "passwordless_authentication"]),
  username: z.string(),
})

export const zOneTimePasswordTokenRequestResponse =
  zOneTimePasswordTokenRequestInput.and(
    z.object({
      id: z.string().uuid().optional(),
      token: z.string().optional(),
      expires_at: z.string().datetime().optional(),
      meta: zMetaTimestamps.optional(),
    }),
  )

export const zUserAuthenticationInfo = z.object({
  type: z.literal("user_authentication_info"),
  name: z.string(),
  given_name: z.string().nullish(),
  family_name: z.string().nullish(),
  middle_name: z.string().nullish(),
  email: z.string().email(),
})

export const zUserAuthenticationInfoResponse = zUserAuthenticationInfo.and(
  z.object({
    id: zUuid.optional(),
    meta: z
      .object({
        created_at: z.string().datetime().optional(),
        updated_at: z.string().datetime().optional(),
        creation_status: z.enum(["COMPLETE", "IN_PROGRESS"]).optional(),
      })
      .optional(),
    links: z
      .object({
        self: z.string().url().optional(),
      })
      .optional(),
  }),
)

export const zUserAuthenticationPasswordProfileInfo = z.object({
  type: z.literal("user_authentication_password_profile_info"),
  username: z.string(),
  password_profile_id: z.string().uuid(),
})

export const zUserAuthenticationPasswordProfileInfoResponse =
  zUserAuthenticationPasswordProfileInfo.and(
    z.object({
      id: zUuid.optional(),
      meta: zMetaTimestamps.optional(),
      links: z
        .object({
          self: z.string().url().optional(),
        })
        .optional(),
    }),
  )

export const zUserAuthenticationPasswordProfileInfoInput =
  zUserAuthenticationPasswordProfileInfo.and(
    z.object({
      password: z.string().min(8),
    }),
  )

export const zUserAuthenticationOidcProfileInfo = z.object({
  type: z.literal("user_authentication_oidc_profile_info"),
  oidc_profile_id: z.string().uuid(),
  subject: z.string().optional(),
  issuer: z.string().url().optional(),
})

export const zUserAuthenticationOidcProfileInfoResponse =
  zUserAuthenticationOidcProfileInfo.and(
    z.object({
      id: zUuid.optional(),
      meta: zMetaTimestamps.optional(),
      links: z
        .object({
          self: z.string().url().optional(),
        })
        .optional(),
    }),
  )

export const zUserAuthenticationPasswordProfileInfoUpdateInput = z.object({
  id: z.string().uuid(),
  type: z.literal("user_authentication_password_profile_info"),
  username: z.string().optional(),
  password: z.string().optional(),
})

export const zUserAuthenticationInfoUpdateInput = z.object({
  type: z.literal("user_authentication_info"),
  name: z.string().optional(),
  given_name: z.string().nullish(),
  family_name: z.string().nullish(),
  middle_name: z.string().nullish(),
  email: z.string().email().optional(),
})

export const zAuthenticationRealmUpdateInput = z.object({
  id: z.string().uuid().optional(),
  type: z.literal("authentication-realm"),
  name: z.string().optional(),
  duplicate_email_policy: z.enum(["allowed", "api_only"]).optional(),
  redirect_uris: z.array(z.string().url()).optional(),
  relationships: z
    .object({
      origin: z
        .object({
          data: z
            .object({
              id: z.string().optional(),
              type: z
                .enum([
                  "customer-authentication-settings",
                  "merchant-realm-mappings",
                  "account_authentication_settings",
                ])
                .optional(),
            })
            .optional(),
        })
        .optional(),
    })
    .optional(),
})

export const zOidcProfileCreateInput = z.object({
  type: z.literal("oidc-profile"),
  name: z.string(),
  discovery_url: z.string().url(),
  client_id: z.string(),
  client_secret: z.string(),
})

export const zOidcProfileUpdateInput = z.object({
  id: z.string().uuid().optional(),
  type: z.literal("oidc-profile"),
  name: z.string().optional(),
  discovery_url: z.string().url().optional(),
  client_id: z.string().optional(),
  client_secret: z.string().optional(),
})

export const zPasswordProfileUpdateInput = z.object({
  id: z.string().uuid().optional(),
  type: z.literal("password_profile"),
  name: z.string().optional(),
  username_format: z.enum(["email", "any"]).optional(),
  enable_one_time_password_token: z.boolean().optional(),
})

export const zUserAuthenticationOidcProfileInfoCreateInput = z.object({
  type: z.literal("user_authentication_oidc_profile_info"),
  oidc_profile_id: z.string().uuid(),
  subject: z.string(),
  issuer: z.string().url(),
})

export const zUserAuthenticationOidcProfileInfoUpdateInput = z.object({
  type: z.literal("user_authentication_oidc_profile_info"),
  subject: z.string().optional(),
  issuer: z.string().url().optional(),
})

/**
 * The number of records per page.
 */
export const zPageLimit = z.coerce
  .bigint()
  .gte(BigInt(1))
  .lte(BigInt(100))
  .default(BigInt(25))

/**
 * The number of records to offset the results by.
 */
export const zPageOffset = z.coerce
  .bigint()
  .gte(BigInt(0))
  .max(BigInt("9223372036854775807"), {
    message: "Invalid value: Expected int64 to be <= 9223372036854775807",
  })
  .default(BigInt(0))

/**
 * Specifies the filter attributes.
 */
export const zFilter = z.string()

export const zGetOidcIdpLoginStoresStoreIdAuthenticationRealmsRealmIdPath =
  z.object({
    storeId: z.string().uuid(),
    realmId: z.string().uuid(),
  })

export const zGetOidcIdpLoginStoresStoreIdAuthenticationRealmsRealmIdQuery =
  z.object({
    client_id: z.string(),
    redirect_uri: z.string().url(),
    response_type: z.literal("code"),
    scope: z.string(),
    state: z.string().max(2048),
    code_challenge_method: z.enum(["S256", "plain"]),
    code_challenge: z.string(),
    prompt: z.string().optional(),
    display: z.string().optional(),
    ui_locales: z.string().optional(),
    elasticpath_commerce_cloud_profile_id: z.string().uuid(),
    ep_report_callback_replay_error: z.boolean().optional(),
  })

export const zGetOidcIdpStoresStoreIdAuthenticationRealmsRealmIdWellKnownOpenidConfigurationPath =
  z.object({
    storeId: z.string().uuid(),
    realmId: z.string().uuid(),
  })

export const zGetOidcIdpStoresStoreIdAuthenticationRealmsRealmIdWellKnownOpenidConfigurationQuery =
  z.object({
    elasticpath_commerce_cloud_profile_id: z.string().uuid().optional(),
  })

/**
 * OK - OpenID Connect discovery document
 */
export const zGetOidcIdpStoresStoreIdAuthenticationRealmsRealmIdWellKnownOpenidConfigurationResponse =
  z.object({
    issuer: z.string().url(),
    authorization_endpoint: z.string().url(),
    token_endpoint: z.string().url(),
    jwks_uri: z.string().url(),
    response_types_supported: z.array(z.string()),
    subject_types_supported: z.array(z.string()),
    id_token_signing_alg_values_supported: z.array(z.string()),
    scopes_supported: z.array(z.string()).optional(),
    token_endpoint_auth_methods_supported: z.string().optional(),
  })

export const zGetV2AuthenticationRealmsQuery = z.object({
  "page[limit]": z.coerce
    .bigint()
    .gte(BigInt(1))
    .lte(BigInt(100))
    .optional()
    .default(BigInt(25)),
  "page[offset]": z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt("9223372036854775807"), {
      message: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional()
    .default(BigInt(0)),
})

/**
 * OK
 */
export const zGetV2AuthenticationRealmsResponse = z.object({
  data: z.array(zAuthenticationRealmResponse).optional(),
  meta: zMetaList.optional(),
  links: z
    .object({
      current: z.string().url().optional(),
      first: z.string().url().optional(),
      last: z.string().url().nullish(),
      next: z.string().url().nullish(),
      prev: z.string().url().nullish(),
    })
    .optional(),
})

export const zGetV2AuthenticationRealmsRealmIdPath = z.object({
  realmId: z.string().uuid(),
})

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdResponse = z.object({
  data: zAuthenticationRealmResponse.optional(),
  links: zSelfLink.optional(),
})

export const zPutV2AuthenticationRealmsRealmIdBody = z.object({
  data: zAuthenticationRealmUpdateInput,
})

export const zPutV2AuthenticationRealmsRealmIdPath = z.object({
  realmId: z.string().uuid(),
})

/**
 * OK
 */
export const zPutV2AuthenticationRealmsRealmIdResponse = z.object({
  data: zAuthenticationRealmResponse.optional(),
  links: zSelfLink.optional(),
})

export const zGetV2AuthenticationRealmsRealmIdOidcProfilesPath = z.object({
  realmId: z.string().uuid(),
})

export const zGetV2AuthenticationRealmsRealmIdOidcProfilesQuery = z.object({
  "page[limit]": z.coerce
    .bigint()
    .gte(BigInt(1))
    .lte(BigInt(100))
    .optional()
    .default(BigInt(25)),
  "page[offset]": z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt("9223372036854775807"), {
      message: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional()
    .default(BigInt(0)),
})

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdOidcProfilesResponse = z.object({
  data: z.array(zOidcProfileResponse).optional(),
  links: zPaginationLinks.optional(),
  meta: zPaginationMeta.optional(),
})

export const zPostV2AuthenticationRealmsRealmIdOidcProfilesBody = z.object({
  data: zOidcProfileCreateInput,
})

export const zPostV2AuthenticationRealmsRealmIdOidcProfilesPath = z.object({
  realmId: z.string().uuid(),
})

/**
 * Created
 */
export const zPostV2AuthenticationRealmsRealmIdOidcProfilesResponse = z.object({
  data: zOidcProfileResponse.optional(),
  links: zOidcProfileLinks.optional(),
})

export const zDeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdPath =
  z.object({
    realmId: z.string().uuid(),
    profileId: z.string().uuid(),
  })

/**
 * No Content
 */
export const zDeleteV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponse =
  z.void()

export const zGetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdPath =
  z.object({
    realmId: z.string().uuid(),
    profileId: z.string().uuid(),
  })

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponse =
  z.object({
    data: zOidcProfileResponse.optional(),
    links: zOidcProfileLinks.optional(),
  })

export const zPutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdBody =
  z.object({
    data: zOidcProfileUpdateInput,
  })

export const zPutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdPath =
  z.object({
    realmId: z.string().uuid(),
    profileId: z.string().uuid(),
  })

/**
 * OK
 */
export const zPutV2AuthenticationRealmsRealmIdOidcProfilesProfileIdResponse =
  z.object({
    data: zOidcProfileResponse.optional(),
    links: zOidcProfileLinks.optional(),
  })

export const zGetV2AuthenticationRealmsRealmIdPasswordProfilesPath = z.object({
  realmId: z.string().uuid(),
})

export const zGetV2AuthenticationRealmsRealmIdPasswordProfilesQuery = z.object({
  "page[limit]": z.coerce
    .bigint()
    .gte(BigInt(1))
    .lte(BigInt(100))
    .optional()
    .default(BigInt(25)),
  "page[offset]": z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt("9223372036854775807"), {
      message: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional()
    .default(BigInt(0)),
})

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdPasswordProfilesResponse =
  z.object({
    data: z.array(zPasswordProfileResponse).optional(),
    links: zPaginationLinks.optional(),
    meta: zPaginationMeta.optional(),
  })

export const zPostV2AuthenticationRealmsRealmIdPasswordProfilesBody = z.object({
  data: zPasswordProfile,
})

export const zPostV2AuthenticationRealmsRealmIdPasswordProfilesPath = z.object({
  realmId: z.string().uuid(),
})

/**
 * Created
 */
export const zPostV2AuthenticationRealmsRealmIdPasswordProfilesResponse =
  z.object({
    data: zPasswordProfileResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zDeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdPath =
  z.object({
    realmId: z.string().uuid(),
    profileId: z.string().uuid(),
  })

/**
 * No Content
 */
export const zDeleteV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponse =
  z.void()

export const zGetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdPath =
  z.object({
    realmId: z.string().uuid(),
    profileId: z.string().uuid(),
  })

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponse =
  z.object({
    data: zPasswordProfileResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zPutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdBody =
  z.object({
    data: zPasswordProfileUpdateInput,
  })

export const zPutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdPath =
  z.object({
    realmId: z.string().uuid(),
    profileId: z.string().uuid(),
  })

/**
 * OK
 */
export const zPutV2AuthenticationRealmsRealmIdPasswordProfilesProfileIdResponse =
  z.object({
    data: zPasswordProfileResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zCreateOneTimePasswordTokenRequestBody = z.object({
  data: zOneTimePasswordTokenRequestInput,
})

export const zCreateOneTimePasswordTokenRequestPath = z.object({
  realmId: z.string().uuid(),
  profileId: z.string().uuid(),
})

export const zCreateOneTimePasswordTokenRequestResponse = z.union([
  z.object({
    data: zOneTimePasswordTokenRequestResponse.optional(),
  }),
  z.unknown(),
])

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoPath =
  z.object({
    realmId: z.string().uuid(),
  })

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoQuery =
  z.object({
    "page[limit]": z.coerce
      .bigint()
      .gte(BigInt(1))
      .lte(BigInt(100))
      .optional()
      .default(BigInt(25)),
    "page[offset]": z.coerce
      .bigint()
      .gte(BigInt(0))
      .max(BigInt("9223372036854775807"), {
        message: "Invalid value: Expected int64 to be <= 9223372036854775807",
      })
      .optional()
      .default(BigInt(0)),
    filter: z.string().optional(),
    sort: z
      .enum([
        "created_at",
        "-created_at",
        "id",
        "-id",
        "updated_at",
        "-updated_at",
      ])
      .optional(),
  })

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponse =
  z.object({
    data: z.array(zUserAuthenticationInfoResponse).optional(),
    meta: zMetaList.optional(),
    links: z
      .object({
        current: z.string().url().optional(),
        first: z.string().url().optional(),
        last: z.string().url().nullish(),
        next: z.string().url().nullish(),
        prev: z.string().url().nullish(),
      })
      .optional(),
  })

export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoBody =
  z.object({
    data: zUserAuthenticationInfo,
  })

export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoPath =
  z.object({
    realmId: z.string().uuid(),
  })

/**
 * Created
 */
export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoResponse =
  z.object({
    data: zUserAuthenticationInfoResponse.optional(),
    links: z
      .object({
        self: z.string().url().optional(),
      })
      .optional(),
  })

export const zDeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
  })

/**
 * No Content
 */
export const zDeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponse =
  z.void()

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
  })

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponse =
  z.object({
    data: zUserAuthenticationInfoResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zPutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdBody =
  z.object({
    data: zUserAuthenticationInfoUpdateInput,
  })

export const zPutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
  })

/**
 * OK
 */
export const zPutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdResponse =
  z.object({
    data: zUserAuthenticationInfoResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
  })

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoQuery =
  z.object({
    "page[limit]": z.coerce
      .bigint()
      .gte(BigInt(1))
      .lte(BigInt(100))
      .optional()
      .default(BigInt(25)),
    "page[offset]": z.coerce
      .bigint()
      .gte(BigInt(0))
      .max(BigInt("9223372036854775807"), {
        message: "Invalid value: Expected int64 to be <= 9223372036854775807",
      })
      .optional()
      .default(BigInt(0)),
  })

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponse =
  z.object({
    data: z.array(zUserAuthenticationPasswordProfileInfoResponse).optional(),
    links: zPaginationLinks.optional(),
    meta: zPaginationMeta.optional(),
  })

export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoBody =
  z.object({
    data: zUserAuthenticationPasswordProfileInfoInput,
  })

export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
  })

/**
 * Created
 */
export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoResponse =
  z.object({
    data: zUserAuthenticationPasswordProfileInfoResponse.optional(),
    links: z
      .object({
        self: z.string().url().optional(),
      })
      .optional(),
  })

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
  })

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoQuery =
  z.object({
    "page[limit]": z.coerce
      .bigint()
      .gte(BigInt(1))
      .lte(BigInt(100))
      .optional()
      .default(BigInt(25)),
    "page[offset]": z.coerce
      .bigint()
      .gte(BigInt(0))
      .max(BigInt("9223372036854775807"), {
        message: "Invalid value: Expected int64 to be <= 9223372036854775807",
      })
      .optional()
      .default(BigInt(0)),
  })

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponse =
  z.object({
    data: z.array(zUserAuthenticationOidcProfileInfoResponse).optional(),
    links: zPaginationLinks.optional(),
    meta: zPaginationMeta.optional(),
  })

export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoBody =
  z.object({
    data: zUserAuthenticationOidcProfileInfoCreateInput,
  })

export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
  })

/**
 * Created
 */
export const zPostV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoResponse =
  z.object({
    data: zUserAuthenticationOidcProfileInfoResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zDeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
    oidcInfoId: z.string().uuid(),
  })

/**
 * No Content
 */
export const zDeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponse =
  z.void()

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
    oidcInfoId: z.string().uuid(),
  })

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponse =
  z.object({
    data: zUserAuthenticationOidcProfileInfoResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zPutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdBody =
  z.object({
    data: zUserAuthenticationOidcProfileInfoUpdateInput,
  })

export const zPutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
    oidcInfoId: z.string().uuid(),
  })

/**
 * OK
 */
export const zPutV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationOidcProfileInfoOidcInfoIdResponse =
  z.object({
    data: zUserAuthenticationOidcProfileInfoResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zDeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
    passwordProfileInfoId: z.string().uuid(),
  })

/**
 * No Content
 */
export const zDeleteV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponse =
  z.void()

export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdPath =
  z.object({
    realmId: z.string().uuid(),
    userAuthInfoId: z.string().uuid(),
    passwordProfileInfoId: z.string().uuid(),
  })

/**
 * OK
 */
export const zGetV2AuthenticationRealmsRealmIdUserAuthenticationInfoUserAuthInfoIdUserAuthenticationPasswordProfileInfoPasswordProfileInfoIdResponse =
  z.object({
    data: zUserAuthenticationPasswordProfileInfoResponse.optional(),
    links: zSelfLink.optional(),
  })

export const zUpdatePasswordProfileInfoBody = z.object({
  data: zUserAuthenticationPasswordProfileInfoUpdateInput,
})

export const zUpdatePasswordProfileInfoPath = z.object({
  realmId: z.string().uuid(),
  userAuthInfoId: z.string().uuid(),
  passwordProfileInfoId: z.string().uuid(),
})

/**
 * OK
 */
export const zUpdatePasswordProfileInfoResponse = z.object({
  data: zUserAuthenticationPasswordProfileInfoResponse.optional(),
  links: zSelfLink.optional(),
})
