// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  CreateImportData,
  CreateImportErrors,
  CreateImportResponses,
  CreateLocationData,
  CreateLocationErrors,
  CreateLocationResponses,
  CreateStockData,
  CreateStockErrors,
  CreateStockResponses,
  CreateTransactionData,
  CreateTransactionErrors,
  CreateTransactionResponses,
  DeleteLocationData,
  DeleteLocationResponses,
  DeleteStockData,
  DeleteStockErrors,
  DeleteStockResponses,
  GetImportData,
  GetImportErrors,
  GetImportErrorsData,
  GetImportErrorsErrors,
  GetImportErrorsResponses,
  GetImportResponses,
  GetLocationData,
  GetLocationErrors,
  GetLocationResponses,
  GetStockData,
  GetStockErrors,
  GetStockForProductsData,
  GetStockForProductsErrors,
  GetStockForProductsResponses,
  GetStockResponses,
  GetTransactionData,
  GetTransactionErrors,
  GetTransactionResponses,
  ListImportJobsData,
  ListImportJobsErrors,
  ListImportJobsResponses,
  ListLocationsData,
  ListLocationsErrors,
  ListLocationsResponses,
  ListStockData,
  ListStockErrors,
  ListStockResponses,
  ListTransactionsData,
  ListTransactionsErrors,
  ListTransactionsResponses,
  UpdateLocationData,
  UpdateLocationErrors,
  UpdateLocationResponses,
  UpdateStockData,
  UpdateStockErrors,
  UpdateStockResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Get Stock for all Products
 *
 * Returns all products and their associated stock.
 */
export const listStock = <ThrowOnError extends boolean = false>(
  options?: Options<ListStockData, ThrowOnError>,
): RequestResult<ListStockResponses, ListStockErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListStockResponses,
    ListStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories",
    ...options,
  })

/**
 * Create Stock for Product
 *
 * Sets the inventory quantity for the specified product.
 */
export const createStock = <ThrowOnError extends boolean = false>(
  options?: Options<CreateStockData, ThrowOnError>,
): RequestResult<CreateStockResponses, CreateStockErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CreateStockResponses,
    CreateStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * List Stock
 *
 * Returns stock for all products matching the supplied unique identifiers.
 */
export const getStockForProducts = <ThrowOnError extends boolean = false>(
  options?: Options<GetStockForProductsData, ThrowOnError>,
): RequestResult<
  GetStockForProductsResponses,
  GetStockForProductsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    GetStockForProductsResponses,
    GetStockForProductsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/multiple",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete Stock for Product
 *
 * Deletes the inventory for the specified product. The product inventory is null and is no longer managed by Commerce. If you want to keep managing inventory but have none of the product in stock, set the inventory to `0` instead of deleting the inventory.
 */
export const deleteStock = <ThrowOnError extends boolean = false>(
  options: Options<DeleteStockData, ThrowOnError>,
): RequestResult<DeleteStockResponses, DeleteStockErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteStockResponses,
    DeleteStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/{product_uuid}",
    ...options,
  })

/**
 * Get Stock for Product
 *
 * Gets the stock for the product matching the specified unique identifier.
 */
export const getStock = <ThrowOnError extends boolean = false>(
  options: Options<GetStockData, ThrowOnError>,
): RequestResult<GetStockResponses, GetStockErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetStockResponses,
    GetStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/{product_uuid}",
    ...options,
  })

/**
 * Update Stock for Product
 *
 * Updates the inventory for the specified product.
 */
export const updateStock = <ThrowOnError extends boolean = false>(
  options: Options<UpdateStockData, ThrowOnError>,
): RequestResult<UpdateStockResponses, UpdateStockErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateStockResponses,
    UpdateStockErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/{product_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get Stock Transactions for Product
 *
 * Returns the transactions recorded for the specified product.
 */
export const listTransactions = <ThrowOnError extends boolean = false>(
  options: Options<ListTransactionsData, ThrowOnError>,
): RequestResult<
  ListTransactionsResponses,
  ListTransactionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListTransactionsResponses,
    ListTransactionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/{product_uuid}/transactions",
    ...options,
  })

/**
 * Create Stock Transaction on Product
 */
export const createTransaction = <ThrowOnError extends boolean = false>(
  options: Options<CreateTransactionData, ThrowOnError>,
): RequestResult<
  CreateTransactionResponses,
  CreateTransactionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTransactionResponses,
    CreateTransactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/{product_uuid}/transactions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get Single Stock Transaction for Product
 *
 * Returns the specific transaction with transaction_uuid for product_uuid
 */
export const getTransaction = <ThrowOnError extends boolean = false>(
  options: Options<GetTransactionData, ThrowOnError>,
): RequestResult<GetTransactionResponses, GetTransactionErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetTransactionResponses,
    GetTransactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/{product_uuid}/transactions/{transaction_uuid}",
    ...options,
  })

/**
 * List Locations
 *
 * Lists all Inventory Locations
 */
export const listLocations = <ThrowOnError extends boolean = false>(
  options?: Options<ListLocationsData, ThrowOnError>,
): RequestResult<ListLocationsResponses, ListLocationsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListLocationsResponses,
    ListLocationsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/locations",
    ...options,
  })

/**
 * Create a Location
 *
 * Creates an Inventory Location
 */
export const createLocation = <ThrowOnError extends boolean = false>(
  options?: Options<CreateLocationData, ThrowOnError>,
): RequestResult<CreateLocationResponses, CreateLocationErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CreateLocationResponses,
    CreateLocationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/locations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete a Location
 *
 * Delete an Inventory Location
 */
export const deleteLocation = <ThrowOnError extends boolean = false>(
  options: Options<DeleteLocationData, ThrowOnError>,
): RequestResult<DeleteLocationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteLocationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/locations/{location_uuid}",
    ...options,
  })

/**
 * Get a Location
 *
 * Get an Inventory Location
 */
export const getLocation = <ThrowOnError extends boolean = false>(
  options: Options<GetLocationData, ThrowOnError>,
): RequestResult<GetLocationResponses, GetLocationErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetLocationResponses,
    GetLocationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/locations/{location_uuid}",
    ...options,
  })

/**
 * Update a Location
 *
 * Updates an Inventory Location
 */
export const updateLocation = <ThrowOnError extends boolean = false>(
  options: Options<UpdateLocationData, ThrowOnError>,
): RequestResult<UpdateLocationResponses, UpdateLocationErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateLocationResponses,
    UpdateLocationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/locations/{location_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List import jobs
 *
 * Retrieves a list of all import jobs.
 *
 */
export const listImportJobs = <ThrowOnError extends boolean = false>(
  options?: Options<ListImportJobsData, ThrowOnError>,
): RequestResult<ListImportJobsResponses, ListImportJobsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListImportJobsResponses,
    ListImportJobsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/imports",
    ...options,
  })

/**
 * Import a dataset
 */
export const createImport = <ThrowOnError extends boolean = false>(
  options?: Options<CreateImportData, ThrowOnError>,
): RequestResult<CreateImportResponses, CreateImportErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CreateImportResponses,
    CreateImportErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/imports",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  })

/**
 * Get import
 *
 * Retrieves the import job for the specified ID.
 */
export const getImport = <ThrowOnError extends boolean = false>(
  options: Options<GetImportData, ThrowOnError>,
): RequestResult<GetImportResponses, GetImportErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetImportResponses,
    GetImportErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/imports/{import_uuid}",
    ...options,
  })

/**
 * Get import errors
 *
 * Retrieves all errors encountered as part of the import. Each error is attributed to a line in the JSONL file
 * imported, so for example, if at line 1 in your JSONL you had a stock without locations, there would
 * be a missing key error for locations.
 *
 * Errors are also ordered by line number ascending, and can be paginated.
 *
 */
export const getImportErrors = <ThrowOnError extends boolean = false>(
  options: Options<GetImportErrorsData, ThrowOnError>,
): RequestResult<
  GetImportErrorsResponses,
  GetImportErrorsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetImportErrorsResponses,
    GetImportErrorsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/inventories/imports/{import_uuid}/errors",
    ...options,
  })
