// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  AddOfferingPlanPricingOptionsData,
  AddOfferingPlanPricingOptionsErrors,
  AddOfferingPlanPricingOptionsResponses,
  AttachOfferingFeatureData,
  AttachOfferingFeatureErrors,
  AttachOfferingFeatureResponses,
  BuildOfferingData,
  BuildOfferingErrors,
  BuildOfferingResponses,
  CreateDunningRuleData,
  CreateDunningRuleErrors,
  CreateDunningRuleResponses,
  CreateFeatureData,
  CreateFeatureErrors,
  CreateFeatureResponses,
  CreateImportData,
  CreateImportErrors,
  CreateImportResponses,
  CreateInvoicePaymentRefundData,
  CreateInvoicePaymentRefundErrors,
  CreateInvoicePaymentRefundResponses,
  CreateJobData,
  CreateJobErrors,
  CreateJobResponses,
  CreateOfferingData,
  CreateOfferingErrors,
  CreateOfferingFeatureData,
  CreateOfferingFeatureErrors,
  CreateOfferingFeatureResponses,
  CreateOfferingPlanData,
  CreateOfferingPlanErrors,
  CreateOfferingPlanResponses,
  CreateOfferingPricingOptionData,
  CreateOfferingPricingOptionErrors,
  CreateOfferingPricingOptionResponses,
  CreateOfferingResponses,
  CreateProrationPolicyData,
  CreateProrationPolicyErrors,
  CreateProrationPolicyResponses,
  CreateScheduleData,
  CreateScheduleErrors,
  CreateScheduleResponses,
  CreateSubscriberData,
  CreateSubscriberErrors,
  CreateSubscriberResponses,
  CreateSubscriptionData,
  CreateSubscriptionErrors,
  CreateSubscriptionProrationPreviewData,
  CreateSubscriptionProrationPreviewErrors,
  CreateSubscriptionProrationPreviewResponses,
  CreateSubscriptionResponses,
  CreateSubscriptionStateData,
  CreateSubscriptionStateErrors,
  CreateSubscriptionStateResponses,
  DeleteDunningRuleData,
  DeleteDunningRuleErrors,
  DeleteDunningRuleResponses,
  DeleteFeatureData,
  DeleteFeatureErrors,
  DeleteFeatureResponses,
  DeleteJobData,
  DeleteJobErrors,
  DeleteJobResponses,
  DeleteOfferingData,
  DeleteOfferingErrors,
  DeleteOfferingFeatureData,
  DeleteOfferingFeatureErrors,
  DeleteOfferingFeatureResponses,
  DeleteOfferingPlanData,
  DeleteOfferingPlanErrors,
  DeleteOfferingPlanResponses,
  DeleteOfferingPricingOptionData,
  DeleteOfferingPricingOptionErrors,
  DeleteOfferingPricingOptionResponses,
  DeleteOfferingResponses,
  DeleteProrationPolicyData,
  DeleteProrationPolicyErrors,
  DeleteProrationPolicyResponses,
  DeleteScheduleData,
  DeleteScheduleErrors,
  DeleteScheduleResponses,
  DeleteSubscriberData,
  DeleteSubscriberErrors,
  DeleteSubscriberResponses,
  DeleteSubscriptionData,
  DeleteSubscriptionErrors,
  DeleteSubscriptionResponses,
  GetDunningRuleData,
  GetDunningRuleErrors,
  GetDunningRuleResponses,
  GetFeatureData,
  GetFeatureErrors,
  GetFeatureResponses,
  GetImportData,
  GetImportErrors,
  GetImportErrorsData,
  GetImportErrorsErrors,
  GetImportErrorsResponses,
  GetImportResponses,
  GetInvoiceData,
  GetInvoiceErrors,
  GetInvoicePaymentData,
  GetInvoicePaymentErrors,
  GetInvoicePaymentRefundData,
  GetInvoicePaymentRefundErrors,
  GetInvoicePaymentRefundResponses,
  GetInvoicePaymentResponses,
  GetInvoiceResponses,
  GetJobData,
  GetJobErrors,
  GetJobResponses,
  GetOfferingData,
  GetOfferingErrors,
  GetOfferingFeatureData,
  GetOfferingFeatureErrors,
  GetOfferingFeatureResponses,
  GetOfferingPlanData,
  GetOfferingPlanErrors,
  GetOfferingPlanResponses,
  GetOfferingPricingOptionData,
  GetOfferingPricingOptionErrors,
  GetOfferingPricingOptionResponses,
  GetOfferingResponses,
  GetProrationPolicyData,
  GetProrationPolicyErrors,
  GetProrationPolicyResponses,
  GetScheduleData,
  GetScheduleErrors,
  GetScheduleResponses,
  GetSubscriberData,
  GetSubscriberErrors,
  GetSubscriberResponses,
  GetSubscriptionData,
  GetSubscriptionErrors,
  GetSubscriptionFeatureData,
  GetSubscriptionFeatureErrors,
  GetSubscriptionFeatureResponses,
  GetSubscriptionInvoiceData,
  GetSubscriptionInvoiceErrors,
  GetSubscriptionInvoicePaymentData,
  GetSubscriptionInvoicePaymentErrors,
  GetSubscriptionInvoicePaymentResponses,
  GetSubscriptionInvoiceResponses,
  GetSubscriptionPlanData,
  GetSubscriptionPlanErrors,
  GetSubscriptionPlanResponses,
  GetSubscriptionPricingOptionData,
  GetSubscriptionPricingOptionErrors,
  GetSubscriptionPricingOptionResponses,
  GetSubscriptionResponses,
  GetSubscriptionStateData,
  GetSubscriptionStateErrors,
  GetSubscriptionStateResponses,
  ListDunningRulesData,
  ListDunningRulesErrors,
  ListDunningRulesResponses,
  ListFeaturesData,
  ListFeaturesErrors,
  ListFeaturesResponses,
  ListImportJobsData,
  ListImportJobsErrors,
  ListImportJobsResponses,
  ListInvoicePaymentRefundsData,
  ListInvoicePaymentRefundsErrors,
  ListInvoicePaymentRefundsResponses,
  ListInvoicePaymentsData,
  ListInvoicePaymentsResponses,
  ListInvoicesData,
  ListInvoicesErrors,
  ListInvoicesResponses,
  ListJobsData,
  ListJobsErrors,
  ListJobsResponses,
  ListOfferingFeaturesData,
  ListOfferingFeaturesErrors,
  ListOfferingFeaturesResponses,
  ListOfferingPlanPricingOptionsData,
  ListOfferingPlanPricingOptionsErrors,
  ListOfferingPlanPricingOptionsResponses,
  ListOfferingPlansData,
  ListOfferingPlansErrors,
  ListOfferingPlansResponses,
  ListOfferingPricingOptionsData,
  ListOfferingPricingOptionsErrors,
  ListOfferingPricingOptionsResponses,
  ListOfferingsData,
  ListOfferingsErrors,
  ListOfferingsResponses,
  ListProrationPoliciesData,
  ListProrationPoliciesErrors,
  ListProrationPoliciesResponses,
  ListSchedulesData,
  ListSchedulesErrors,
  ListSchedulesResponses,
  ListSubscribersData,
  ListSubscribersErrors,
  ListSubscribersResponses,
  ListSubscriptionFeaturesData,
  ListSubscriptionFeaturesErrors,
  ListSubscriptionFeaturesResponses,
  ListSubscriptionInvoicePaymentsData,
  ListSubscriptionInvoicePaymentsResponses,
  ListSubscriptionInvoicesData,
  ListSubscriptionInvoicesErrors,
  ListSubscriptionInvoicesResponses,
  ListSubscriptionPlansData,
  ListSubscriptionPlansErrors,
  ListSubscriptionPlansResponses,
  ListSubscriptionPricingOptionsData,
  ListSubscriptionPricingOptionsErrors,
  ListSubscriptionPricingOptionsResponses,
  ListSubscriptionsData,
  ListSubscriptionsErrors,
  ListSubscriptionsResponses,
  ListSubscriptionStatesData,
  ListSubscriptionStatesErrors,
  ListSubscriptionStatesResponses,
  ManageSubscriptionPlansData,
  ManageSubscriptionPlansErrors,
  ManageSubscriptionPlansResponses,
  RemoveOfferingPlanPricingOptionsData,
  RemoveOfferingPlanPricingOptionsErrors,
  RemoveOfferingPlanPricingOptionsResponses,
  UpdateDunningRuleData,
  UpdateDunningRuleErrors,
  UpdateDunningRuleResponses,
  UpdateFeatureData,
  UpdateFeatureErrors,
  UpdateFeatureResponses,
  UpdateInvoicePaymentData,
  UpdateInvoicePaymentErrors,
  UpdateInvoicePaymentResponses,
  UpdateOfferingData,
  UpdateOfferingErrors,
  UpdateOfferingFeatureData,
  UpdateOfferingFeatureErrors,
  UpdateOfferingFeatureResponses,
  UpdateOfferingPlanData,
  UpdateOfferingPlanErrors,
  UpdateOfferingPlanResponses,
  UpdateOfferingPricingOptionData,
  UpdateOfferingPricingOptionErrors,
  UpdateOfferingPricingOptionResponses,
  UpdateOfferingResponses,
  UpdateProrationPolicyData,
  UpdateProrationPolicyErrors,
  UpdateProrationPolicyResponses,
  UpdateScheduleData,
  UpdateScheduleErrors,
  UpdateScheduleResponses,
  UpdateSubscriberData,
  UpdateSubscriberErrors,
  UpdateSubscriberResponses,
  UpdateSubscriptionData,
  UpdateSubscriptionErrors,
  UpdateSubscriptionResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * List offerings
 *
 * Retrieves a list of all subscription offerings.
 *
 * ### Filtering
 *
 * This endpoint supports filtering. For the general syntax, see [**Filtering**](/guides/Getting-Started/filtering).
 *
 * The following attributes and operators are supported.
 *
 * | Operator | Attribute | Description |
 * | --- | --- | --- |
 * | `eq` | `external_ref`, `plans.external_ref`, `proration_policy_id` | Equals. Checks if the values of two operands are equal. If they are, the condition is true. |
 * | `in` | `external_ref`, `plans.external_ref`, `proration_policy_id` | In. Checks if the value is in the specified list. If it is, the condition is true. |
 *
 */
export const listOfferings = <ThrowOnError extends boolean = false>(
  options?: Options<ListOfferingsData, ThrowOnError>,
): RequestResult<ListOfferingsResponses, ListOfferingsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListOfferingsResponses,
    ListOfferingsErrors,
    ThrowOnError
  >({
    querySerializer: { parameters: { include: { array: { explode: false } } } },
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings",
    ...options,
  })

/**
 * Create an offering
 */
export const createOffering = <ThrowOnError extends boolean = false>(
  options?: Options<CreateOfferingData, ThrowOnError>,
): RequestResult<CreateOfferingResponses, CreateOfferingErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CreateOfferingResponses,
    CreateOfferingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Build an offering
 *
 * An offering includes plans and pricing options; plans are combined with one or more pricing options to form an offering. An offering can include either:
 *
 * - subscription plans (created within an offering).
 * - Product Experience Manager products. See [**create a product**](/docs/api/pxm/products/create-product).
 *
 * When you are building an offering:
 *
 * - you can create new pricing options and plans.
 * - you can modify an existing plan and pricing options. For example, you can modify the plan price or any attributes of a pricing option included in the offering.
 *
 * Here's how you build an offering:
 *
 * 1. Specify the plan to build with the offering. A plan can be:
 *
 * - subscription plans. Specify the subscription plan attributes.
 * - Product Experience Manager products. Specify the Product Experience Manager product ID in `external_ref` in `PlanAttributes`. For the remaining plan attributes, you can specify their values to match the values of the existing Product Experience Manager product attributes. However, you can also specify different values, depending on your requirements.
 *
 * 2. Specify the pricing options to build with the offering. Pricing options are the rules that govern your subscription, for example, any discount. You can combine and reuse pricing options for as many plans as you want, making it quick and easy to create your subscription offerings.
 * An offering must have at least one pricing option.
 *
 */
export const buildOffering = <ThrowOnError extends boolean = false>(
  options?: Options<BuildOfferingData, ThrowOnError>,
): RequestResult<BuildOfferingResponses, BuildOfferingErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    BuildOfferingResponses,
    BuildOfferingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/build",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete offering
 *
 * When a subscription is created, it creates a snapshot of the offering. This means you can delete an offering without affecting any active subscriptions.
 */
export const deleteOffering = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOfferingData, ThrowOnError>,
): RequestResult<DeleteOfferingResponses, DeleteOfferingErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteOfferingResponses,
    DeleteOfferingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}",
    ...options,
  })

/**
 * Get offering
 */
export const getOffering = <ThrowOnError extends boolean = false>(
  options: Options<GetOfferingData, ThrowOnError>,
): RequestResult<GetOfferingResponses, GetOfferingErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetOfferingResponses,
    GetOfferingErrors,
    ThrowOnError
  >({
    querySerializer: { parameters: { include: { array: { explode: false } } } },
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}",
    ...options,
  })

/**
 * Update an offering
 *
 * After saving an offering, you can update an offering at any time. Updating an offering does not affect any active subscriptions. The changes take effect on all new subscriptions that are created. For fields that are optional, an existing value can be removed by specifying a value of null.
 *
 */
export const updateOffering = <ThrowOnError extends boolean = false>(
  options: Options<UpdateOfferingData, ThrowOnError>,
): RequestResult<UpdateOfferingResponses, UpdateOfferingErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateOfferingResponses,
    UpdateOfferingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Remove a feature from an offering
 *
 * After saving an offering, you can remove features from it at any time.
 *
 * Removing a feature from an offering does not affect any existing active subscriptions. The changes take effect on all new subscriptions that are created.
 *
 */
export const deleteOfferingFeature = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOfferingFeatureData, ThrowOnError>,
): RequestResult<
  DeleteOfferingFeatureResponses,
  DeleteOfferingFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteOfferingFeatureResponses,
    DeleteOfferingFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/features/{feature_uuid}",
    ...options,
  })

/**
 * Get a feature in an offering
 */
export const getOfferingFeature = <ThrowOnError extends boolean = false>(
  options: Options<GetOfferingFeatureData, ThrowOnError>,
): RequestResult<
  GetOfferingFeatureResponses,
  GetOfferingFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOfferingFeatureResponses,
    GetOfferingFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/features/{feature_uuid}",
    ...options,
  })

/**
 * Updates a feature in an offering
 *
 * Use the unique identifier of the feature in the offering that you want to update. Any modifications that you make to the features in an offering, does not affect any active subscriptions. The changes take effect on all new subscriptions that are created.
 */
export const updateOfferingFeature = <ThrowOnError extends boolean = false>(
  options: Options<UpdateOfferingFeatureData, ThrowOnError>,
): RequestResult<
  UpdateOfferingFeatureResponses,
  UpdateOfferingFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateOfferingFeatureResponses,
    UpdateOfferingFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/features/{feature_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Attach a feature
 *
 * After saving an offering, you can attach new features to it at any time.
 *
 * Adding new features does not affect any existing active subscriptions. The changes take effect on all new subscriptions that are created.
 *
 */
export const attachOfferingFeature = <ThrowOnError extends boolean = false>(
  options: Options<AttachOfferingFeatureData, ThrowOnError>,
): RequestResult<
  AttachOfferingFeatureResponses,
  AttachOfferingFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AttachOfferingFeatureResponses,
    AttachOfferingFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/features/attach",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List an offering's pricing options
 */
export const listOfferingPricingOptions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListOfferingPricingOptionsData, ThrowOnError>,
): RequestResult<
  ListOfferingPricingOptionsResponses,
  ListOfferingPricingOptionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListOfferingPricingOptionsResponses,
    ListOfferingPricingOptionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/pricing-options",
    ...options,
  })

/**
 * Create a pricing option inside an offering
 *
 * After saving an offering, you can add new pricing option to it at any time.
 *
 */
export const createOfferingPricingOption = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateOfferingPricingOptionData, ThrowOnError>,
): RequestResult<
  CreateOfferingPricingOptionResponses,
  CreateOfferingPricingOptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateOfferingPricingOptionResponses,
    CreateOfferingPricingOptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/pricing-options",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Remove a pricing option from an offering
 *
 * After saving an offering, you can remove pricing options from it at any time.
 *
 * Removing a pricing option from an offering does not affect any existing active subscriptions. The changes take effect on all new subscriptions that are created.
 *
 */
export const deleteOfferingPricingOption = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteOfferingPricingOptionData, ThrowOnError>,
): RequestResult<
  DeleteOfferingPricingOptionResponses,
  DeleteOfferingPricingOptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteOfferingPricingOptionResponses,
    DeleteOfferingPricingOptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/pricing-options/{pricing_option_uuid}",
    ...options,
  })

/**
 * Get a pricing option in an offering
 */
export const getOfferingPricingOption = <ThrowOnError extends boolean = false>(
  options: Options<GetOfferingPricingOptionData, ThrowOnError>,
): RequestResult<
  GetOfferingPricingOptionResponses,
  GetOfferingPricingOptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOfferingPricingOptionResponses,
    GetOfferingPricingOptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/pricing-options/{pricing_option_uuid}",
    ...options,
  })

/**
 * Update a pricing option in an offering
 */
export const updateOfferingPricingOption = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateOfferingPricingOptionData, ThrowOnError>,
): RequestResult<
  UpdateOfferingPricingOptionResponses,
  UpdateOfferingPricingOptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateOfferingPricingOptionResponses,
    UpdateOfferingPricingOptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/pricing-options/{pricing_option_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List an offering's features
 */
export const listOfferingFeatures = <ThrowOnError extends boolean = false>(
  options: Options<ListOfferingFeaturesData, ThrowOnError>,
): RequestResult<
  ListOfferingFeaturesResponses,
  ListOfferingFeaturesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListOfferingFeaturesResponses,
    ListOfferingFeaturesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/features",
    ...options,
  })

/**
 * Create a feature directly inside an offering
 *
 * After saving an offering, you can add new features to it at any time.
 *
 */
export const createOfferingFeature = <ThrowOnError extends boolean = false>(
  options: Options<CreateOfferingFeatureData, ThrowOnError>,
): RequestResult<
  CreateOfferingFeatureResponses,
  CreateOfferingFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateOfferingFeatureResponses,
    CreateOfferingFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/features",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List an offering's plans
 */
export const listOfferingPlans = <ThrowOnError extends boolean = false>(
  options: Options<ListOfferingPlansData, ThrowOnError>,
): RequestResult<
  ListOfferingPlansResponses,
  ListOfferingPlansErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListOfferingPlansResponses,
    ListOfferingPlansErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/plans",
    ...options,
  })

/**
 * Create a plan inside an offering
 *
 * After saving an offering, you can add new plans to it at any time.
 *
 */
export const createOfferingPlan = <ThrowOnError extends boolean = false>(
  options: Options<CreateOfferingPlanData, ThrowOnError>,
): RequestResult<
  CreateOfferingPlanResponses,
  CreateOfferingPlanErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateOfferingPlanResponses,
    CreateOfferingPlanErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/plans",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Remove a plan from an offering
 *
 * After saving an offering, you can remove plans from it at any time.
 *
 * Removing a plan from an offering does not affect any existing active subscriptions. The changes take effect on all new subscriptions that are created.
 *
 */
export const deleteOfferingPlan = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOfferingPlanData, ThrowOnError>,
): RequestResult<
  DeleteOfferingPlanResponses,
  DeleteOfferingPlanErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteOfferingPlanResponses,
    DeleteOfferingPlanErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/plans/{plan_uuid}",
    ...options,
  })

/**
 * Get a plan in an offering
 */
export const getOfferingPlan = <ThrowOnError extends boolean = false>(
  options: Options<GetOfferingPlanData, ThrowOnError>,
): RequestResult<
  GetOfferingPlanResponses,
  GetOfferingPlanErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOfferingPlanResponses,
    GetOfferingPlanErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/plans/{plan_uuid}",
    ...options,
  })

/**
 * Update a plan in an offering
 *
 * Use the unique identifier of the plan in the offering that you want to update. Any modifications that you make to the plans in an offering, does not affect any active subscriptions. The changes take effect on all new subscriptions that are created.
 */
export const updateOfferingPlan = <ThrowOnError extends boolean = false>(
  options: Options<UpdateOfferingPlanData, ThrowOnError>,
): RequestResult<
  UpdateOfferingPlanResponses,
  UpdateOfferingPlanErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateOfferingPlanResponses,
    UpdateOfferingPlanErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/plans/{plan_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Removes an offering's pricing options from the plan
 *
 * Use the unique identifier of the pricing in the offering that you want to update. Any modifications that you make to the plans in an offering, does not affect any active subscriptions. The changes take effect on all new subscriptions that are created.
 */
export const removeOfferingPlanPricingOptions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoveOfferingPlanPricingOptionsData, ThrowOnError>,
): RequestResult<
  RemoveOfferingPlanPricingOptionsResponses,
  RemoveOfferingPlanPricingOptionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    RemoveOfferingPlanPricingOptionsResponses,
    RemoveOfferingPlanPricingOptionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/plans/{plan_uuid}/relationships/pricing_options",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List the pricing options available to a plan in an offering
 */
export const listOfferingPlanPricingOptions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListOfferingPlanPricingOptionsData, ThrowOnError>,
): RequestResult<
  ListOfferingPlanPricingOptionsResponses,
  ListOfferingPlanPricingOptionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListOfferingPlanPricingOptionsResponses,
    ListOfferingPlanPricingOptionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/plans/{plan_uuid}/relationships/pricing_options",
    ...options,
  })

/**
 * Adds an offering's pricing options to the plan
 *
 * Use the unique identifier of the pricing in the offering that you want to update. Any modifications that you make to the plans in an offering, does not affect any active subscriptions. The changes take effect on all new subscriptions that are created.
 */
export const addOfferingPlanPricingOptions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AddOfferingPlanPricingOptionsData, ThrowOnError>,
): RequestResult<
  AddOfferingPlanPricingOptionsResponses,
  AddOfferingPlanPricingOptionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AddOfferingPlanPricingOptionsResponses,
    AddOfferingPlanPricingOptionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/offerings/{offering_uuid}/plans/{plan_uuid}/relationships/pricing_options",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List subscriptions
 *
 * Retrieves a list of all subscriptions.
 *
 * ### Filtering
 *
 * This endpoint supports filtering. For the general syntax, see [**Filtering**](/guides/Getting-Started/filtering).
 *
 * The following attributes and operators are supported.
 *
 * | Operator | Attribute | Description |
 * | --- | --- | --- |
 * | `eq` | `account_id`, `name`, `email`, `external_ref` | Equals. Checks if the values of two operands are equal. If they are, the condition is true. |
 * | `in` | `account_id`, `name`, `email`, `external_ref` | In. Checks if the value is in the specified list. If it is, the condition is true. |
 *
 * ### Including Resources
 *
 * You can use the `include` parameter to include the following resources with this endpoint.
 *
 * | Resource | Required | Description |
 * | --- | --- | --- |
 * | `pricing_options, plans` | Optional | Retrieves all pricing options and plans associated with a subscription. |
 * | `plans` | Optional | Retrieves all plans associated with a subscription. |
 * | `pricing_options` | Optional | Retrieves all pricing options associated with a subscription. |
 *
 * See [Characteristics of Include Parameter](/guides/Getting-Started/includes#characteristics-of-include-parameter).
 *
 */
export const listSubscriptions = <ThrowOnError extends boolean = false>(
  options?: Options<ListSubscriptionsData, ThrowOnError>,
): RequestResult<
  ListSubscriptionsResponses,
  ListSubscriptionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListSubscriptionsResponses,
    ListSubscriptionsErrors,
    ThrowOnError
  >({
    querySerializer: { parameters: { include: { array: { explode: false } } } },
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions",
    ...options,
  })

/**
 * Create a subscription
 */
export const createSubscription = <ThrowOnError extends boolean = false>(
  options?: Options<CreateSubscriptionData, ThrowOnError>,
): RequestResult<
  CreateSubscriptionResponses,
  CreateSubscriptionErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CreateSubscriptionResponses,
    CreateSubscriptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete a subscription
 *
 * Deletes a subscription
 *
 */
export const deleteSubscription = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSubscriptionData, ThrowOnError>,
): RequestResult<
  DeleteSubscriptionResponses,
  DeleteSubscriptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteSubscriptionResponses,
    DeleteSubscriptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}",
    ...options,
  })

/**
 * Get subscription
 */
export const getSubscription = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriptionData, ThrowOnError>,
): RequestResult<
  GetSubscriptionResponses,
  GetSubscriptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionResponses,
    GetSubscriptionErrors,
    ThrowOnError
  >({
    querySerializer: { parameters: { include: { array: { explode: false } } } },
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}",
    ...options,
  })

/**
 * Update a subscription
 *
 * Updates a subscription. For example, a subscriber can switch from one pricing option to another in a subscription.
 *
 */
export const updateSubscription = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSubscriptionData, ThrowOnError>,
): RequestResult<
  UpdateSubscriptionResponses,
  UpdateSubscriptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateSubscriptionResponses,
    UpdateSubscriptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get a feature in a subscription
 */
export const getSubscriptionFeature = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriptionFeatureData, ThrowOnError>,
): RequestResult<
  GetSubscriptionFeatureResponses,
  GetSubscriptionFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionFeatureResponses,
    GetSubscriptionFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/features/{feature_uuid}",
    ...options,
  })

/**
 * Get a plan in a subscription
 */
export const getSubscriptionPlan = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriptionPlanData, ThrowOnError>,
): RequestResult<
  GetSubscriptionPlanResponses,
  GetSubscriptionPlanErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionPlanResponses,
    GetSubscriptionPlanErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/plans/{plan_uuid}",
    ...options,
  })

/**
 * Get a pricing option in a subscription
 */
export const getSubscriptionPricingOption = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSubscriptionPricingOptionData, ThrowOnError>,
): RequestResult<
  GetSubscriptionPricingOptionResponses,
  GetSubscriptionPricingOptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionPricingOptionResponses,
    GetSubscriptionPricingOptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/pricing-options/{pricing_option_uuid}",
    ...options,
  })

/**
 * List an subscriptions features
 */
export const listSubscriptionFeatures = <ThrowOnError extends boolean = false>(
  options: Options<ListSubscriptionFeaturesData, ThrowOnError>,
): RequestResult<
  ListSubscriptionFeaturesResponses,
  ListSubscriptionFeaturesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListSubscriptionFeaturesResponses,
    ListSubscriptionFeaturesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/features",
    ...options,
  })

/**
 * List subscription plans
 *
 * Retrieves a list of plans associated with the specified subscription. Using this endpoint you can see the plan that is currently active in a subscription. If `active_plan` is `true`, a plan is active in a subscription. If `active_plan` is null, the pricing option is not active.
 */
export const listSubscriptionPlans = <ThrowOnError extends boolean = false>(
  options: Options<ListSubscriptionPlansData, ThrowOnError>,
): RequestResult<
  ListSubscriptionPlansResponses,
  ListSubscriptionPlansErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListSubscriptionPlansResponses,
    ListSubscriptionPlansErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/plans",
    ...options,
  })

/**
 * Manage subscription plans
 *
 * Manage subscription plans by replacing, changing or detaching plans on the subscription
 */
export const manageSubscriptionPlans = <ThrowOnError extends boolean = false>(
  options: Options<ManageSubscriptionPlansData, ThrowOnError>,
): RequestResult<
  ManageSubscriptionPlansResponses,
  ManageSubscriptionPlansErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ManageSubscriptionPlansResponses,
    ManageSubscriptionPlansErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/plans",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List subscription pricing options
 *
 * Retrieves a list of pricing options associated with the specified subscription. Using this endpoint you can see the pricing options that are currently active in a subscription. If `active_pricing_option` is `true`, a pricing option is active in a subscription. If `active_pricing_option` is null, the pricing option is not active.
 */
export const listSubscriptionPricingOptions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListSubscriptionPricingOptionsData, ThrowOnError>,
): RequestResult<
  ListSubscriptionPricingOptionsResponses,
  ListSubscriptionPricingOptionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListSubscriptionPricingOptionsResponses,
    ListSubscriptionPricingOptionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/pricing-options",
    ...options,
  })

/**
 * Preview a subscription proration
 *
 * Computes the proration amounts a prospective plan or pricing option change would produce, without
 * persisting anything or affecting billing. Use this to show a subscriber the cost impact of a change
 * before submitting it via a subscription update.
 *
 * A `200` response with `would_prorate: false` is not an error - it means the prospective change would
 * not result in a proration being applied if actually submitted. See `rejection_reason`.
 *
 */
export const createSubscriptionProrationPreview = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSubscriptionProrationPreviewData, ThrowOnError>,
): RequestResult<
  CreateSubscriptionProrationPreviewResponses,
  CreateSubscriptionProrationPreviewErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSubscriptionProrationPreviewResponses,
    CreateSubscriptionProrationPreviewErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/proration-preview",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List subscription states
 */
export const listSubscriptionStates = <ThrowOnError extends boolean = false>(
  options: Options<ListSubscriptionStatesData, ThrowOnError>,
): RequestResult<
  ListSubscriptionStatesResponses,
  ListSubscriptionStatesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListSubscriptionStatesResponses,
    ListSubscriptionStatesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/states",
    ...options,
  })

/**
 * Create a subscription state
 *
 * The subscription lifecycle is the states that a subscription can go through when a customer subscribes to a service or a plan.
 *
 * A subscription can have the following states:
 *
 * - `pending`
 * - `canceled`
 * - `paused`
 * - `resumed`
 * For more information, see [Managing the Subscription Lifecycle](/docs/api/subscriptions/subscriptions#managing-the-subscription-lifecycle).
 *
 * Immediate cancellation (`cancel` with `cancel_immediately: true`) ends the subscription and updates entitlements in this request; it does **not** issue refunds or modify paid invoices. Use payments refund flows separately if needed.
 *
 */
export const createSubscriptionState = <ThrowOnError extends boolean = false>(
  options: Options<CreateSubscriptionStateData, ThrowOnError>,
): RequestResult<
  CreateSubscriptionStateResponses,
  CreateSubscriptionStateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSubscriptionStateResponses,
    CreateSubscriptionStateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/states",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get subscription state
 */
export const getSubscriptionState = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriptionStateData, ThrowOnError>,
): RequestResult<
  GetSubscriptionStateResponses,
  GetSubscriptionStateErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionStateResponses,
    GetSubscriptionStateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/states/{state_uuid}",
    ...options,
  })

/**
 * List jobs
 *
 * Retrieves a list of all jobs.
 *
 * ### Filtering
 *
 * This endpoint supports filtering. For the general syntax, see [**Filtering**](/guides/Getting-Started/filtering).
 *
 * The following attributes and operators are supported.
 *
 * | Operator | Attribute | Description |
 * | --- | --- | --- |
 * | `eq` | `external_ref` | Equals. Checks if the values of two operands are equal. If they are, the condition is true. |
 * | `in` | `external_ref` | In. Checks if the value is in the specified list. If it is, the condition is true. |
 *
 */
export const listJobs = <ThrowOnError extends boolean = false>(
  options?: Options<ListJobsData, ThrowOnError>,
): RequestResult<ListJobsResponses, ListJobsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListJobsResponses,
    ListJobsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/jobs",
    ...options,
  })

/**
 * Create a job
 */
export const createJob = <ThrowOnError extends boolean = false>(
  options?: Options<CreateJobData, ThrowOnError>,
): RequestResult<CreateJobResponses, CreateJobErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CreateJobResponses,
    CreateJobErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/jobs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete job
 */
export const deleteJob = <ThrowOnError extends boolean = false>(
  options: Options<DeleteJobData, ThrowOnError>,
): RequestResult<DeleteJobResponses, DeleteJobErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteJobResponses,
    DeleteJobErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/jobs/{job_uuid}",
    ...options,
  })

/**
 * Get job
 */
export const getJob = <ThrowOnError extends boolean = false>(
  options: Options<GetJobData, ThrowOnError>,
): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> =>
  (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/jobs/{job_uuid}",
    ...options,
  })

/**
 * List import jobs
 *
 * Retrieves a list of all import jobs.
 *
 */
export const listImportJobs = <ThrowOnError extends boolean = false>(
  options?: Options<ListImportJobsData, ThrowOnError>,
): RequestResult<ListImportJobsResponses, ListImportJobsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListImportJobsResponses,
    ListImportJobsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/imports",
    ...options,
  })

/**
 * Import a dataset
 */
export const createImport = <ThrowOnError extends boolean = false>(
  options?: Options<CreateImportData, ThrowOnError>,
): RequestResult<CreateImportResponses, CreateImportErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CreateImportResponses,
    CreateImportErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/imports",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  })

/**
 * Get import
 *
 * Retrieves the import job for the specified ID.
 */
export const getImport = <ThrowOnError extends boolean = false>(
  options: Options<GetImportData, ThrowOnError>,
): RequestResult<GetImportResponses, GetImportErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetImportResponses,
    GetImportErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/imports/{import_uuid}",
    ...options,
  })

/**
 * Get import errors
 *
 * Retrieves all errors encountered as part of the import. Each error is attributed to a line in the JSONL file
 * imported, so for example, if at line 1 in your JSONL you had a subscription_offering without a name, there would
 * be a minimum string error for the `name` attribute with `"line_number": 1`.
 *
 * Errors are also ordered by line number ascending, and can be paginated.
 *
 */
export const getImportErrors = <ThrowOnError extends boolean = false>(
  options: Options<GetImportErrorsData, ThrowOnError>,
): RequestResult<
  GetImportErrorsResponses,
  GetImportErrorsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetImportErrorsResponses,
    GetImportErrorsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/imports/{import_uuid}/errors",
    ...options,
  })

/**
 * List subscription invoices
 *
 * Lists all invoices for a given subscription.
 */
export const listSubscriptionInvoices = <ThrowOnError extends boolean = false>(
  options: Options<ListSubscriptionInvoicesData, ThrowOnError>,
): RequestResult<
  ListSubscriptionInvoicesResponses,
  ListSubscriptionInvoicesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListSubscriptionInvoicesResponses,
    ListSubscriptionInvoicesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/invoices",
    ...options,
  })

/**
 * List subscription invoice payments
 *
 * Lists all invoice payments for a given invoice.
 */
export const listSubscriptionInvoicePayments = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListSubscriptionInvoicePaymentsData, ThrowOnError>,
): RequestResult<
  ListSubscriptionInvoicePaymentsResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListSubscriptionInvoicePaymentsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/invoices/{invoice_uuid}/payments",
    ...options,
  })

/**
 * Get subscription invoice payment
 *
 * Gets a specific payment for a given invoice.
 */
export const getSubscriptionInvoicePayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSubscriptionInvoicePaymentData, ThrowOnError>,
): RequestResult<
  GetSubscriptionInvoicePaymentResponses,
  GetSubscriptionInvoicePaymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionInvoicePaymentResponses,
    GetSubscriptionInvoicePaymentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/invoices/{invoice_uuid}/payments/{payment_uuid}",
    ...options,
  })

/**
 * Get subscription invoice
 *
 * Gets a specific invoice for a given subscription.
 */
export const getSubscriptionInvoice = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriptionInvoiceData, ThrowOnError>,
): RequestResult<
  GetSubscriptionInvoiceResponses,
  GetSubscriptionInvoiceErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionInvoiceResponses,
    GetSubscriptionInvoiceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscriptions/{subscription_uuid}/invoices/{invoice_uuid}",
    ...options,
  })

/**
 * List invoices
 *
 * Retrieves a list of all invoices.
 *
 * ### Filtering
 *
 * This endpoint supports filtering. For the general syntax, see [**Filtering**](/guides/Getting-Started/filtering).
 *
 * The following attributes and operators are supported.
 *
 * | Operator |Attribute | Description |
 * | --- | --- | --- |
 * | `eq` | `subscriber_id`, `subscription_id`, `outstanding`, `tax_required` | Equals. Checks if the values of two operands are equal. If they are, the condition is true. |
 * | `in` | `subscriber_id`, `subscription_id` | In. Checks if the value is in the specified list. If it is, the condition is true. |
 *
 */
export const listInvoices = <ThrowOnError extends boolean = false>(
  options?: Options<ListInvoicesData, ThrowOnError>,
): RequestResult<ListInvoicesResponses, ListInvoicesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListInvoicesResponses,
    ListInvoicesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/invoices",
    ...options,
  })

/**
 * Get invoice
 */
export const getInvoice = <ThrowOnError extends boolean = false>(
  options: Options<GetInvoiceData, ThrowOnError>,
): RequestResult<GetInvoiceResponses, GetInvoiceErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetInvoiceResponses,
    GetInvoiceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/invoices/{invoice_uuid}",
    ...options,
  })

/**
 * List invoice payments
 */
export const listInvoicePayments = <ThrowOnError extends boolean = false>(
  options: Options<ListInvoicePaymentsData, ThrowOnError>,
): RequestResult<ListInvoicePaymentsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    ListInvoicePaymentsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/invoices/{invoice_uuid}/payments",
    ...options,
  })

/**
 * Get invoice payment
 */
export const getInvoicePayment = <ThrowOnError extends boolean = false>(
  options: Options<GetInvoicePaymentData, ThrowOnError>,
): RequestResult<
  GetInvoicePaymentResponses,
  GetInvoicePaymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetInvoicePaymentResponses,
    GetInvoicePaymentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/invoices/{invoice_uuid}/payments/{payment_uuid}",
    ...options,
  })

/**
 * Update Invoice Payment
 *
 * External payment methods are payment methods not offered by Elastic Path Subscriptions (such as Elastic Path Payments powered by Stripe or Authorize.net), but they can still be integrated with Subscriptions. You can use the `Update Invoice Payment` endpoint to manually update a payment against an invoice where an external payment method is handling the payment of your invoices. See [External Payments](/docs/api/subscriptions/invoices#external-payments).
 *
 */
export const updateInvoicePayment = <ThrowOnError extends boolean = false>(
  options: Options<UpdateInvoicePaymentData, ThrowOnError>,
): RequestResult<
  UpdateInvoicePaymentResponses,
  UpdateInvoicePaymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateInvoicePaymentResponses,
    UpdateInvoicePaymentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/invoices/{invoice_uuid}/payments/{payment_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List invoice payment refunds
 *
 * List all refunds for an invoice payments
 */
export const listInvoicePaymentRefunds = <ThrowOnError extends boolean = false>(
  options: Options<ListInvoicePaymentRefundsData, ThrowOnError>,
): RequestResult<
  ListInvoicePaymentRefundsResponses,
  ListInvoicePaymentRefundsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListInvoicePaymentRefundsResponses,
    ListInvoicePaymentRefundsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/invoices/{invoice_uuid}/payments/{payment_uuid}/refunds",
    ...options,
  })

/**
 * Create a refund for an invoice payment
 *
 * Creates a refund for a paid invoice.
 */
export const createInvoicePaymentRefund = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateInvoicePaymentRefundData, ThrowOnError>,
): RequestResult<
  CreateInvoicePaymentRefundResponses,
  CreateInvoicePaymentRefundErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateInvoicePaymentRefundResponses,
    CreateInvoicePaymentRefundErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/invoices/{invoice_uuid}/payments/{payment_uuid}/refunds",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get a refund for an invoice payment
 *
 * Get a refund for a paid invoice.
 */
export const getInvoicePaymentRefund = <ThrowOnError extends boolean = false>(
  options: Options<GetInvoicePaymentRefundData, ThrowOnError>,
): RequestResult<
  GetInvoicePaymentRefundResponses,
  GetInvoicePaymentRefundErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetInvoicePaymentRefundResponses,
    GetInvoicePaymentRefundErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/invoices/{invoice_uuid}/payments/{payment_uuid}/refunds/{refund_uuid}",
    ...options,
  })

/**
 * List schedules
 *
 * Retrieves a list of all schedules.
 *
 * ### Filtering
 *
 * This endpoint supports filtering. For the general syntax, see [**Filtering**](/guides/Getting-Started/filtering).
 *
 * The following attributes and operators are supported.
 *
 * | Operator | Attribute | Description |
 * | --- | --- | --- |
 * | `eq` | `external_ref` | Equals. Checks if the values of two operands are equal. If they are, the condition is true. |
 * | `in` | `external_ref` | In. Checks if the value is in the specified list. If it is, the condition is true. |
 *
 */
export const listSchedules = <ThrowOnError extends boolean = false>(
  options?: Options<ListSchedulesData, ThrowOnError>,
): RequestResult<ListSchedulesResponses, ListSchedulesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListSchedulesResponses,
    ListSchedulesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/schedules",
    ...options,
  })

/**
 * Create a schedule
 */
export const createSchedule = <ThrowOnError extends boolean = false>(
  options?: Options<CreateScheduleData, ThrowOnError>,
): RequestResult<CreateScheduleResponses, CreateScheduleErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CreateScheduleResponses,
    CreateScheduleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/schedules",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete schedule
 */
export const deleteSchedule = <ThrowOnError extends boolean = false>(
  options: Options<DeleteScheduleData, ThrowOnError>,
): RequestResult<DeleteScheduleResponses, DeleteScheduleErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteScheduleResponses,
    DeleteScheduleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/schedules/{schedule_uuid}",
    ...options,
  })

/**
 * Get a schedule
 */
export const getSchedule = <ThrowOnError extends boolean = false>(
  options: Options<GetScheduleData, ThrowOnError>,
): RequestResult<GetScheduleResponses, GetScheduleErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetScheduleResponses,
    GetScheduleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/schedules/{schedule_uuid}",
    ...options,
  })

/**
 * Update a schedule
 */
export const updateSchedule = <ThrowOnError extends boolean = false>(
  options: Options<UpdateScheduleData, ThrowOnError>,
): RequestResult<UpdateScheduleResponses, UpdateScheduleErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateScheduleResponses,
    UpdateScheduleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/schedules/{schedule_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List subscribers
 *
 * Retrieves a list of all subscribers.
 *
 * ### Filtering
 *
 * This endpoint supports filtering. For the general syntax, see [**Filtering**](/guides/Getting-Started/filtering).
 *
 * The following attributes and operators are supported.
 *
 * | Operator | Attribute | Description |
 * | --- | --- | --- |
 * | `eq` | `account_id`, `name`, `email`, `external_ref` | Equals. Checks if the values of two operands are equal. If they are, the condition is true. |
 * | `in` | `account_id`, `name`, `email`, `external_ref` | In. Checks if the value is in the specified list. If it is, the condition is true. |
 * | `like` | `name`, `email` | Partial match (case-sensitive). Use `*` at the start, end, or both to match any sequence of characters (e.g. `*substring`, `substring*`, `*substring*`). |
 * | `ilike` | `name`, `email` | Partial match (case-insensitive). Same as `like` but matching ignores case. Use `*` at the start, end, or both to match any sequence of characters. |
 *
 */
export const listSubscribers = <ThrowOnError extends boolean = false>(
  options?: Options<ListSubscribersData, ThrowOnError>,
): RequestResult<
  ListSubscribersResponses,
  ListSubscribersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListSubscribersResponses,
    ListSubscribersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscribers",
    ...options,
  })

/**
 * Create a subscriber
 */
export const createSubscriber = <ThrowOnError extends boolean = false>(
  options?: Options<CreateSubscriberData, ThrowOnError>,
): RequestResult<
  CreateSubscriberResponses,
  CreateSubscriberErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CreateSubscriberResponses,
    CreateSubscriberErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscribers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete subscriber
 */
export const deleteSubscriber = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSubscriberData, ThrowOnError>,
): RequestResult<
  DeleteSubscriberResponses,
  DeleteSubscriberErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteSubscriberResponses,
    DeleteSubscriberErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscribers/{subscriber_uuid}",
    ...options,
  })

/**
 * Get a subscriber
 */
export const getSubscriber = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriberData, ThrowOnError>,
): RequestResult<GetSubscriberResponses, GetSubscriberErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetSubscriberResponses,
    GetSubscriberErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscribers/{subscriber_uuid}",
    ...options,
  })

/**
 * Update a subscriber
 */
export const updateSubscriber = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSubscriberData, ThrowOnError>,
): RequestResult<
  UpdateSubscriberResponses,
  UpdateSubscriberErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateSubscriberResponses,
    UpdateSubscriberErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/subscribers/{subscriber_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List dunning rules
 *
 * Retrieves a list of all dunning rule sets.
 *
 */
export const listDunningRules = <ThrowOnError extends boolean = false>(
  options?: Options<ListDunningRulesData, ThrowOnError>,
): RequestResult<
  ListDunningRulesResponses,
  ListDunningRulesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListDunningRulesResponses,
    ListDunningRulesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/dunning-rules",
    ...options,
  })

/**
 * Create a dunning rule
 *
 * Dunning rules must use a `fixed` strategy. This means payments are retried on a fixed schedule.
 *
 * When an invoice is created, it immediately becomes eligible for payment by the next payment run. If the first payment attempt fails then the invoice enters dunning. In subsequent payment runs, invoices are only  considered for payment if they meet the dunning rules you create.
 *
 * You can configure a dunning rule to be the default for your store. There can only be one default rule per store. All invoices in your store will then perform dunning according to the specified rules.
 *
 * :::note
 * If no dunning rule is configured, then payment is retried once a day for 10 days, in total 11 payments. You can decide what action to take after the Subscriptions has stopped retrying the payments.
 * :::
 *
 * The following attributes are used to define a `fixed` schedule:
 *
 * - `payment_retry_unit - the unit of time used to measure the intervals between payment attempts or retries.
 * - `payment_retry_interval` - the number of `payment_interval-units` to wait between each payment retry attempt.
 * - `payment_retries_limit` - the number of times subscriptions attempts payments retries before an `action` is taken.
 * - `action` - the action to take if payment is not successful.
 *
 * For example, if:
 *
 * - the `payment_retry_unit` is `days`
 * - the `payment_retry_interval` is `2`
 * - the `payment_rety_limit` is `10`
 * - the `action` is `close`.
 *
 * Subscriptions attempts to retry the payment every 2 days until 10 payment attempts have been tried. At that point, the subscription ends and it's status changes to `inacive`.
 *
 * Following on from this, you can specify that the dunning rule is no longer the default. You do not have to specify another rule to replace it. If you do remove the default dunning rule, the store defaults to the behavior that is followed when dunning is not enabled.
 *
 */
export const createDunningRule = <ThrowOnError extends boolean = false>(
  options?: Options<CreateDunningRuleData, ThrowOnError>,
): RequestResult<
  CreateDunningRuleResponses,
  CreateDunningRuleErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CreateDunningRuleResponses,
    CreateDunningRuleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/dunning-rules",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete dunning rules
 *
 * You can delete a dunning rule at any time. If a dunning rule is deleted then Subscriptions reverts to the configuration used if no dunning rule is set; payment is retried once a day for 10 days, in total 11 payments. You can decide what action to take after the Subscriptions has stopped retrying the payments. See [Dunning Rules](/docs/api/subscriptions/dunning-rules).
 */
export const deleteDunningRule = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDunningRuleData, ThrowOnError>,
): RequestResult<
  DeleteDunningRuleResponses,
  DeleteDunningRuleErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteDunningRuleResponses,
    DeleteDunningRuleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/dunning-rules/{dunning_rule_uuid}",
    ...options,
  })

/**
 * Get dunning rule policy
 */
export const getDunningRule = <ThrowOnError extends boolean = false>(
  options: Options<GetDunningRuleData, ThrowOnError>,
): RequestResult<GetDunningRuleResponses, GetDunningRuleErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetDunningRuleResponses,
    GetDunningRuleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/dunning-rules/{dunning_rule_uuid}",
    ...options,
  })

/**
 * Update dunning rule policy
 *
 * Specify whichever attributes you want to change. The values of the other attributes remain the same. If the attributes section is empty, the rule is not updated. For fields that are optional, an existing value can be removed by specifying a value of null.
 */
export const updateDunningRule = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDunningRuleData, ThrowOnError>,
): RequestResult<
  UpdateDunningRuleResponses,
  UpdateDunningRuleErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateDunningRuleResponses,
    UpdateDunningRuleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/dunning-rules/{dunning_rule_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List proration policies
 *
 * Retrieves a list of all proration policies.
 *
 */
export const listProrationPolicies = <ThrowOnError extends boolean = false>(
  options?: Options<ListProrationPoliciesData, ThrowOnError>,
): RequestResult<
  ListProrationPoliciesResponses,
  ListProrationPoliciesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListProrationPoliciesResponses,
    ListProrationPoliciesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/proration-policies",
    ...options,
  })

/**
 * Create a Proration Policy
 *
 * In Subscriptions, you configure proration by creating a proration policy and attaching it to an offering. Once you have [attached](/docs/api/subscriptions/update-offering) the policy, the proration policy applies to all subscriptions that use the offering.
 *
 */
export const createProrationPolicy = <ThrowOnError extends boolean = false>(
  options?: Options<CreateProrationPolicyData, ThrowOnError>,
): RequestResult<
  CreateProrationPolicyResponses,
  CreateProrationPolicyErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CreateProrationPolicyResponses,
    CreateProrationPolicyErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/proration-policies",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete proration policy
 *
 * A proration policy cannot be deleted if it is being used by any subscriptions. This means you must detach a proration policy that you want to delete from any offerings using that policy before deleting the policy. See [Remove a proration policy from an offering](/docs/api/subscriptions/update-offering).
 */
export const deleteProrationPolicy = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProrationPolicyData, ThrowOnError>,
): RequestResult<
  DeleteProrationPolicyResponses,
  DeleteProrationPolicyErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProrationPolicyResponses,
    DeleteProrationPolicyErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/proration-policies/{proration_policy_uuid}",
    ...options,
  })

/**
 * Get proration policy
 */
export const getProrationPolicy = <ThrowOnError extends boolean = false>(
  options: Options<GetProrationPolicyData, ThrowOnError>,
): RequestResult<
  GetProrationPolicyResponses,
  GetProrationPolicyErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetProrationPolicyResponses,
    GetProrationPolicyErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/proration-policies/{proration_policy_uuid}",
    ...options,
  })

/**
 * Update proration policy
 *
 * You can update a proration policy at any time. For any subscriptions that are using the updated proration policy, the changes are also applied. Specify whichever attributes you want to change. The values of the other attributes remain the same. If the attributes section is empty, the proration policy is not updated.
 *
 * When updating proration policies:
 *
 * - You can change the name of an existing policy.
 * - You can update `rounding`.
 * - You can update `external_ref` as long as `external_ref` is still unique in  your store.
 * - You can remove `external_ref` as this attribute is optional.
 * - You cannot remove any required attributes, such as `name` or `rounding`.
 *
 */
export const updateProrationPolicy = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProrationPolicyData, ThrowOnError>,
): RequestResult<
  UpdateProrationPolicyResponses,
  UpdateProrationPolicyErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProrationPolicyResponses,
    UpdateProrationPolicyErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/proration-policies/{proration_policy_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List features
 *
 * Retrieves a list of all subscription features.
 *
 * ### Filtering
 *
 * This endpoint supports filtering. For the general syntax, see [**Filtering**](/guides/Getting-Started/filtering).
 *
 * The following attributes and operators are supported.
 *
 * | Operator | Attribute | Description |
 * | --- | --- | --- |
 * | `eq` | `external_ref` | Equals. Checks if the values of two operands are equal. If they are, the condition is true. |
 * | `eq` | `tag` | Equals. Checks if the values of two operands are equal. If they are, the condition is true. |
 * | `in` | `external_ref`, `tag` | In. Checks if the value is in the specified list. If it is, the condition is true. |
 *
 */
export const listFeatures = <ThrowOnError extends boolean = false>(
  options?: Options<ListFeaturesData, ThrowOnError>,
): RequestResult<ListFeaturesResponses, ListFeaturesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListFeaturesResponses,
    ListFeaturesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/features",
    ...options,
  })

/**
 * Create a feature
 */
export const createFeature = <ThrowOnError extends boolean = false>(
  options?: Options<CreateFeatureData, ThrowOnError>,
): RequestResult<CreateFeatureResponses, CreateFeatureErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CreateFeatureResponses,
    CreateFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/features",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete feature
 *
 * Remove a feature.
 */
export const deleteFeature = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFeatureData, ThrowOnError>,
): RequestResult<DeleteFeatureResponses, DeleteFeatureErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteFeatureResponses,
    DeleteFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/features/{feature_uuid}",
    ...options,
  })

/**
 * Get feature
 */
export const getFeature = <ThrowOnError extends boolean = false>(
  options: Options<GetFeatureData, ThrowOnError>,
): RequestResult<GetFeatureResponses, GetFeatureErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetFeatureResponses,
    GetFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/features/{feature_uuid}",
    ...options,
  })

/**
 * Update a feature
 *
 * Specify whichever attributes you want to change. The values of the other attributes remain the same. If the attributes section is empty, the feature is not updated. For fields that are optional, an existing value can be removed by specifying a value of null.
 */
export const updateFeature = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFeatureData, ThrowOnError>,
): RequestResult<UpdateFeatureResponses, UpdateFeatureErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateFeatureResponses,
    UpdateFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/subscriptions/features/{feature_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
