// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod"

/**
 * Whether a pricing option is active on a subscription using that offering. The `active_pricing_option` attribute is null if a pricing option is not active in a subscription.
 */
export const zActivePricingOption = z.boolean()

/**
 * Whether a plan is active on a subscription using that offering. The `active_plan` attribute is null if a plan is not active in a subscription.
 */
export const zActivePlan = z.boolean()

/**
 * A unique attribute that you could use to contain information from another company system, for example. The maximum length is 2048 characters.
 */
export const zExternalRef = z.string().max(2048)

/**
 * A unique attribute that you could use to contain information from another company system, for example. The maximum length is 2048 characters.
 */
export const zExternalRefUpdate = z.string().max(2048).nullable()

export const zSubscriptionType = z.enum(["subscription"])

export const zProrationPolicyType = z.enum(["subscription_proration_policy"])

export const zSubscriptionDunningRuleType = z.enum([
  "subscription_dunning_rule",
])

export const zSubscriptionFeatureType = z.enum(["subscription_feature"])

export const zSubscriptionOfferingType = z.enum(["subscription_offering"])

export const zSubscriptionOfferingFeatureType = z.enum([
  "subscription_offering_feature",
])

export const zSubscriptionOfferingPlanType = z.enum([
  "subscription_offering_plan",
])

export const zSubscriptionOfferingPricingOptionType = z.enum([
  "subscription_offering_pricing_option",
])

export const zSubscriptionJobType = z.enum(["subscription_job"])

export const zSubscriptionImportType = z.enum(["subscription_import"])

export const zSubscriptionImportErrorType = z.enum([
  "subscription_import_error",
])

/**
 * This represents the type of resource object being returned. Always `subscription_invoice`.
 */
export const zSubscriptionInvoiceType = z.enum(["subscription_invoice"])

/**
 * This represents the type of resource object being returned. Always `subscription_invoice_payment`.
 */
export const zSubscriptionInvoicePaymentType = z.enum([
  "subscription_invoice_payment",
])

/**
 * This represents the type of resource object being returned. Always `subscription_invoice_payment_refund`.
 */
export const zSubscriptionInvoicePaymentRefundType = z.enum([
  "subscription_invoice_payment_refund",
])

export const zLinkUri = z.string().url().nullable()

export const zLinkObject = z.object({
  href: z.string().url().optional(),
  title: z.string().optional(),
  describedby: z.string().url().optional(),
})

export const zLink = z.union([zLinkUri, zLinkObject])

export const zLinks = z.record(zLink)

export const zTimestamps = z.object({
  updated_at: z.string(),
  created_at: z.string(),
})

export const zSubscriptionImportErrorMeta = z.object({
  owner: z.string(),
  timestamps: zTimestamps,
  error: z.string(),
  field: z.string(),
  line_number: z.number().int(),
  external_ref: zExternalRef.optional(),
})

/**
 * The status of a subscription, either `active` or `inactive`.
 */
export const zStatus = z.enum(["active", "inactive"])

/**
 * Relationships are established between different subscription entities. For example, a plan and a pricing option are related to an offering, as both are attached to it.
 */
export const zRelationships = z.unknown()

/**
 * Links are used to allow you, as an API consumer, to move between requests. Single entities use a self parameter with a link to that specific resource. Sometimes, there aren’t enough entities for a project to fill multiple pages. In this situation, we return some defaults, instead of expecting you to check for these special cases.
 *
 * - current - Always the current page.
 * - first - Always the first page.
 * - last - always `null`.
 * - next - `null` if the user is on the first page.
 * - previous - `null` if there is only one page.
 *
 */
export const zRelationshipLinks = z.object({
  related: z.string().optional(),
})

/**
 * A period of time between a start and end point.
 */
export const zTimePeriod = z.object({
  start: z.string().datetime(),
  end: z.string().datetime(),
})

/**
 * A price in a single currency.
 */
export const zSingleCurrencyPrice = z.object({
  currency: z.string().max(1024),
  amount: z.preprocess(
    (v) => (typeof v === "string" ? Number(v) : v),
    z.number().int(),
  ),
  includes_tax: z.boolean().optional(),
})

/**
 * The timeframe during which the plan price is applicable. For example, for a streaming service, the price is $12.99 and the `unit` is `months` and the `amount` is `1`. In other words, the streaming service is available for $12.99 a month. You may want to specify a unit price if you have many plans that all have different prices. Rather than having to create separate pricing options for each plan, you can specify the timeframe during which the plan price is applicable and then create one pricing option that determines the billing frequency for those plans.
 */
export const zPriceUnits = z.object({
  unit: z.enum(["day", "month"]),
  amount: z.number().int().gte(1),
})

/**
 * The timeframe during which the plan price is applicable. For example, for a streaming service, the price is $12.99 and the `unit` is `months` and the `amount` is `1`. In other words, the streaming service is available for $12.99 a month. You may want to specify a unit price if you have many plans that all have different prices. Rather than having to create separate pricing options for each plan, you can specify the timeframe during which the plan price is applicable and then create one pricing option that determines the billing frequency for those plans.
 */
export const zNullablePriceUnits = z
  .object({
    unit: z.enum(["day", "month"]),
    amount: z.number().int().gte(1),
  })
  .nullable()

export const zPrice = z.unknown()

export const zNullablePrice = z
  .record(
    z
      .object({
        amount: z.preprocess(
          (v) => (typeof v === "string" ? Number(v) : v),
          z.number().int(),
        ),
        includes_tax: z.boolean().optional(),
      })
      .nullable(),
  )
  .nullable()

export const zPriceFormatting = z.object({
  amount: z.preprocess(
    (v) => (typeof v === "string" ? Number(v) : v),
    z.number().int(),
  ),
  currency: z.string(),
  formatted: z.string(),
})

export const zDisplayPrice = z.object({
  without_tax: zPriceFormatting.optional(),
  with_tax: zPriceFormatting.optional(),
  tax: zPriceFormatting.optional(),
})

export const zOfferingPlanPriceForPricingOption = z.object({
  price: zPrice.optional(),
  display_price: zDisplayPrice.optional(),
})

/**
 * A list of plan prices for each of its pricing options.
 */
export const zOfferingPlanPrices = z.record(zOfferingPlanPriceForPricingOption)

/**
 * A tag to add to the customer's account when entitled to the feature.
 */
export const zFeatureTag = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[0-9A-Za-z_-]+$/)

export const zFeatureAccessAttributes = z.object({
  type: z.enum(["access"]),
  tag: zFeatureTag,
})

export const zFeatureUsageAttributes = z.object({
  type: z.enum(["usage"]),
  tag: zFeatureTag,
  label: z.string().min(3).max(1024),
  default_value: z.number().int(),
})

/**
 * A map of merchant-defined string attributes attached to the plan. Carried onto any subscription created from this plan.
 */
export const zPlanCustomAttributes = z.record(z.string().max(512))

export const zPlanAttributes = z.object({
  external_ref: zExternalRef.optional(),
  name: z.string().min(3).max(1024),
  description: z.string().max(1024).optional(),
  sku: z.string().max(1024).optional(),
  main_image: z.string().url().max(1024).optional(),
  price: zPrice.optional(),
  price_units: zPriceUnits.optional(),
})

export const zPlanResponseAttributes = zPlanAttributes.and(zTimestamps)

export const zPlanUpdateAttributes = z.object({
  external_ref: zExternalRefUpdate.optional(),
  name: z.string().min(3).max(1024).optional(),
  description: z.string().max(1024).nullish(),
  sku: z.string().max(1024).nullish(),
  main_image: z.string().url().max(1024).nullish(),
  price: zNullablePrice.optional(),
  price_units: zNullablePriceUnits.optional(),
})

/**
 * The dunning rule attributes you can use to configure your payment retry strategy.
 *
 */
export const zDunningRuleAttributes = z.object({
  payment_retry_type: z.enum(["fixed", "backoff", "tiered"]),
  payment_retry_interval: z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(1).lte(1024),
    )
    .optional(),
  payment_retry_unit: z.enum(["day", "week"]).optional(),
  payment_retry_multiplier: z.number().gte(1).lte(1024).optional(),
  payment_retries_limit: z.preprocess(
    (v) => (typeof v === "string" ? Number(v) : v),
    z.number().int().gte(0),
  ),
  action: z.enum(["none", "pause", "close", "suspend"]),
  default: z.boolean().optional(),
})

export const zDunningRuleCreate = z.object({
  type: zSubscriptionDunningRuleType,
  attributes: zDunningRuleAttributes,
})

export const zDunningRuleUpdateAttributes = z.object({
  payment_retry_type: z.enum(["fixed", "backoff", "tiered"]).optional(),
  payment_retry_interval: z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(1).lte(1024),
    )
    .nullish(),
  payment_retry_unit: z.enum(["day", "week"]).optional(),
  payment_retry_multiplier: z.number().gte(1).lte(1024).nullish(),
  payment_retries_limit: z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
  action: z.enum(["none", "pause", "close", "suspend"]).optional(),
  default: z.boolean().optional(),
})

export const zProrationPolicyAttributes = z.object({
  name: z.string().min(3).max(1024),
  rounding: z.enum(["up", "down", "nearest"]),
  external_ref: zExternalRef.optional(),
  allow_negative_proration_refund: z.boolean().optional().default(false),
})

export const zProrationPolicyResponseAttributes = zProrationPolicyAttributes

export const zProrationPolicyCreate = z.object({
  type: zProrationPolicyType,
  attributes: zProrationPolicyAttributes,
})

export const zProrationPolicyUpdateAttributes = z.object({
  external_ref: zExternalRefUpdate.optional(),
  name: z.string().min(3).max(1024).optional(),
  rounding: z.enum(["up", "down", "nearest"]).optional(),
  allow_negative_proration_refund: z.boolean().optional(),
})

/**
 * Configures an access feature against a plan in an offering, indicating that the referenced feature is a benefit of that plan.
 */
export const zFeatureConfigAccessAttributes = z.object({
  type: z.enum(["access"]),
})

/**
 * Configures a promotion feature against a plan in an offering, indicating that the referenced feature is a benefit of that plan. The tag of the specific promotion that it to be made available must be supplied.
 */
export const zFeatureConfigPromotionAttributes = z.object({
  type: z.enum(["promotion"]),
  tag: zFeatureTag,
})

/**
 * Configures a usage feature against a plan in an offering, indicating that the referenced feature is a benefit of that plan. The default value that the usage metrics adopts must be supplied.
 */
export const zFeatureConfigUsageAttributes = z.object({
  type: z.enum(["usage"]),
  default_value: z.number().int(),
})

export const zFeaturePlanConfiguration = z.intersection(
  z.union([
    zFeatureConfigAccessAttributes,
    zFeatureConfigPromotionAttributes,
    zFeatureConfigUsageAttributes,
  ]),
  z.object({
    type: z.enum(["access", "promotion", "usage"]),
  }),
)

export const zOfferingPlanExtraAttributes = z.object({
  feature_configurations: z.record(zFeaturePlanConfiguration).optional(),
  custom_attributes: zPlanCustomAttributes.optional(),
})

export const zOfferingPlanAttributes = zPlanAttributes.and(
  zOfferingPlanExtraAttributes,
)

export const zOfferingPlanCreate = z.object({
  type: zSubscriptionOfferingPlanType,
  attributes: zOfferingPlanAttributes,
  relationships: zRelationships.optional(),
})

export const zOfferingPlanResponseExtraAttributes = z.object({
  feature_configurations: z.record(zFeaturePlanConfiguration),
  custom_attributes: z.record(z.string()).optional(),
})

export const zOfferingPlanResponseAttributes = zPlanResponseAttributes.and(
  zOfferingPlanResponseExtraAttributes,
)

export const zFeaturePlanConfigurationUpdate = z
  .intersection(
    z.union([
      zFeatureConfigAccessAttributes,
      zFeatureConfigPromotionAttributes,
      zFeatureConfigUsageAttributes,
    ]),
    z.object({
      type: z.enum(["access", "promotion", "usage"]),
    }),
  )
  .nullable()

export const zOfferingPlanUpdateExtraAttributes = z.object({
  feature_configurations: z.record(zFeaturePlanConfigurationUpdate).optional(),
  custom_attributes: z.record(z.string().max(512).nullable()).optional(),
})

export const zOfferingPlanUpdateAttributes = zPlanUpdateAttributes.and(
  zOfferingPlanUpdateExtraAttributes,
)

export const zOfferingBuildPlanPricingOptions = z.array(z.string())

/**
 * A map of plans keyed by plan UUID or external_ref to a list of associated pricing options, similarly keyed.
 */
export const zOfferingBuildPricingOptionAssociations = z.record(
  zOfferingBuildPlanPricingOptions,
)

/**
 * A map of configurations indicating which features are available for the plan
 */
export const zOfferingBuildPlanFeatures = z.record(zFeaturePlanConfiguration)

/**
 * Map of feature configurations keyed by plan UUID or external_ref
 */
export const zOfferingBuildConfiguredFeatures = z.record(
  zOfferingBuildPlanFeatures,
)

export const zOfferingPricingOptionPriceForPlan = z
  .object({
    price: zPrice.optional(),
    display_price: zDisplayPrice.optional(),
  })
  .readonly()

/**
 * The price of each plan within the offering that this pricing option may be applied to.
 */
export const zOfferingPricingOptionPrices = z
  .record(zOfferingPricingOptionPriceForPlan)
  .readonly()

export const zOfferingAttributes = z.object({
  external_ref: zExternalRef.optional(),
  name: z.string().min(3).max(1024),
  description: z.string().max(1024).optional(),
})

export const zOfferingResponseAttributes = zOfferingAttributes.and(zTimestamps)

export const zOfferingUpdateAttributes = z.object({
  external_ref: zExternalRefUpdate.optional(),
  name: z.string().min(3).max(1024).optional(),
  description: z.string().max(1024).nullish(),
})

export const zEmbeddedOfferingPlanExtraAttributes = z.object({
  custom_attributes: zPlanCustomAttributes.optional(),
})

export const zSelectedMetaAttributes = z.object({
  selected: z.boolean().optional(),
})

export const zSelectedMeta = z.object({
  meta: zSelectedMetaAttributes.optional(),
})

export const zPlanAttributesAndSelectedMeta = zPlanAttributes
  .and(zSelectedMeta)
  .and(zEmbeddedOfferingPlanExtraAttributes)

export const zSubscriptionTimestamps = zTimestamps.and(
  z.object({
    canceled_at: z.string().optional(),
    paused_at: z.string().optional(),
    resumed_at: z.string().optional(),
    end_date: z.string().optional(),
    go_live_after: z.string().optional(),
    go_live: z.string().optional(),
  }),
)

/**
 * This represents the type of resource object being returned. Always `subscription_state`.
 */
export const zSubscriptionStateType = z.enum(["subscription_state"])

/**
 * The subscription lifecycle is the states that a subscription can go through when a customer subscribes to a service or a plan.
 *
 * A subscription can have the following states; `canceled`, `paused`, or `resumed`.
 *
 * See [**Managing the subscription lifecycle**](/docs/api/subscriptions/subscriptions#managing-the-subscription-lifecycle).
 *
 */
export const zSubscriptionStateAction = z.enum([
  "cancel",
  "pause",
  "resume",
  "pending",
])

export const zSubscriptionStateAttributes = z.object({
  action: zSubscriptionStateAction,
  cancel_immediately: z.boolean().optional().default(false),
})

export const zChangeState = z.object({
  type: zSubscriptionStateType,
  attributes: zSubscriptionStateAttributes,
})

export const zStateMeta = z
  .object({
    created_at: z.string(),
  })
  .readonly()

/**
 * The kind of prospective subscription change being previewed. Only `plan_pricing_option_change`
 * exists today; this discriminator allows other proration triggers to be added later without a
 * breaking change.
 *
 */
export const zProrationPreviewTriggerType = z.enum([
  "plan_pricing_option_change",
])

/**
 * This represents the type of resource object being sent. Always `proration_preview_request`.
 */
export const zProrationPreviewRequestType = z.enum([
  "proration_preview_request",
])

/**
 * This represents the type of resource object being returned. Always `proration_preview`.
 */
export const zProrationPreviewType = z.enum(["proration_preview"])

export const zProrationPreviewAttributes = z.object({
  trigger: zProrationPreviewTriggerType,
  would_prorate: z.boolean(),
  would_refund: z.boolean().nullish(),
  refund_amount: z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int(),
    )
    .nullish(),
  rejection_reason: z.enum([
    "negative_amount",
    "no_change",
    "refund_not_possible",
    "refund_disallowed_by_policy",
  ]),
  billing_cost_before_proration: z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int(),
    )
    .nullish(),
  refunded_cost_for_unused_pricing_option_period: z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int(),
    )
    .nullish(),
  new_pricing_option_cost: z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int(),
    )
    .nullish(),
  proration_policy_id: z.string().uuid().nullish(),
  prorated_at: z.string().nullish(),
  billing_period_end_date_after_proration: z.string().nullish(),
  refund_period_end_date: z.string().nullish(),
})

export const zProrationPreview = z.object({
  type: zProrationPreviewType,
  attributes: zProrationPreviewAttributes,
})

/**
 * When configured to true, no payment gateway is used and a pending payment is created. See [External Payments](/docs/api/subscriptions/invoices#external-payments).
 */
export const zManualPayments = z.boolean().default(false)

export const zCreatePaymentAuthorityAuthorizeNet = z.object({
  type: z.enum(["authorize_net"]),
  payment_profile_id: z.string().min(3).max(1024),
  customer_profile_id: z.string().min(3).max(1024),
})

export const zCreatePaymentAuthorityEpPayments = z.object({
  type: z.enum(["elastic_path_payments_stripe"]),
  customer_id: z.string().min(3).max(1024),
  card_id: z.string().min(3).max(1024),
})

export const zCreatePaymentAuthorityStripe = z.object({
  type: z.enum(["stripe_payment_intents"]),
  customer_id: z.string().min(3).max(1024),
  card_id: z.string().min(3).max(1024),
})

export const zCreatePaymentAuthority = z.intersection(
  z.union([
    zCreatePaymentAuthorityEpPayments,
    zCreatePaymentAuthorityStripe,
    zCreatePaymentAuthorityAuthorizeNet,
  ]),
  z.object({
    type: z.enum([
      "authorize_net",
      "elastic_path_payments_stripe",
      "stripe_payment_intents",
    ]),
  }),
)

export const zPaymentAuthorityAuthorizeNet = z.object({
  type: z.enum(["authorize_net"]),
  payment_profile_id: z.string().min(3).max(1024).optional(),
  customer_profile_id: z.string().min(3).max(1024).optional(),
})

export const zPaymentAuthorityEpPayments = z.object({
  type: z.enum(["elastic_path_payments_stripe"]),
  customer_id: z.string().min(3).max(1024).optional(),
  card_id: z.string().min(3).max(1024).optional(),
})

export const zPaymentAuthorityStripe = z.object({
  type: z.enum(["stripe_payment_intents"]),
  customer_id: z.string().min(3).max(1024).optional(),
  card_id: z.string().min(3).max(1024).optional(),
})

export const zPaymentAuthority = z.intersection(
  z.union([
    zPaymentAuthorityEpPayments,
    zPaymentAuthorityStripe,
    zPaymentAuthorityAuthorizeNet,
  ]),
  z.object({
    type: z.enum([
      "authorize_net",
      "elastic_path_payments_stripe",
      "stripe_payment_intents",
    ]),
  }),
)

export const zSubscriptionUpdateAttributes = z.object({
  pricing_option_id: z.string().uuid().optional(),
  plan_id: z.string().uuid().optional(),
  address_id: z.string().nullish(),
  payment_authority: zPaymentAuthority.optional(),
  go_live_after: z.string().nullish(),
})

export const zNullablePaymentAuthority = z
  .intersection(
    z.union([
      zPaymentAuthorityEpPayments,
      zPaymentAuthorityStripe,
      zPaymentAuthorityAuthorizeNet,
    ]),
    z.object({
      type: z.enum([
        "authorize_net",
        "elastic_path_payments_stripe",
        "stripe_payment_intents",
      ]),
    }),
  )
  .nullable()

export const zImportAttributes = z.object({
  external_ref: zExternalRef.optional(),
  status: z.enum(["pending", "started", "success", "failed"]),
})

/**
 * You can track the number of records imported to ensure the completeness, accuracy and integrity of the import. Uploaded shows the number of records ready to be imported into Subscriptions. However, this does not mean they are valid subscription objects, only that they have the correct type and their JSON format is properly formatted. Imported shows the number of records that have been both validated and successfully added to Subscriptions.
 */
export const zImportRecords = z.object({
  uploaded: z.object({
    subscription_feature: z.number().int(),
    subscription_subscriber: z.number().int(),
    subscription_offering: z.number().int(),
    subscription: z.number().int(),
  }),
  imported: z.object({
    subscription_feature: z.number().int(),
    subscription_subscriber: z.number().int(),
    subscription_offering: z.number().int(),
    subscription: z.number().int(),
  }),
})

export const zBillingRunReport = z.object({
  invoices_ready_for_payment: z.number().int(),
  invoices_tax_required: z.number().int(),
  invoice_failures: z.number().int(),
  total_ready_for_payment: z.intersection(z.unknown(), zPrice),
  total_tax_required: z.intersection(z.unknown(), zPrice),
})

export const zTaxRunReport = z.object({
  invoices_updated: z.number().int(),
  invoice_failures: z.number().int(),
})

export const zPaymentRunReport = z.object({
  total_payment_attempts: z.number().int(),
  failed_payments: z.number().int(),
  total_collected: z.intersection(z.unknown(), zPrice),
})

export const zNotificationRunReport = z.object({
  total_notifications_sent: z.number().int(),
  failed_notifications: z.number().int(),
})

export const zSubscriptionUpdateReport = z.object({
  subscriptions_updated: z.number().int(),
  subscription_failures: z.number().int(),
  total_processed: z.number().int(),
})

/**
 * You can track your Subscriptions billing, tax, and payment operations using reports.
 */
export const zJobReport = z.union([
  zBillingRunReport,
  zTaxRunReport,
  zPaymentRunReport,
  zNotificationRunReport,
  zSubscriptionUpdateReport,
])

export const zJobTimestamps = zTimestamps.and(
  z.object({
    started_at: z.string().optional(),
    finished_at: z.string().optional(),
  }),
)

/**
 * The type of job. One of the following:
 * - `billing-run` - a billing run job.
 * - `payment-run` - a payment run job.
 * - `notification-run` - a notification run job.
 *
 */
export const zScheduleJobType = z.enum([
  "billing-run",
  "payment-run",
  "notification-run",
])

export const zBillingRunJobAttributes = z.object({
  job_type: z.string(),
})

export const zPaymentRunJobAttributes = z.object({
  job_type: z.string(),
})

export const zImportJobAttributes = z.object({
  job_type: z.string(),
})

export const zNotificationRunJobAttributes = z.object({
  job_type: z.string(),
})

export const zSubscriptionPriceChanges = z.object({
  plan_prices: z.unknown().optional(),
  pricing_option_prices: z.unknown().optional(),
})

/**
 * A record of the previous prices of a subscription before a price change was applied
 */
export const zSubscriptionPriceUpdateHistoryEntry = z.object({
  price_changes: zSubscriptionPriceChanges,
  valid_until: z.string().datetime(),
})

export const zPricingOptionPrice = z.object({
  base_price_percentage: z.number().gte(0).lte(100).optional(),
  fixed_price: zPrice.optional(),
})

export const zJobAttributes = z.object({
  external_ref: zExternalRef.optional(),
  status: z.enum(["pending", "started", "success", "failed"]),
})

export const zTaxItem = z.object({
  type: z.enum(["tax_item"]),
  name: z.string().max(1024).optional(),
  code: z.string().max(1024).optional(),
  rate: z.number(),
  jurisdiction: z.string().max(1024).optional(),
})

/**
 * A notification scheduled for an invoice.
 */
export const zInvoiceNotification = z.object({
  name: z.string(),
  due: z.string().datetime(),
  sent_at: z.string().datetime().optional(),
})

export const zUpdateInvoicePaymentAttributes = z.object({
  success: z.boolean(),
  external_payment_id: z.string().max(1024).optional(),
  failure_detail: z.string().optional(),
  payment_taken_at: z.string().optional(),
})

export const zSubscriptionInvoicePaymentRefundAttributes = z.object({
  amount: z.preprocess(
    (v) => (typeof v === "string" ? Number(v) : v),
    z.number().int().gte(1),
  ),
  reason: z.string().max(1024),
  gateway: z.string().max(1024),
  external_refund_id: z.string().max(1024),
  created_at: z.string(),
})

export const zCreateInvoicePaymentRefund = z.object({
  type: zSubscriptionInvoicePaymentRefundType,
  attributes: z.object({
    amount: z.preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(1),
    ),
    reason: z.string().min(1).max(1024),
  }),
})

export const zInvoiceTimestamps = zTimestamps.and(
  z.object({
    taxes_added_at: z.string().optional(),
  }),
)

export const zInvoicePaymentTimestamps = zTimestamps.and(
  z.object({
    payment_taken_at: z.string().optional(),
  }),
)

/**
 * The reason the payment failed.
 */
export const zPaymentFailureDetail = z.object({
  reason: z.string().optional(),
})

export const zSubscriptionInvoicePaymentAttributes = z.object({
  success: z.boolean(),
  pending: z.boolean().optional(),
  gateway: z.string().max(1024),
  external_payment_id: z.string().max(1024).optional(),
  failure_detail: zPaymentFailureDetail.optional(),
  amount: zSingleCurrencyPrice,
})

export const zError = z.object({
  status: z.string(),
  title: z.string(),
  detail: z.string().optional(),
  meta: z.record(z.unknown()).optional(),
})

export const zErrorResponse = z.object({
  errors: z.array(zError),
})

/**
 * The three-letter [**ISO currency code**](https://www.iso.org/iso-4217-currency-codes.html) in uppercase.
 */
export const zCurrencyIdentifier = z.string().max(1024)

/**
 * The unique identifier.
 */
export const zUuid = z.string().uuid()

export const zSubscriptionImportError = z.object({
  id: zUuid,
  type: zSubscriptionImportErrorType,
  meta: zSubscriptionImportErrorMeta,
})

export const zRelationshipData = z.object({
  id: zUuid,
  type: z.string(),
})

/**
 * Enumerates a list of resources that are related.
 */
export const zRelationshipsRequest = z.object({
  data: z.array(zRelationshipData),
})

/**
 * The list of resources that are related.
 */
export const zManyRelationship = z.object({
  data: z.array(zRelationshipData).optional(),
  links: zRelationshipLinks.optional(),
})

/**
 * The subscription resource that is related.
 */
export const zSingleRelationship = z.object({
  data: zRelationshipData.optional(),
  links: zRelationshipLinks.optional(),
})

export const zRelationship = z.union([zSingleRelationship, zManyRelationship])

export const zFeaturePromotion = z.object({
  name: z.string().min(3).max(1024),
  tag: zFeatureTag,
  promotion_id: zUuid.optional(),
})

export const zFeaturePromotionAttributes = z.object({
  type: z.enum(["promotion"]),
  promotions: z.array(zFeaturePromotion),
})

export const zFeatureConfiguration = z.intersection(
  z.union([
    zFeatureAccessAttributes,
    zFeaturePromotionAttributes,
    zFeatureUsageAttributes,
  ]),
  z.object({
    type: z.enum(["access", "promotion", "usage"]),
  }),
)

export const zFeatureAttributes = z.object({
  external_ref: zExternalRef.optional(),
  name: z.string().min(3).max(1024),
  description: z.string().max(1024).optional(),
  configuration: zFeatureConfiguration,
})

export const zFeatureCreate = z.object({
  type: zSubscriptionFeatureType,
  attributes: zFeatureAttributes,
})

export const zOfferingFeatureCreate = z.object({
  type: zSubscriptionOfferingFeatureType,
  attributes: zFeatureAttributes,
})

export const zFeatureResponseAttributes = zFeatureAttributes

export const zFeatureUpdateAttributes = z.object({
  external_ref: zExternalRefUpdate.optional(),
  name: z.string().min(3).max(1024).optional(),
  description: z.string().max(1024).nullish(),
  configuration: zFeatureConfiguration.optional(),
})

export const zFeatureUpdate = z.object({
  id: zUuid,
  type: zSubscriptionFeatureType,
  attributes: zFeatureUpdateAttributes,
})

export const zDunningRuleUpdate = z.object({
  id: zUuid,
  type: zSubscriptionDunningRuleType,
  attributes: zDunningRuleUpdateAttributes,
})

export const zProrationPolicyUpdate = z.object({
  id: zUuid,
  type: zProrationPolicyType,
  attributes: zProrationPolicyUpdateAttributes,
})

export const zProrationPolicyRelationshipAttributes = z.object({
  type: zProrationPolicyType,
  id: zUuid,
})

export const zProrationPolicyUpdateRelationshipAttributes = z
  .object({
    type: zProrationPolicyType,
    id: zUuid,
  })
  .nullable()

export const zOfferingPlanUpdate = z.object({
  id: zUuid,
  type: zSubscriptionOfferingPlanType,
  attributes: zOfferingPlanUpdateAttributes,
})

export const zOfferingFeatureUpdate = z.object({
  id: zUuid,
  type: zSubscriptionOfferingFeatureType,
  attributes: zFeatureUpdateAttributes,
})

/**
 * A list of feature IDs to attach to the offering. See [**List Features**](/docs/api/subscriptions/list-features).
 */
export const zOfferingFeatureAttach = z.object({
  features: z.array(zUuid).min(1),
})

export const zOfferingRelationships = z.object({
  proration_policy: zProrationPolicyRelationshipAttributes.optional(),
})

export const zOfferingCreate = z.object({
  type: zSubscriptionOfferingType,
  attributes: zOfferingAttributes,
  relationships: zOfferingRelationships.optional(),
})

export const zOfferingUpdateRelationships = z.object({
  proration_policy: zProrationPolicyUpdateRelationshipAttributes.optional(),
})

export const zOfferingUpdate = z.intersection(
  z.unknown(),
  z.object({
    id: zUuid,
    type: zSubscriptionOfferingType,
    attributes: zOfferingUpdateAttributes.optional(),
    relationships: zOfferingUpdateRelationships.optional(),
  }),
)

/**
 * A subscription may optionally be associated with an item in an order by supplying both the order ID and the ID of the item within that order.
 */
export const zBuildSubscriptionOrder = z.object({
  order_id: zUuid,
  order_item_id: zUuid,
})

export const zManageSubscriptionPlans = z.object({
  type: z.enum(["detach"]),
  plans: z.array(zUuid).min(1),
})

export const zSubscriptionUpdate = z.object({
  id: zUuid,
  type: zSubscriptionType,
  attributes: zSubscriptionUpdateAttributes,
})

export const zSubscriptionState = z.object({
  id: zUuid.optional(),
  type: zSubscriptionStateType,
  attributes: zSubscriptionStateAttributes,
  meta: zStateMeta,
})

export const zProrationPreviewRequestAttributes = z.object({
  trigger: zProrationPreviewTriggerType,
  pricing_option_id: zUuid,
  plan_id: zUuid,
})

export const zProrationPreviewRequest = z.object({
  type: zProrationPreviewRequestType,
  attributes: zProrationPreviewRequestAttributes,
})

export const zSubscriptionUpdateRunJobAttributes = z.object({
  job_type: z.string(),
  offering_id: z.string().uuid().optional(),
  excluded_subscription_ids: z.array(zUuid).optional(),
  subscription_ids: z.array(zUuid).optional(),
  price_changes: zSubscriptionPriceChanges,
})

export const zInvoiceTaxItems = z.object({
  invoice_id: zUuid,
  tax_items: z.array(zTaxItem),
})

export const zTaxRunJobAttributes = z.object({
  job_type: z.string(),
  taxes: z.array(zInvoiceTaxItems).min(1).optional(),
})

export const zJobCreateAttributes = z.intersection(
  z.union([
    zBillingRunJobAttributes,
    zTaxRunJobAttributes,
    zPaymentRunJobAttributes,
    zImportJobAttributes,
    zNotificationRunJobAttributes,
    zSubscriptionUpdateRunJobAttributes,
  ]),
  z.object({
    external_ref: zExternalRef.optional(),
    job_type: z.enum([
      "billing-run",
      "tax-run",
      "payment-run",
      "import",
      "notification-run",
      "subscription-update",
    ]),
  }),
)

export const zJobCreate = z.object({
  type: zSubscriptionJobType,
  attributes: zJobCreateAttributes,
})

export const zJobResponseAttributes = zJobCreateAttributes
  .and(zJobAttributes)
  .and(zTimestamps)

export const zUpdateInvoicePayment = z.object({
  id: zUuid,
  type: zSubscriptionInvoicePaymentType,
  attributes: zUpdateInvoicePaymentAttributes,
})

export const zProrationEvent = z.object({
  proration_policy_id: zUuid,
  billing_cost_before_proration: z.preprocess(
    (v) => (typeof v === "string" ? Number(v) : v),
    z.number().int(),
  ),
  refunded_amount_for_unused_pricing_option: z.preprocess(
    (v) => (typeof v === "string" ? Number(v) : v),
    z.number().int(),
  ),
  new_pricing_option_cost: z.preprocess(
    (v) => (typeof v === "string" ? Number(v) : v),
    z.number().int(),
  ),
  prorated_at: z.string(),
})

export const zSubscriptionInvoicePaymentRefund = z.object({
  id: zUuid,
  type: zSubscriptionInvoicePaymentRefundType,
  attributes: zSubscriptionInvoicePaymentRefundAttributes,
  relationships: zRelationships,
})

export const zSubscriptionInvoiceItem = z.object({
  description: z.string(),
  price: zSingleCurrencyPrice,
  plan_id: zUuid.optional(),
  from_time_period: z.string().optional(),
  until_time_period: z.string().optional(),
})

export const zSubscriptionInvoiceAttributes = z.object({
  billing_period: zTimePeriod,
  invoice_items: z.array(zSubscriptionInvoiceItem),
  tax_items: z.array(zTaxItem).optional(),
  outstanding: z.boolean(),
  number: z.number().int().optional(),
  tax_required: z.boolean(),
  payment_retries_limit_reached: z.boolean(),
  updated_at: z.string().optional(),
  created_at: z.string().optional(),
  pro_forma: z.boolean(),
  valid_from: z.string().optional(),
  manual_payment_pending: z.boolean(),
})

/**
 * The owner of a resource, either `store` or `organization`.
 */
export const zOwnerMeta = z.string().readonly()

export const zFeatureMeta = z
  .object({
    owner: zOwnerMeta,
    timestamps: zTimestamps,
  })
  .readonly()

export const zFeature = z.object({
  id: zUuid.optional(),
  type: zSubscriptionFeatureType,
  attributes: zFeatureResponseAttributes,
  meta: zFeatureMeta,
})

export const zPlanMeta = z
  .object({
    prices: zOfferingPlanPrices.optional(),
    display_price: zDisplayPrice.optional(),
    owner: zOwnerMeta,
    timestamps: zTimestamps,
    active_plan: zActivePlan.optional(),
  })
  .readonly()

export const zDunningRuleMeta = z
  .object({
    owner: zOwnerMeta,
    timestamps: zTimestamps,
  })
  .readonly()

export const zDunningRule = z.object({
  id: zUuid.optional(),
  type: zSubscriptionDunningRuleType,
  attributes: zDunningRuleAttributes,
  meta: zDunningRuleMeta,
})

export const zProrationPolicyMeta = z
  .object({
    owner: zOwnerMeta,
    timestamps: zTimestamps,
  })
  .readonly()

export const zProrationPolicy = z.object({
  id: zUuid.optional(),
  type: zProrationPolicyType,
  attributes: zProrationPolicyResponseAttributes,
  meta: zProrationPolicyMeta,
})

export const zOfferingFeature = z.object({
  id: zUuid.optional(),
  type: zSubscriptionOfferingFeatureType,
  attributes: zFeatureResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zFeatureMeta,
})

export const zOfferingPlan = z.object({
  id: zUuid.optional(),
  type: zSubscriptionOfferingPlanType,
  attributes: zOfferingPlanResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zPlanMeta,
})

export const zOfferingPricingOptionMeta = z
  .object({
    prices: zOfferingPricingOptionPrices.optional(),
    price: zPrice.optional(),
    display_price: zDisplayPrice.optional(),
    active_pricing_option: zActivePricingOption.optional(),
    owner: zOwnerMeta,
    timestamps: zTimestamps,
  })
  .readonly()

export const zSubscriptionMeta = z
  .object({
    owner: zOwnerMeta,
    timestamps: zSubscriptionTimestamps,
    status: zStatus,
    state: zSubscriptionState.optional(),
    manual_payments: zManualPayments,
    first_invoice_prepaid: z.boolean(),
    canceled: z.boolean(),
    paused: z.boolean(),
    closed: z.boolean(),
    suspended: z.boolean(),
    pending: z.boolean(),
    invoice_after: z.string(),
    pending_price_change: zSubscriptionPriceChanges.optional(),
    price_update_history: z
      .array(zSubscriptionPriceUpdateHistoryEntry)
      .optional(),
    last_refund_id: z.string().uuid().optional(),
    last_refund_amount: z
      .preprocess(
        (v) => (typeof v === "string" ? Number(v) : v),
        z.number().int(),
      )
      .optional(),
    paused_by: z.enum(["subscriber", "merchandizer", "dunning"]).optional(),
  })
  .readonly()

export const zImportMeta = z
  .object({
    owner: zOwnerMeta,
    timestamps: zJobTimestamps,
    records: zImportRecords,
  })
  .readonly()

export const zImport = z.object({
  id: zUuid.optional(),
  type: zSubscriptionImportType,
  attributes: zImportAttributes,
  meta: zImportMeta,
})

export const zJobMeta = z
  .object({
    owner: zOwnerMeta,
    timestamps: zJobTimestamps,
    report: zJobReport.optional(),
  })
  .readonly()

export const zJob = z.object({
  id: zUuid.optional(),
  type: zSubscriptionJobType,
  attributes: zJobResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zJobMeta,
})

export const zSubscriptionInvoiceMeta = z
  .object({
    owner: zOwnerMeta,
    subscription_id: zUuid.optional(),
    subscriber_id: zUuid.optional(),
    price: zSingleCurrencyPrice.optional(),
    display_price: zDisplayPrice,
    notifications: z.array(zInvoiceNotification).optional(),
    timestamps: zInvoiceTimestamps,
    proration_events: z.array(zProrationEvent).nullable(),
    pro_rata_remaining_value: z.preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int(),
    ),
  })
  .readonly()

export const zSubscriptionInvoice = z.object({
  id: zUuid.optional(),
  type: zSubscriptionInvoiceType,
  attributes: zSubscriptionInvoiceAttributes,
  relationships: zRelationships.optional(),
  meta: zSubscriptionInvoiceMeta,
})

export const zSubscriptionInvoicePaymentMeta = z
  .object({
    owner: zOwnerMeta,
    subscription_id: zUuid,
    invoice_id: zUuid,
    job_id: zUuid,
    timestamps: zInvoicePaymentTimestamps,
    manual_payment: z.boolean(),
  })
  .readonly()

export const zSubscriptionInvoicePayment = z.object({
  id: zUuid,
  type: zSubscriptionInvoicePaymentType,
  attributes: zSubscriptionInvoicePaymentAttributes,
  meta: zSubscriptionInvoicePaymentMeta,
})

/**
 * The offerings plan external_ref value
 */
export const zOfferingPlanExternalRefMeta = z.string().readonly()

export const zOfferingMeta = z
  .object({
    external_plan_refs: z.array(zOfferingPlanExternalRefMeta),
    owner: zOwnerMeta,
    timestamps: zTimestamps,
  })
  .readonly()

export const zOffering = z.object({
  id: zUuid.optional(),
  type: zSubscriptionOfferingType,
  attributes: zOfferingResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zOfferingMeta,
})

export const zSubscriptionAttributes = z.object({
  external_ref: zExternalRef.optional(),
  account_id: zUuid,
  address_id: zUuid.optional(),
  offering: zOffering,
  pricing_option_id: zUuid,
  plan_id: zUuid,
  currency: zCurrencyIdentifier,
  payment_authority: zPaymentAuthority.optional(),
})

export const zSubscription = z.object({
  id: zUuid.optional(),
  type: zSubscriptionType,
  attributes: zSubscriptionAttributes,
  relationships: zRelationships.optional(),
  meta: zSubscriptionMeta,
})

export const zSubscriberMeta = z
  .object({
    feature_entitlements: z.array(zFeatureTag).optional(),
    owner: zOwnerMeta,
    timestamps: zTimestamps,
  })
  .readonly()

export const zSubscriptionSubscriberType = z.enum(["subscription_subscriber"])

export const zSubscriberAttributes = z.object({
  account_id: zUuid,
  name: z.string().min(3).max(1024),
  email: z.string().email().min(3).max(1024),
  payment_authority: zPaymentAuthority.optional(),
})

export const zSubscriberResponseAttributes =
  zSubscriberAttributes.and(zTimestamps)

export const zSubscriber = z.object({
  id: zUuid.optional(),
  type: zSubscriptionSubscriberType,
  attributes: zSubscriberResponseAttributes,
  meta: zSubscriberMeta,
})

export const zSubscriberUpdateAttributes = z.object({
  name: z.string().min(3).max(1024).optional(),
  email: z.string().email().min(3).max(1024).optional(),
  payment_authority: zNullablePaymentAuthority.optional(),
})

export const zSubscriberCreate = z.object({
  type: zSubscriptionSubscriberType,
  attributes: zSubscriberAttributes,
})

export const zSubscriberUpdate = z.object({
  id: zUuid,
  type: zSubscriptionSubscriberType,
  attributes: zSubscriberUpdateAttributes,
})

export const zScheduleMeta = z
  .object({
    scheduled_for: z.string().datetime().optional(),
    owner: zOwnerMeta,
    timestamps: zTimestamps,
  })
  .readonly()

export const zSubscriptionScheduleType = z.enum(["subscription_schedule"])

export const zScheduleJob = z.object({
  job_type: zScheduleJobType,
})

export const zScheduleAttributes = z.object({
  external_ref: zExternalRef.optional(),
  name: z.string().min(3).max(1024).optional(),
  specification: z.string().max(1024),
  location: z.string().max(1024),
  job: zScheduleJob,
})

export const zScheduleCreate = z.object({
  type: zSubscriptionScheduleType,
  attributes: zScheduleAttributes,
})

export const zScheduleResponseAttributes = zScheduleAttributes.and(zTimestamps)

export const zSchedule = z.object({
  id: zUuid.optional(),
  type: zSubscriptionScheduleType,
  attributes: zScheduleResponseAttributes,
  meta: zScheduleMeta,
})

export const zScheduleUpdateAttributes = z.object({
  external_ref: zExternalRefUpdate.optional(),
  name: z.string().min(3).max(1024).nullish(),
  specification: z.string().max(1024).optional(),
  location: z.string().max(1024).optional(),
  job: zScheduleJob.optional(),
})

export const zScheduleUpdate = z.object({
  id: zUuid,
  type: zSubscriptionScheduleType,
  attributes: zScheduleUpdateAttributes,
})

/**
 * Configuration of the lead time to generate an invoice ahead of time in a pro-forma state
 */
export const zLeadTime = z.object({
  type: z.enum(["day", "week"]),
  time: z.number().int().gte(1),
})

/**
 * Configuration of the lead time to generate an invoice ahead of time in a pro-forma state
 */
export const zNullableLeadTime = z
  .object({
    type: z.enum(["day", "week"]),
    time: z.number().int().gte(1),
  })
  .nullable()

export const zNotificationSchedule = z.object({
  name: z.string().min(1).max(1024),
  unit: z.enum(["day", "week", "month"]),
  amount: z.preprocess(
    (v) => (typeof v === "string" ? Number(v) : v),
    z.number().int().gte(1),
  ),
})

export const zPricingOptionAttributes = z.object({
  external_ref: zExternalRef.optional(),
  name: z.string().min(3).max(1024),
  description: z.string().max(1024).optional(),
  billing_interval_type: z.enum(["day", "week", "month", "year"]),
  billing_frequency: z.number().int().gte(1),
  trial_period: z.number().int().gte(0).optional(),
  lead_time: zLeadTime.optional(),
  notification_schedule: z.array(zNotificationSchedule).optional(),
  plan_length: z.number().int().gte(1),
  end_behavior: z.enum(["close", "roll"]),
  can_pause: z.boolean(),
  can_resume: z.boolean(),
  can_cancel: z.boolean(),
  base_price_percentage: z.number().gte(0).lte(100).optional(),
  fixed_price: zPrice.optional(),
})

export const zOfferingPricingOptionCreate = z.object({
  type: zSubscriptionOfferingPricingOptionType,
  attributes: zPricingOptionAttributes,
})

export const zPricingOptionResponseAttributes =
  zPricingOptionAttributes.and(zTimestamps)

export const zPricingOptionUpdateAttributes = z.object({
  external_ref: zExternalRefUpdate.optional(),
  name: z.string().min(3).max(1024).optional(),
  description: z.string().max(1024).nullish(),
  billing_interval_type: z.enum(["day", "week", "month", "year"]).optional(),
  billing_frequency: z.number().int().gte(1).optional(),
  trial_period: z.number().int().gte(0).nullish(),
  plan_length: z.number().int().gte(1).optional(),
  lead_time: zNullableLeadTime.optional(),
  notification_schedule: z.array(zNotificationSchedule).optional(),
  end_behavior: z.enum(["close", "roll"]).optional(),
  can_pause: z.boolean().optional(),
  can_resume: z.boolean().optional(),
  can_cancel: z.boolean().optional(),
  base_price_percentage: z.number().gte(0).lte(100).nullish(),
  fixed_price: zNullablePrice.optional(),
})

export const zBuildOffering = z.object({
  external_ref: zExternalRef.optional(),
  name: z.string().min(3).max(1024),
  description: z.string().max(1024).optional(),
  proration_policy_id: z.string().optional(),
  configured_features: zOfferingBuildConfiguredFeatures.optional(),
  pricing_option_associations:
    zOfferingBuildPricingOptionAssociations.optional(),
  features: z
    .array(z.union([zExternalRef, zFeatureAttributes, zUuid]))
    .min(1)
    .optional(),
  plans: z.array(zOfferingPlanAttributes).min(1),
  pricing_options: z.array(zPricingOptionAttributes).min(1),
})

export const zOfferingPricingOptionUpdate = z.object({
  id: zUuid,
  type: zSubscriptionOfferingPricingOptionType,
  attributes: zPricingOptionUpdateAttributes,
})

export const zOfferingPricingOption = z.object({
  id: zUuid.optional(),
  type: zSubscriptionOfferingPricingOptionType,
  attributes: zPricingOptionResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zOfferingPricingOptionMeta,
})

export const zOfferingIncludes = z
  .object({
    features: z.array(zOfferingFeature).optional(),
    plans: z.array(zOfferingPlan).optional(),
    pricing_options: z.array(zOfferingPricingOption).optional(),
  })
  .readonly()

export const zPricingOptionAttributesAndSelectedMeta =
  zPricingOptionAttributes.and(zSelectedMeta)

export const zBuildSubscription = z.object({
  external_ref: zExternalRef.optional(),
  account_id: zUuid,
  address_id: zUuid.optional(),
  offering_external_ref: zExternalRef.optional(),
  offering_id: zUuid.optional(),
  plan_id: zUuid.optional(),
  pricing_option_id: zUuid.optional(),
  currency: zCurrencyIdentifier,
  payment_authority: zCreatePaymentAuthority.optional(),
  manual_payments: zManualPayments,
  name: z.string().min(3).max(1024),
  email: z.string().email().min(3).max(1024),
  pending: z.boolean().optional(),
  first_invoice_paid: z.boolean().optional(),
  started_at: z.string().optional(),
  override_first_period_end_date: z.string().datetime().optional(),
  offering: zOfferingAttributes.optional(),
  features: z
    .array(z.union([zExternalRef, zFeatureAttributes, zUuid]))
    .min(1)
    .optional(),
  plans: z.array(zPlanAttributesAndSelectedMeta).min(1).optional(),
  pricing_options: z
    .array(zPricingOptionAttributesAndSelectedMeta)
    .min(1)
    .optional(),
  configured_features: zOfferingBuildConfiguredFeatures.optional(),
  pricing_option_associations:
    zOfferingBuildPricingOptionAssociations.optional(),
  selected_plan: zExternalRef.optional(),
  selected_pricing_option: zExternalRef.optional(),
  order: zBuildSubscriptionOrder.optional(),
  meta: zSubscriptionMeta.optional(),
})

export const zSubscriptionIncludes = z
  .object({
    plans: z.array(zOfferingPlan).optional(),
    pricing_options: z.array(zOfferingPricingOption).optional(),
  })
  .readonly()

export const zFeatureMetaWritable = z
  .object({
    timestamps: zTimestamps,
  })
  .readonly()

export const zFeatureWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionFeatureType,
  attributes: zFeatureResponseAttributes,
  meta: zFeatureMetaWritable,
})

export const zPlanMetaWritable = z
  .object({
    prices: zOfferingPlanPrices.optional(),
    display_price: zDisplayPrice.optional(),
    timestamps: zTimestamps,
    active_plan: zActivePlan.optional(),
  })
  .readonly()

export const zDunningRuleMetaWritable = z
  .object({
    timestamps: zTimestamps,
  })
  .readonly()

export const zDunningRuleWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionDunningRuleType,
  attributes: zDunningRuleAttributes,
  meta: zDunningRuleMetaWritable,
})

export const zProrationPolicyMetaWritable = z
  .object({
    timestamps: zTimestamps,
  })
  .readonly()

export const zProrationPolicyWritable = z.object({
  id: zUuid.optional(),
  type: zProrationPolicyType,
  attributes: zProrationPolicyResponseAttributes,
  meta: zProrationPolicyMetaWritable,
})

export const zOfferingMetaWritable = z
  .object({
    external_plan_refs: z.array(z.unknown()),
    timestamps: zTimestamps,
  })
  .readonly()

export const zOfferingWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionOfferingType,
  attributes: zOfferingResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zOfferingMetaWritable,
})

/**
 * A map of plans keyed by plan UUID or external_ref to a list of associated pricing options, similarly keyed.
 */
export const zOfferingBuildPricingOptionAssociationsWritable = z.record(
  zOfferingBuildPlanPricingOptions,
)

export const zOfferingFeatureWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionOfferingFeatureType,
  attributes: zFeatureResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zFeatureMetaWritable,
})

export const zOfferingPlanWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionOfferingPlanType,
  attributes: zOfferingPlanResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zPlanMetaWritable,
})

/**
 * The price of each plan within the offering that this pricing option may be applied to.
 */
export const zOfferingPricingOptionPricesWritable = z
  .record(zOfferingPricingOptionPriceForPlan)
  .readonly()

export const zOfferingPricingOptionMetaWritable = z
  .object({
    prices: zOfferingPricingOptionPricesWritable.optional(),
    price: zPrice.optional(),
    display_price: zDisplayPrice.optional(),
    active_pricing_option: zActivePricingOption.optional(),
    timestamps: zTimestamps,
  })
  .readonly()

export const zOfferingPricingOptionWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionOfferingPricingOptionType,
  attributes: zPricingOptionResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zOfferingPricingOptionMetaWritable,
})

export const zOfferingIncludesWritable = z
  .object({
    features: z.array(zOfferingFeatureWritable).optional(),
    plans: z.array(zOfferingPlanWritable).optional(),
    pricing_options: z.array(zOfferingPricingOptionWritable).optional(),
  })
  .readonly()

export const zSubscriptionIncludesWritable = z
  .object({
    plans: z.array(zOfferingPlanWritable).optional(),
    pricing_options: z.array(zOfferingPricingOptionWritable).optional(),
  })
  .readonly()

export const zSubscriptionStateWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionStateType,
  attributes: zSubscriptionStateAttributes,
  meta: zStateMeta,
})

export const zSubscriptionMetaWritable = z
  .object({
    timestamps: zSubscriptionTimestamps,
    status: zStatus,
    state: zSubscriptionStateWritable.optional(),
    manual_payments: zManualPayments,
    first_invoice_prepaid: z.boolean(),
    canceled: z.boolean(),
    paused: z.boolean(),
    closed: z.boolean(),
    suspended: z.boolean(),
    pending: z.boolean(),
    invoice_after: z.string(),
    pending_price_change: zSubscriptionPriceChanges.optional(),
    price_update_history: z
      .array(zSubscriptionPriceUpdateHistoryEntry)
      .optional(),
    last_refund_id: z.string().uuid().optional(),
    last_refund_amount: z
      .preprocess(
        (v) => (typeof v === "string" ? Number(v) : v),
        z.number().int(),
      )
      .optional(),
    paused_by: z.enum(["subscriber", "merchandizer", "dunning"]).optional(),
  })
  .readonly()

export const zPaymentAuthorityWritable = z.intersection(
  z.union([
    zPaymentAuthorityEpPayments,
    zPaymentAuthorityStripe,
    zPaymentAuthorityAuthorizeNet,
  ]),
  z.object({
    type: z.enum([
      "authorize_net",
      "elastic_path_payments_stripe",
      "stripe_payment_intents",
    ]),
  }),
)

export const zSubscriptionUpdateAttributesWritable = z.object({
  pricing_option_id: z.string().uuid().optional(),
  plan_id: z.string().uuid().optional(),
  address_id: z.string().nullish(),
  payment_authority: zPaymentAuthorityWritable.optional(),
  go_live_after: z.string().nullish(),
})

export const zSubscriptionUpdateWritable = z.object({
  id: zUuid,
  type: zSubscriptionType,
  attributes: zSubscriptionUpdateAttributesWritable,
})

export const zSubscriptionAttributesWritable = z.object({
  external_ref: zExternalRef.optional(),
  account_id: zUuid,
  address_id: zUuid.optional(),
  offering: zOfferingWritable,
  pricing_option_id: zUuid,
  plan_id: zUuid,
  currency: zCurrencyIdentifier,
  payment_authority: zPaymentAuthorityWritable.optional(),
})

export const zSubscriptionWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionType,
  attributes: zSubscriptionAttributesWritable,
  relationships: zRelationships.optional(),
  meta: zSubscriptionMetaWritable,
})

export const zNullablePaymentAuthorityWritable = z
  .intersection(
    z.union([
      zPaymentAuthorityEpPayments,
      zPaymentAuthorityStripe,
      zPaymentAuthorityAuthorizeNet,
    ]),
    z.object({
      type: z.enum([
        "authorize_net",
        "elastic_path_payments_stripe",
        "stripe_payment_intents",
      ]),
    }),
  )
  .nullable()

export const zCreatePaymentAuthorityWritable = z.intersection(
  z.union([
    zCreatePaymentAuthorityEpPayments,
    zCreatePaymentAuthorityStripe,
    zCreatePaymentAuthorityAuthorizeNet,
  ]),
  z.object({
    type: z.enum([
      "authorize_net",
      "elastic_path_payments_stripe",
      "stripe_payment_intents",
    ]),
  }),
)

export const zBuildSubscriptionWritable = z.object({
  external_ref: zExternalRef.optional(),
  account_id: zUuid,
  address_id: zUuid.optional(),
  offering_external_ref: zExternalRef.optional(),
  offering_id: zUuid.optional(),
  plan_id: zUuid.optional(),
  pricing_option_id: zUuid.optional(),
  currency: zCurrencyIdentifier,
  payment_authority: zCreatePaymentAuthorityWritable.optional(),
  manual_payments: zManualPayments,
  name: z.string().min(3).max(1024),
  email: z.string().email().min(3).max(1024),
  pending: z.boolean().optional(),
  first_invoice_paid: z.boolean().optional(),
  started_at: z.string().optional(),
  override_first_period_end_date: z.string().datetime().optional(),
  offering: zOfferingAttributes.optional(),
  features: z
    .array(z.union([zExternalRef, zFeatureAttributes, zUuid]))
    .min(1)
    .optional(),
  plans: z.array(zPlanAttributesAndSelectedMeta).min(1).optional(),
  pricing_options: z
    .array(zPricingOptionAttributesAndSelectedMeta)
    .min(1)
    .optional(),
  configured_features: zOfferingBuildConfiguredFeatures.optional(),
  pricing_option_associations:
    zOfferingBuildPricingOptionAssociationsWritable.optional(),
  selected_plan: zExternalRef.optional(),
  selected_pricing_option: zExternalRef.optional(),
  order: zBuildSubscriptionOrder.optional(),
  meta: zSubscriptionMetaWritable.optional(),
})

export const zImportMetaWritable = z
  .object({
    timestamps: zJobTimestamps,
    records: zImportRecords,
  })
  .readonly()

export const zImportWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionImportType,
  attributes: zImportAttributes,
  meta: zImportMetaWritable,
})

export const zJobMetaWritable = z
  .object({
    timestamps: zJobTimestamps,
    report: zJobReport.optional(),
  })
  .readonly()

export const zJobWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionJobType,
  attributes: zJobResponseAttributes,
  relationships: zRelationships.optional(),
  meta: zJobMetaWritable,
})

export const zSubscriptionInvoiceMetaWritable = z
  .object({
    subscription_id: zUuid.optional(),
    subscriber_id: zUuid.optional(),
    price: zSingleCurrencyPrice.optional(),
    display_price: zDisplayPrice,
    notifications: z.array(zInvoiceNotification).optional(),
    timestamps: zInvoiceTimestamps,
    proration_events: z.array(zProrationEvent).nullable(),
    pro_rata_remaining_value: z.preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int(),
    ),
  })
  .readonly()

export const zSubscriptionInvoiceWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionInvoiceType,
  attributes: zSubscriptionInvoiceAttributes,
  relationships: zRelationships.optional(),
  meta: zSubscriptionInvoiceMetaWritable,
})

export const zSubscriptionInvoicePaymentMetaWritable = z
  .object({
    subscription_id: zUuid,
    invoice_id: zUuid,
    job_id: zUuid,
    timestamps: zInvoicePaymentTimestamps,
    manual_payment: z.boolean(),
  })
  .readonly()

export const zSubscriptionInvoicePaymentWritable = z.object({
  id: zUuid,
  type: zSubscriptionInvoicePaymentType,
  attributes: zSubscriptionInvoicePaymentAttributes,
  meta: zSubscriptionInvoicePaymentMetaWritable,
})

export const zSubscriberMetaWritable = z
  .object({
    feature_entitlements: z.array(zFeatureTag).optional(),
    timestamps: zTimestamps,
  })
  .readonly()

export const zSubscriberAttributesWritable = z.object({
  account_id: zUuid,
  name: z.string().min(3).max(1024),
  email: z.string().email().min(3).max(1024),
  payment_authority: zPaymentAuthorityWritable.optional(),
})

export const zSubscriberResponseAttributesWritable =
  zSubscriberAttributesWritable.and(zTimestamps)

export const zSubscriberWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionSubscriberType,
  attributes: zSubscriberResponseAttributesWritable,
  meta: zSubscriberMetaWritable,
})

export const zSubscriberUpdateAttributesWritable = z.object({
  name: z.string().min(3).max(1024).optional(),
  email: z.string().email().min(3).max(1024).optional(),
  payment_authority: zNullablePaymentAuthorityWritable.optional(),
})

export const zSubscriberCreateWritable = z.object({
  type: zSubscriptionSubscriberType,
  attributes: zSubscriberAttributesWritable,
})

export const zSubscriberUpdateWritable = z.object({
  id: zUuid,
  type: zSubscriptionSubscriberType,
  attributes: zSubscriberUpdateAttributesWritable,
})

export const zScheduleMetaWritable = z
  .object({
    scheduled_for: z.string().datetime().optional(),
    timestamps: zTimestamps,
  })
  .readonly()

export const zScheduleWritable = z.object({
  id: zUuid.optional(),
  type: zSubscriptionScheduleType,
  attributes: zScheduleResponseAttributes,
  meta: zScheduleMetaWritable,
})

/**
 * A comma-separated list of resources to include. See [Characteristics of Include Parameter](/guides/Getting-Started/includes#characteristics-of-include-parameter).
 */
export const zOfferingInclude = z.array(
  z.enum(["plans", "pricing_options", "features"]),
)

/**
 * A comma-separated list of resources to include. See [Characteristics of Include Parameter](/guides/Getting-Started/includes#characteristics-of-include-parameter).
 */
export const zSubscriptionInclude = z.array(
  z.enum(["plans", "pricing_options"]),
)

/**
 * Some Subscriptions API endpoints support filtering. For the general syntax, see [**Filtering**](/guides/Getting-Started/filtering), but you must go to a specific endpoint to understand the attributes and operators an endpoint supports.
 *
 */
export const zFilter = z.string()

/**
 * The current offset by number of records, not pages. Offset is zero-based. The maximum records you can offset is 10,000. If no page size is set, the [page length](/docs/commerce-cloud/global-project-settings/settings-overview#page-length) store setting is used.
 */
export const zPageOffset = z.preprocess(
  (v) => (typeof v === "string" ? Number(v) : v),
  z.number().int().gte(0).lte(10000),
)

/**
 * The maximum number of records per page for this response. You can set this value up to 100. If no page size is set, the [page length](/docs/commerce-cloud/global-project-settings/settings-overview#page-length) store setting is used.
 */
export const zPageLimit = z.preprocess(
  (v) => (typeof v === "string" ? Number(v) : v),
  z.number().int().gte(0),
)

export const zListOfferingsQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
  include: z.array(z.enum(["plans", "pricing_options", "features"])).optional(),
})

/**
 * Success. A list of offerings is returned.
 */
export const zListOfferingsResponse = z.object({
  data: z.array(zOffering).optional(),
  included: zOfferingIncludes.optional(),
  links: zLinks.optional(),
})

export const zCreateOfferingBody = z.object({
  data: zOfferingCreate,
})

/**
 * Success. The offering is created.
 */
export const zCreateOfferingResponse = z.object({
  data: zOffering.optional(),
})

export const zBuildOfferingBody = z.object({
  data: zBuildOffering,
})

/**
 * Success. The new subscription offering is created with the specified subscription plans and pricing options attached to the offering.
 */
export const zBuildOfferingResponse = z.object({
  data: zOffering.optional(),
})

export const zDeleteOfferingPath = z.object({
  offering_uuid: zUuid,
})

/**
 * Success. The subscription offering is removed.
 */
export const zDeleteOfferingResponse = z.void()

export const zGetOfferingPath = z.object({
  offering_uuid: zUuid,
})

export const zGetOfferingQuery = z.object({
  include: z.array(z.enum(["plans", "pricing_options", "features"])).optional(),
})

/**
 * Success. The details of the subscription offering are returned.
 */
export const zGetOfferingResponse = z.object({
  data: zOffering.optional(),
  included: zOfferingIncludes.optional(),
})

export const zUpdateOfferingBody = z.object({
  data: zOfferingUpdate,
})

export const zUpdateOfferingPath = z.object({
  offering_uuid: zUuid,
})

/**
 * Success. The details of the subscription offering are updated.
 */
export const zUpdateOfferingResponse = z.object({
  data: zOffering.optional(),
})

export const zDeleteOfferingFeaturePath = z.object({
  offering_uuid: zUuid,
  feature_uuid: zUuid,
})

/**
 * Success. The subscription feature is removed from the offering.
 */
export const zDeleteOfferingFeatureResponse = z.void()

export const zGetOfferingFeaturePath = z.object({
  offering_uuid: zUuid,
  feature_uuid: zUuid,
})

/**
 * Success. The details of the feature are returned.
 */
export const zGetOfferingFeatureResponse = z.object({
  data: zOfferingFeature.optional(),
})

export const zUpdateOfferingFeatureBody = z.object({
  data: zOfferingFeatureUpdate,
})

export const zUpdateOfferingFeaturePath = z.object({
  offering_uuid: zUuid,
  feature_uuid: zUuid,
})

/**
 * Success. The feature details are updated on the offering.
 */
export const zUpdateOfferingFeatureResponse = z.object({
  data: zFeature.optional(),
})

export const zAttachOfferingFeatureBody = z.object({
  data: zOfferingFeatureAttach,
})

export const zAttachOfferingFeaturePath = z.object({
  offering_uuid: zUuid,
})

/**
 * Success. The subscription feature is attached with the offering.
 */
export const zAttachOfferingFeatureResponse = z.object({
  data: z.array(zOfferingFeature).optional(),
})

export const zListOfferingPricingOptionsPath = z.object({
  offering_uuid: zUuid,
})

export const zListOfferingPricingOptionsQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of pricing options attached with the offering is returned.
 */
export const zListOfferingPricingOptionsResponse = z.object({
  data: z.array(zOfferingPricingOption).optional(),
  links: zLinks.optional(),
})

export const zCreateOfferingPricingOptionBody = z.object({
  data: zOfferingPricingOptionCreate,
})

export const zCreateOfferingPricingOptionPath = z.object({
  offering_uuid: zUuid,
})

/**
 * Success. The pricing option is created.
 */
export const zCreateOfferingPricingOptionResponse = z.object({
  data: zOfferingPricingOption.optional(),
})

export const zDeleteOfferingPricingOptionPath = z.object({
  offering_uuid: zUuid,
  pricing_option_uuid: zUuid,
})

/**
 * Success. The subscription pricing option is no longer associated with the offering.
 */
export const zDeleteOfferingPricingOptionResponse = z.void()

export const zGetOfferingPricingOptionPath = z.object({
  offering_uuid: zUuid,
  pricing_option_uuid: zUuid,
})

/**
 * Success. The details of the pricing option are returned.
 */
export const zGetOfferingPricingOptionResponse = z.object({
  data: zOfferingPricingOption.optional(),
})

export const zUpdateOfferingPricingOptionBody = z.object({
  data: zOfferingPricingOptionUpdate,
})

export const zUpdateOfferingPricingOptionPath = z.object({
  offering_uuid: zUuid,
  pricing_option_uuid: zUuid,
})

/**
 * Success. The pricing option details are updated on the offering.
 */
export const zUpdateOfferingPricingOptionResponse = z.object({
  data: zOfferingPricingOption.optional(),
})

export const zListOfferingFeaturesPath = z.object({
  offering_uuid: zUuid,
})

export const zListOfferingFeaturesQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of subscription features attached to the offering is returned.
 */
export const zListOfferingFeaturesResponse = z.object({
  data: z.array(zOfferingFeature).optional(),
  links: zLinks.optional(),
})

export const zCreateOfferingFeatureBody = z.object({
  data: zOfferingFeatureCreate,
})

export const zCreateOfferingFeaturePath = z.object({
  offering_uuid: zUuid,
})

/**
 * Success. The feature is created.
 */
export const zCreateOfferingFeatureResponse = z.object({
  data: zOfferingFeature.optional(),
})

export const zListOfferingPlansPath = z.object({
  offering_uuid: zUuid,
})

export const zListOfferingPlansQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of subscription plans attached to the offering is returned.
 */
export const zListOfferingPlansResponse = z.object({
  data: z.array(zOfferingPlan).optional(),
  links: zLinks.optional(),
})

export const zCreateOfferingPlanBody = z.object({
  data: zOfferingPlanCreate,
})

export const zCreateOfferingPlanPath = z.object({
  offering_uuid: zUuid,
})

/**
 * Success. The plan is created.
 */
export const zCreateOfferingPlanResponse = z.object({
  data: zOfferingPlan.optional(),
})

export const zDeleteOfferingPlanPath = z.object({
  offering_uuid: zUuid,
  plan_uuid: zUuid,
})

/**
 * Success. The subscription plan is removed from the offering.
 */
export const zDeleteOfferingPlanResponse = z.void()

export const zGetOfferingPlanPath = z.object({
  offering_uuid: zUuid,
  plan_uuid: zUuid,
})

/**
 * Success. The details of the plan are returned.
 */
export const zGetOfferingPlanResponse = z.object({
  data: zOfferingPlan.optional(),
})

export const zUpdateOfferingPlanBody = z.object({
  data: zOfferingPlanUpdate,
})

export const zUpdateOfferingPlanPath = z.object({
  offering_uuid: zUuid,
  plan_uuid: zUuid,
})

/**
 * Success. The plan details are updated on the offering.
 */
export const zUpdateOfferingPlanResponse = z.object({
  data: zOfferingPlan.optional(),
})

export const zRemoveOfferingPlanPricingOptionsBody = zRelationshipsRequest

export const zRemoveOfferingPlanPricingOptionsPath = z.object({
  offering_uuid: zUuid,
  plan_uuid: zUuid,
})

/**
 * Success. The pricing options are added to the plan
 */
export const zRemoveOfferingPlanPricingOptionsResponse = z.object({
  data: z.array(zRelationshipData).optional(),
})

export const zListOfferingPlanPricingOptionsPath = z.object({
  offering_uuid: zUuid,
  plan_uuid: zUuid,
})

/**
 * Success. The pricing option relationships are returned
 */
export const zListOfferingPlanPricingOptionsResponse = z.object({
  data: z.array(zRelationshipData).optional(),
})

export const zAddOfferingPlanPricingOptionsBody = zRelationshipsRequest

export const zAddOfferingPlanPricingOptionsPath = z.object({
  offering_uuid: zUuid,
  plan_uuid: zUuid,
})

/**
 * Success. The pricing options are added to the plan
 */
export const zAddOfferingPlanPricingOptionsResponse = z.object({
  data: z.array(zRelationshipData).optional(),
})

export const zListSubscriptionsQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
  include: z.array(z.enum(["plans", "pricing_options"])).optional(),
})

/**
 * Success. A list of subscriptions is returned.
 */
export const zListSubscriptionsResponse = z.object({
  data: z.array(zSubscription).optional(),
  included: zSubscriptionIncludes.optional(),
  links: zLinks.optional(),
})

export const zCreateSubscriptionBody = z.object({
  data: zBuildSubscriptionWritable,
})

/**
 * Success. The subscription is created.
 */
export const zCreateSubscriptionResponse = z.object({
  data: zSubscription.optional(),
})

export const zDeleteSubscriptionPath = z.object({
  subscription_uuid: zUuid,
})

/**
 * Success. The subscription is removed.
 */
export const zDeleteSubscriptionResponse = z.void()

export const zGetSubscriptionPath = z.object({
  subscription_uuid: zUuid,
})

export const zGetSubscriptionQuery = z.object({
  include: z.array(z.enum(["plans", "pricing_options"])).optional(),
})

/**
 * Success. The details of a subscription are returned.
 */
export const zGetSubscriptionResponse = z.object({
  data: zSubscription.optional(),
  included: zSubscriptionIncludes.optional(),
})

export const zUpdateSubscriptionBody = z.object({
  data: zSubscriptionUpdateWritable,
})

export const zUpdateSubscriptionPath = z.object({
  subscription_uuid: zUuid,
})

/**
 * Success. The subscription is updated.
 */
export const zUpdateSubscriptionResponse = z.object({
  data: zSubscription.optional(),
})

export const zGetSubscriptionFeaturePath = z.object({
  subscription_uuid: zUuid,
  feature_uuid: zUuid,
})

/**
 * Success. The details of the feature are returned.
 */
export const zGetSubscriptionFeatureResponse = z.object({
  data: zOfferingFeature.optional(),
})

export const zGetSubscriptionPlanPath = z.object({
  subscription_uuid: zUuid,
  plan_uuid: zUuid,
})

/**
 * Success. The details of the plan are returned.
 */
export const zGetSubscriptionPlanResponse = z.object({
  data: zOfferingPlan.optional(),
})

export const zGetSubscriptionPricingOptionPath = z.object({
  subscription_uuid: zUuid,
  pricing_option_uuid: zUuid,
})

/**
 * Success. The details of the pricing option are returned.
 */
export const zGetSubscriptionPricingOptionResponse = z.object({
  data: zOfferingPricingOption.optional(),
})

export const zListSubscriptionFeaturesPath = z.object({
  subscription_uuid: zUuid,
})

export const zListSubscriptionFeaturesQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of subscription features is returned.
 */
export const zListSubscriptionFeaturesResponse = z.object({
  data: z.array(zOfferingFeature).optional(),
  links: zLinks.optional(),
})

export const zListSubscriptionPlansPath = z.object({
  subscription_uuid: zUuid,
})

/**
 * Success. A list of subscription plans is returned.
 */
export const zListSubscriptionPlansResponse = z.object({
  data: z.array(zOfferingPlan).optional(),
})

export const zManageSubscriptionPlansBody = z.object({
  data: z.array(zManageSubscriptionPlans),
})

export const zManageSubscriptionPlansPath = z.object({
  subscription_uuid: zUuid,
})

/**
 * Success. The subscription's plans have been updated.
 */
export const zManageSubscriptionPlansResponse = z.void()

export const zListSubscriptionPricingOptionsPath = z.object({
  subscription_uuid: zUuid,
})

/**
 * Success. A list of subscription pricing options is returned.
 */
export const zListSubscriptionPricingOptionsResponse = z.object({
  data: z.array(zOfferingPricingOption).optional(),
})

export const zCreateSubscriptionProrationPreviewBody = z.object({
  data: zProrationPreviewRequest,
})

export const zCreateSubscriptionProrationPreviewPath = z.object({
  subscription_uuid: zUuid,
})

/**
 * Success. The proration preview was computed.
 */
export const zCreateSubscriptionProrationPreviewResponse = z.object({
  data: zProrationPreview.optional(),
})

export const zListSubscriptionStatesPath = z.object({
  subscription_uuid: zUuid,
})

/**
 * Success. A list of subscription states is returned.
 */
export const zListSubscriptionStatesResponse = z.object({
  data: z.array(zSubscriptionState).optional(),
})

export const zCreateSubscriptionStateBody = z.object({
  data: zChangeState,
})

export const zCreateSubscriptionStatePath = z.object({
  subscription_uuid: zUuid,
})

/**
 * Success. The subscription's state has changed.
 */
export const zCreateSubscriptionStateResponse = z.void()

export const zGetSubscriptionStatePath = z.object({
  subscription_uuid: zUuid,
  state_uuid: zUuid,
})

/**
 * Success. A subscription state is returned.
 */
export const zGetSubscriptionStateResponse = z.object({
  data: zSubscriptionState.optional(),
})

export const zListJobsQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of jobs is returned.
 */
export const zListJobsResponse = z.object({
  data: z.array(zJob).optional(),
  links: zLinks.optional(),
})

/**
 * JobCreateJSON
 */
export const zCreateJobBody = z.object({
  data: zJobCreate,
})

/**
 * Success. The job was created.
 */
export const zCreateJobResponse = z.object({
  data: zJob.optional(),
})

export const zDeleteJobPath = z.object({
  job_uuid: zUuid,
})

/**
 * Success. The job was deleted.
 */
export const zDeleteJobResponse = z.void()

export const zGetJobPath = z.object({
  job_uuid: zUuid,
})

/**
 * Success. The job is returned.
 */
export const zGetJobResponse = z.object({
  data: zJob.optional(),
})

export const zListImportJobsQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of import jobs is returned.
 */
export const zListImportJobsResponse = z.object({
  data: z.array(zImport).optional(),
  links: zLinks.optional(),
})

export const zCreateImportBody = z.object({
  external_ref: zExternalRef.optional(),
  import_file: z.string(),
})

/**
 * Success. The import was started.
 */
export const zCreateImportResponse = z.object({
  data: zImport.optional(),
})

export const zGetImportPath = z.object({
  import_uuid: zUuid,
})

export const zGetImportQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. The import is returned.
 */
export const zGetImportResponse = z.object({
  data: zImport.optional(),
})

export const zGetImportErrorsPath = z.object({
  import_uuid: zUuid,
})

export const zGetImportErrorsQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. The import errors are returned.
 */
export const zGetImportErrorsResponse = z.object({
  data: z.array(zSubscriptionImportError).optional(),
  links: zLinks.optional(),
})

export const zListSubscriptionInvoicesPath = z.object({
  subscription_uuid: zUuid,
})

export const zListSubscriptionInvoicesQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of invoices is returned.
 */
export const zListSubscriptionInvoicesResponse = z.object({
  data: z.array(zSubscriptionInvoice).optional(),
  links: zLinks.optional(),
})

export const zListSubscriptionInvoicePaymentsPath = z.object({
  subscription_uuid: zUuid,
  invoice_uuid: zUuid,
})

export const zListSubscriptionInvoicePaymentsQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. Payments for the invoice are returned.
 */
export const zListSubscriptionInvoicePaymentsResponse = z.object({
  data: z.array(zSubscriptionInvoicePayment).optional(),
  links: zLinks.optional(),
})

export const zGetSubscriptionInvoicePaymentPath = z.object({
  subscription_uuid: zUuid,
  invoice_uuid: zUuid,
  payment_uuid: zUuid,
})

/**
 * Success. Specific payment for the invoice is returned.
 */
export const zGetSubscriptionInvoicePaymentResponse = z.object({
  data: zSubscriptionInvoicePayment.optional(),
})

export const zGetSubscriptionInvoicePath = z.object({
  subscription_uuid: zUuid,
  invoice_uuid: zUuid,
})

/**
 * Success. An invoice is returned.
 */
export const zGetSubscriptionInvoiceResponse = z.object({
  data: zSubscriptionInvoice.optional(),
})

export const zListInvoicesQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of invoices is returned.
 */
export const zListInvoicesResponse = z.object({
  data: z.array(zSubscriptionInvoice).optional(),
  links: zLinks.optional(),
})

export const zGetInvoicePath = z.object({
  invoice_uuid: zUuid,
})

/**
 * Success. The details of the invoice are returned.
 */
export const zGetInvoiceResponse = z.object({
  data: zSubscriptionInvoice.optional(),
})

export const zListInvoicePaymentsPath = z.object({
  invoice_uuid: zUuid,
})

export const zListInvoicePaymentsQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. Payments for the invoice are returned
 */
export const zListInvoicePaymentsResponse = z.object({
  data: z.array(zSubscriptionInvoicePayment).optional(),
  links: zLinks.optional(),
})

export const zGetInvoicePaymentPath = z.object({
  invoice_uuid: zUuid,
  payment_uuid: zUuid,
})

/**
 * Success. Specific payment for the invoice is returned
 */
export const zGetInvoicePaymentResponse = z.object({
  data: zSubscriptionInvoicePayment.optional(),
})

export const zUpdateInvoicePaymentBody = z.object({
  data: zUpdateInvoicePayment,
})

export const zUpdateInvoicePaymentPath = z.object({
  invoice_uuid: zUuid,
  payment_uuid: zUuid,
})

/**
 * Success. Invoice payment has been updated.
 */
export const zUpdateInvoicePaymentResponse = z.object({
  data: zSubscriptionInvoicePayment,
})

export const zListInvoicePaymentRefundsPath = z.object({
  invoice_uuid: zUuid,
  payment_uuid: zUuid,
})

export const zListInvoicePaymentRefundsQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. Refunds for an invoice payment are returned.
 */
export const zListInvoicePaymentRefundsResponse = z.object({
  data: z.array(zSubscriptionInvoicePaymentRefund).optional(),
  links: zLinks.optional(),
})

export const zCreateInvoicePaymentRefundBody = z.object({
  data: zCreateInvoicePaymentRefund,
})

export const zCreateInvoicePaymentRefundPath = z.object({
  invoice_uuid: zUuid,
  payment_uuid: zUuid,
})

/**
 * Success. The payment refund is completed.
 */
export const zCreateInvoicePaymentRefundResponse = z.object({
  data: zSubscriptionInvoicePaymentRefund,
})

export const zGetInvoicePaymentRefundPath = z.object({
  invoice_uuid: zUuid,
  payment_uuid: zUuid,
  refund_uuid: zUuid,
})

/**
 * Success. Specific refund for the invoice payment is returned
 */
export const zGetInvoicePaymentRefundResponse = z.object({
  data: zSubscriptionInvoicePaymentRefund,
})

export const zListSchedulesQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of schedules is returned.
 */
export const zListSchedulesResponse = z.object({
  data: z.array(zSchedule).optional(),
  links: zLinks.optional(),
})

export const zCreateScheduleBody = z.object({
  data: zScheduleCreate,
})

/**
 * Success. The schedule is created.
 */
export const zCreateScheduleResponse = z.object({
  data: zSchedule.optional(),
})

export const zDeleteSchedulePath = z.object({
  schedule_uuid: zUuid,
})

/**
 * Success. The schedule is removed.
 */
export const zDeleteScheduleResponse = z.void()

export const zGetSchedulePath = z.object({
  schedule_uuid: zUuid,
})

/**
 * Success. A schedule is returned.
 */
export const zGetScheduleResponse = z.object({
  data: zSchedule.optional(),
})

export const zUpdateScheduleBody = z.object({
  data: zScheduleUpdate,
})

export const zUpdateSchedulePath = z.object({
  schedule_uuid: zUuid,
})

/**
 * Success. The schedule details are returned.
 */
export const zUpdateScheduleResponse = z.object({
  data: zSchedule.optional(),
})

export const zListSubscribersQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of subscribers is returned.
 */
export const zListSubscribersResponse = z.object({
  data: z.array(zSubscriber).optional(),
  links: zLinks.optional(),
})

export const zCreateSubscriberBody = z.object({
  data: zSubscriberCreateWritable,
})

/**
 * Success. The subscriber is created.
 */
export const zCreateSubscriberResponse = z.object({
  data: zSubscriber.optional(),
})

export const zDeleteSubscriberPath = z.object({
  subscriber_uuid: zUuid,
})

/**
 * Success. The subscriber is removed.
 */
export const zDeleteSubscriberResponse = z.void()

export const zGetSubscriberPath = z.object({
  subscriber_uuid: zUuid,
})

/**
 * Success. A subscriber is returned.
 */
export const zGetSubscriberResponse = z.object({
  data: zSubscriber.optional(),
})

export const zUpdateSubscriberBody = z.object({
  data: zSubscriberUpdateWritable,
})

export const zUpdateSubscriberPath = z.object({
  subscriber_uuid: zUuid,
})

/**
 * Success. The subscriber details are returned.
 */
export const zUpdateSubscriberResponse = z.object({
  data: zSubscriber.optional(),
})

export const zListDunningRulesQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of dunning rules is returned.
 */
export const zListDunningRulesResponse = z.object({
  data: z.array(zDunningRule).optional(),
  links: zLinks.optional(),
})

export const zCreateDunningRuleBody = z.object({
  data: zDunningRuleCreate,
})

/**
 * Success. The dunning rule set is created.
 */
export const zCreateDunningRuleResponse = z.object({
  data: zDunningRule.optional(),
})

export const zDeleteDunningRulePath = z.object({
  dunning_rule_uuid: zUuid,
})

/**
 * Success. The dunning rule is removed.
 */
export const zDeleteDunningRuleResponse = z.void()

export const zGetDunningRulePath = z.object({
  dunning_rule_uuid: zUuid,
})

/**
 * Success. The dunning rule details are returned.
 */
export const zGetDunningRuleResponse = z.object({
  data: zDunningRule.optional(),
})

export const zUpdateDunningRuleBody = z.object({
  data: zDunningRuleUpdate,
})

export const zUpdateDunningRulePath = z.object({
  dunning_rule_uuid: zUuid,
})

/**
 * Success. The dunning rule set has been updated.
 */
export const zUpdateDunningRuleResponse = z.object({
  data: zDunningRule.optional(),
})

export const zListProrationPoliciesQuery = z.object({
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of proration policies is returned.
 */
export const zListProrationPoliciesResponse = z.object({
  data: z.array(zProrationPolicy).optional(),
  links: zLinks.optional(),
})

export const zCreateProrationPolicyBody = z.object({
  data: zProrationPolicyCreate,
})

/**
 * Success. The proration policy is created.
 */
export const zCreateProrationPolicyResponse = z.object({
  data: zProrationPolicy.optional(),
})

export const zDeleteProrationPolicyPath = z.object({
  proration_policy_uuid: zUuid,
})

/**
 * Success. The proration policy details are removed.
 */
export const zDeleteProrationPolicyResponse = z.void()

export const zGetProrationPolicyPath = z.object({
  proration_policy_uuid: zUuid,
})

/**
 * Success. The proration policy details are returned.
 */
export const zGetProrationPolicyResponse = z.object({
  data: zProrationPolicy.optional(),
})

export const zUpdateProrationPolicyBody = z.object({
  data: zProrationPolicyUpdate,
})

export const zUpdateProrationPolicyPath = z.object({
  proration_policy_uuid: zUuid,
})

/**
 * Success. The proration policy details are updated.
 */
export const zUpdateProrationPolicyResponse = z.object({
  data: zProrationPolicy.optional(),
})

export const zListFeaturesQuery = z.object({
  filter: z.string().optional(),
  "page[offset]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0).lte(10000),
    )
    .optional(),
  "page[limit]": z
    .preprocess(
      (v) => (typeof v === "string" ? Number(v) : v),
      z.number().int().gte(0),
    )
    .optional(),
})

/**
 * Success. A list of features is returned.
 */
export const zListFeaturesResponse = z.object({
  data: z.array(zFeature).optional(),
  links: zLinks.optional(),
})

export const zCreateFeatureBody = z.object({
  data: zFeatureCreate,
})

/**
 * Success. The feature is created.
 */
export const zCreateFeatureResponse = z.object({
  data: zFeature.optional(),
})

export const zDeleteFeaturePath = z.object({
  feature_uuid: zUuid,
})

/**
 * Success. The feature is removed.
 */
export const zDeleteFeatureResponse = z.void()

export const zGetFeaturePath = z.object({
  feature_uuid: zUuid,
})

/**
 * Success. The feature details are returned.
 */
export const zGetFeatureResponse = z.object({
  data: zFeature.optional(),
})

export const zUpdateFeatureBody = z.object({
  data: zFeatureUpdate,
})

export const zUpdateFeaturePath = z.object({
  feature_uuid: zUuid,
})

/**
 * Success. The feature details are updated.
 */
export const zUpdateFeatureResponse = z.object({
  data: zFeature.optional(),
})
