// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  CreateIntegrationData,
  CreateIntegrationErrors,
  CreateIntegrationResponses,
  DeleteIntegrationData,
  DeleteIntegrationErrors,
  DeleteIntegrationResponses,
  GetIntegrationData,
  GetIntegrationErrors,
  GetIntegrationResponses,
  ListIntegrationJobsData,
  ListIntegrationJobsErrors,
  ListIntegrationJobsResponses,
  ListIntegrationLogsData,
  ListIntegrationLogsErrors,
  ListIntegrationLogsResponses,
  ListIntegrationsData,
  ListIntegrationsErrors,
  ListIntegrationsResponses,
  ListJobLogsData,
  ListJobLogsErrors,
  ListJobLogsResponses,
  ListStoreLogsData,
  ListStoreLogsErrors,
  ListStoreLogsResponses,
  UpdateIntegrationData,
  UpdateIntegrationErrors,
  UpdateIntegrationResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * List integrations
 *
 * Returns a list of all integrations created by the store.
 */
export const listIntegrations = <ThrowOnError extends boolean = false>(
  options?: Options<ListIntegrationsData, ThrowOnError>,
): RequestResult<
  ListIntegrationsResponses,
  ListIntegrationsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListIntegrationsResponses,
    ListIntegrationsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations",
    ...options,
  })

/**
 * Create an integration
 *
 * Create an integration.
 */
export const createIntegration = <ThrowOnError extends boolean = false>(
  options?: Options<CreateIntegrationData, ThrowOnError>,
): RequestResult<
  CreateIntegrationResponses,
  CreateIntegrationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CreateIntegrationResponses,
    CreateIntegrationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete an integration
 *
 * Deletes the Integration for the given UUID
 */
export const deleteIntegration = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIntegrationData, ThrowOnError>,
): RequestResult<
  DeleteIntegrationResponses,
  DeleteIntegrationErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteIntegrationResponses,
    DeleteIntegrationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations/{integration_uuid}",
    ...options,
  })

/**
 * Get an integration
 *
 * Returns the integration for the given UUID.
 */
export const getIntegration = <ThrowOnError extends boolean = false>(
  options: Options<GetIntegrationData, ThrowOnError>,
): RequestResult<GetIntegrationResponses, GetIntegrationErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetIntegrationResponses,
    GetIntegrationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations/{integration_uuid}",
    ...options,
  })

/**
 * Update an integration
 *
 * Updates the Integration for the given UUID. Specify whichever attributes you want to change. The values of the other attributes remain the same. If the attributes section is empty, the integration is not updated.
 */
export const updateIntegration = <ThrowOnError extends boolean = false>(
  options: Options<UpdateIntegrationData, ThrowOnError>,
): RequestResult<
  UpdateIntegrationResponses,
  UpdateIntegrationErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateIntegrationResponses,
    UpdateIntegrationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations/{integration_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List logs for all integrations for the store
 *
 * Returns all integration logs for the store.
 */
export const listStoreLogs = <ThrowOnError extends boolean = false>(
  options?: Options<ListStoreLogsData, ThrowOnError>,
): RequestResult<ListStoreLogsResponses, ListStoreLogsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListStoreLogsResponses,
    ListStoreLogsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations/logs",
    ...options,
  })

/**
 * List logs for integration
 *
 * Returns the logs for the given integration UUID.
 */
export const listIntegrationLogs = <ThrowOnError extends boolean = false>(
  options: Options<ListIntegrationLogsData, ThrowOnError>,
): RequestResult<
  ListIntegrationLogsResponses,
  ListIntegrationLogsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListIntegrationLogsResponses,
    ListIntegrationLogsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations/{integration_uuid}/logs",
    ...options,
  })

/**
 * List jobs for integration
 *
 * Returns the jobs for the given integration UUID.
 */
export const listIntegrationJobs = <ThrowOnError extends boolean = false>(
  options: Options<ListIntegrationJobsData, ThrowOnError>,
): RequestResult<
  ListIntegrationJobsResponses,
  ListIntegrationJobsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListIntegrationJobsResponses,
    ListIntegrationJobsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations/{integration_uuid}/jobs",
    ...options,
  })

/**
 * List logs for the job
 *
 * Returns the integration logs for the given integration and job UUID.
 */
export const listJobLogs = <ThrowOnError extends boolean = false>(
  options: Options<ListJobLogsData, ThrowOnError>,
): RequestResult<ListJobLogsResponses, ListJobLogsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListJobLogsResponses,
    ListJobLogsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/integrations/{integration_uuid}/jobs/{job_uuid}/logs",
    ...options,
  })
