// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  AddAccountTagsOnAccountData,
  AddAccountTagsOnAccountErrors,
  AddAccountTagsOnAccountResponses,
  CreateAnAccountTagData,
  CreateAnAccountTagErrors,
  CreateAnAccountTagResponses,
  DeleteAnAccountTagData,
  DeleteAnAccountTagErrors,
  DeleteAnAccountTagResponses,
  DeleteV2AccountsAccountIdAccountMembershipsMembershipIdData,
  DeleteV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
  DeleteV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
  DeleteV2AccountsAccountIdData,
  DeleteV2AccountsAccountIdErrors,
  DeleteV2AccountsAccountIdResponses,
  GetAnAccountTagData,
  GetAnAccountTagErrors,
  GetAnAccountTagResponses,
  GetAnAccountTagsRelationshipData,
  GetAnAccountTagsRelationshipErrors,
  GetAnAccountTagsRelationshipResponses,
  GetV2AccountMembersAccountMemberIdAccountMembershipsData,
  GetV2AccountMembersAccountMemberIdAccountMembershipsErrors,
  GetV2AccountMembersAccountMemberIdAccountMembershipsResponses,
  GetV2AccountMembersAccountMemberIdData,
  GetV2AccountMembersAccountMemberIdErrors,
  GetV2AccountMembersAccountMemberIdResponses,
  GetV2AccountMembersData,
  GetV2AccountMembersErrors,
  GetV2AccountMembersResponses,
  GetV2AccountsAccountIdAccountMembershipsData,
  GetV2AccountsAccountIdAccountMembershipsErrors,
  GetV2AccountsAccountIdAccountMembershipsMembershipIdData,
  GetV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
  GetV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
  GetV2AccountsAccountIdAccountMembershipsResponses,
  GetV2AccountsAccountIdAccountMembershipsUnassignedAccountMembersData,
  GetV2AccountsAccountIdAccountMembershipsUnassignedAccountMembersErrors,
  GetV2AccountsAccountIdAccountMembershipsUnassignedAccountMembersResponses,
  GetV2AccountsAccountIdData,
  GetV2AccountsAccountIdErrors,
  GetV2AccountsAccountIdResponses,
  GetV2AccountsData,
  GetV2AccountsErrors,
  GetV2AccountsResponses,
  GetV2SettingsAccountAuthenticationData,
  GetV2SettingsAccountAuthenticationErrors,
  GetV2SettingsAccountAuthenticationResponses,
  GetV2SettingsAccountMembershipData,
  GetV2SettingsAccountMembershipErrors,
  GetV2SettingsAccountMembershipResponses,
  ListAccountTagsData,
  ListAccountTagsErrors,
  ListAccountTagsResponses,
  PostV2AccountMembersTokensData,
  PostV2AccountMembersTokensErrors,
  PostV2AccountMembersTokensResponses,
  PostV2AccountsAccountIdAccountMembershipsData,
  PostV2AccountsAccountIdAccountMembershipsErrors,
  PostV2AccountsAccountIdAccountMembershipsResponses,
  PostV2AccountsData,
  PostV2AccountsErrors,
  PostV2AccountsResponses,
  PutV2AccountMembersAccountMemberIdData,
  PutV2AccountMembersAccountMemberIdErrors,
  PutV2AccountMembersAccountMemberIdResponses,
  PutV2AccountsAccountIdAccountMembershipsMembershipIdData,
  PutV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
  PutV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
  PutV2AccountsAccountIdData,
  PutV2AccountsAccountIdErrors,
  PutV2AccountsAccountIdResponses,
  PutV2SettingsAccountAuthenticationData,
  PutV2SettingsAccountAuthenticationErrors,
  PutV2SettingsAccountAuthenticationResponses,
  PutV2SettingsAccountMembershipData,
  PutV2SettingsAccountMembershipErrors,
  PutV2SettingsAccountMembershipResponses,
  RemoveAccountTagsOnAccountData,
  RemoveAccountTagsOnAccountErrors,
  RemoveAccountTagsOnAccountResponses,
  UpdateAnAccountTagData,
  UpdateAnAccountTagErrors,
  UpdateAnAccountTagResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Get All Accounts
 *
 * Use this endpoint to Get all accounts.
 *
 * You can use pagination with this resource. For more information, see [pagination](/guides/Getting-Started/pagination).
 *
 * ### Filtering
 * The following operators and attributes are available for [filtering](/guides/Getting-Started/filtering) accounts:
 *
 * | Attribute         | Operators                     | Example                                                       |
 * |-------------------|-------------------------------|---------------------------------------------------------------|
 * | `id`              | `lt`,`le`,`eq`,`gt`,`ge`,`in` | `eq(id,3fa85f64-5717-4562-b3fc-2c963f66afa6)`                 |
 * | `created_at`      | `lt`,`le`,`eq`,`gt`,`ge`      | `ge(created_at,2024-04-29T00:00:00.000Z)`                     |
 * | `updated_at`      | `lt`,`le`,`eq`,`gt`,`ge`      | `le(updated_at,2024-04-29T00:00:00.000Z)`                     |
 * | `name`            | `eq`,`like`                   | `like(name,*swan*)`                                           |
 * | `legal_name`      | `eq`,`like`                   | `like(legal_name,*swan*)`                                     |
 * | `registration_id` | `eq`,`like`                   | `like(registration_id,00000000-0000-1000-8000-*)`             |
 * | `external_ref`    | `eq`,`like`,`in`              | `like(external_ref,16be*)`                                    |
 * | `account_tags`    | `contains`                    | `contains(account_tags,26beb787-be6e-40c3-bbae-9c645820b075)` |
 *
 */
export const getV2Accounts = <ThrowOnError extends boolean = false>(
  options?: Options<GetV2AccountsData, ThrowOnError>,
): RequestResult<GetV2AccountsResponses, GetV2AccountsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetV2AccountsResponses,
    GetV2AccountsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts",
    ...options,
  })

/**
 * Create an Account
 *
 * With the account creation endpoint, you have the ability to create accounts which can optionally have another account as a parent.
 */
export const postV2Accounts = <ThrowOnError extends boolean = false>(
  options?: Options<PostV2AccountsData, ThrowOnError>,
): RequestResult<PostV2AccountsResponses, PostV2AccountsErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    PostV2AccountsResponses,
    PostV2AccountsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete an Account
 *
 * Delete a specific account within a store
 */
export const deleteV2AccountsAccountId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV2AccountsAccountIdData, ThrowOnError>,
): RequestResult<
  DeleteV2AccountsAccountIdResponses,
  DeleteV2AccountsAccountIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteV2AccountsAccountIdResponses,
    DeleteV2AccountsAccountIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}",
    ...options,
  })

/**
 * Get an Account
 *
 * View a specific account contained within your store
 */
export const getV2AccountsAccountId = <ThrowOnError extends boolean = false>(
  options: Options<GetV2AccountsAccountIdData, ThrowOnError>,
): RequestResult<
  GetV2AccountsAccountIdResponses,
  GetV2AccountsAccountIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetV2AccountsAccountIdResponses,
    GetV2AccountsAccountIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}",
    ...options,
  })

/**
 * Update an Account
 *
 * Update the information contained on an account.
 */
export const putV2AccountsAccountId = <ThrowOnError extends boolean = false>(
  options: Options<PutV2AccountsAccountIdData, ThrowOnError>,
): RequestResult<
  PutV2AccountsAccountIdResponses,
  PutV2AccountsAccountIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutV2AccountsAccountIdResponses,
    PutV2AccountsAccountIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Remove Account Tags
 *
 * Remove Account Tags from an Account. Please note that after removing a tag from an account, the account member token should be regenerated to reflect the updated status, allowing other services to react accordingly. See [Account Management Authentication Token](/docs/api/accounts/post-v-2-account-members-tokens).
 */
export const removeAccountTagsOnAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoveAccountTagsOnAccountData, ThrowOnError>,
): RequestResult<
  RemoveAccountTagsOnAccountResponses,
  RemoveAccountTagsOnAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    RemoveAccountTagsOnAccountResponses,
    RemoveAccountTagsOnAccountErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}/relationships/account-tags",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get an Account's Tags Relationship
 *
 * Get a list of Account Tags on an Account
 */
export const getAnAccountTagsRelationship = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAnAccountTagsRelationshipData, ThrowOnError>,
): RequestResult<
  GetAnAccountTagsRelationshipResponses,
  GetAnAccountTagsRelationshipErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAnAccountTagsRelationshipResponses,
    GetAnAccountTagsRelationshipErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}/relationships/account-tags",
    ...options,
  })

/**
 * Add Account Tags
 *
 * Add Account Tags onto an Account. Please note that after adding a tag to an account, the account member token should be regenerated to reflect the updated account status, allowing other services to react accordingly. See [Account Management Authentication Token](/docs/api/accounts/post-v-2-account-members-tokens).
 */
export const addAccountTagsOnAccount = <ThrowOnError extends boolean = false>(
  options: Options<AddAccountTagsOnAccountData, ThrowOnError>,
): RequestResult<
  AddAccountTagsOnAccountResponses,
  AddAccountTagsOnAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AddAccountTagsOnAccountResponses,
    AddAccountTagsOnAccountErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}/relationships/account-tags",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get all Account Members
 *
 * Get all account members contained within your store.
 *
 * ### Filtering
 *
 *
 * The following operators and attributes are available for
 * [filtering](/guides/Getting-Started/filtering) account members.
 *
 * | Attribute | Type | Operator | Example | | :--- | :--- | :--- | :--- | | `email`       | `string` | `ilike`           | `ilike(email,'ronswanson@example.com')` | | `name`        | `string` | `ilike`           | `ilike(name,'*swan*')`                  | | `given_name`  | `string` | `ilike`/`is_null` | `ilike(given_name,'ron*')`              | | `middle_name` | `string` | `ilike`/`is_null` | `is_null(middle_name)`                  | | `family_name` | `string` | `ilike`/`is_null` | `is_null(family_name)`                  |
 *
 */
export const getV2AccountMembers = <ThrowOnError extends boolean = false>(
  options?: Options<GetV2AccountMembersData, ThrowOnError>,
): RequestResult<
  GetV2AccountMembersResponses,
  GetV2AccountMembersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetV2AccountMembersResponses,
    GetV2AccountMembersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-members",
    ...options,
  })

/**
 * Get an Account Member
 *
 * Get an account member from your store
 */
export const getV2AccountMembersAccountMemberId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetV2AccountMembersAccountMemberIdData, ThrowOnError>,
): RequestResult<
  GetV2AccountMembersAccountMemberIdResponses,
  GetV2AccountMembersAccountMemberIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetV2AccountMembersAccountMemberIdResponses,
    GetV2AccountMembersAccountMemberIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-members/{accountMemberID}",
    ...options,
  })

/**
 * Update an account member
 *
 * This endpoint can be used to update an account member.
 */
export const putV2AccountMembersAccountMemberId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutV2AccountMembersAccountMemberIdData, ThrowOnError>,
): RequestResult<
  PutV2AccountMembersAccountMemberIdResponses,
  PutV2AccountMembersAccountMemberIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutV2AccountMembersAccountMemberIdResponses,
    PutV2AccountMembersAccountMemberIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-members/{accountMemberID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get all Account Memberships
 *
 * You can also use `include=account_member` to retrieve details about the account members associated with the account memberships. With this option, you can get more information about the account members such as name and email in a single request. For more information see [including resources](/guides/Getting-Started/includes).
 *
 * ### Filtering
 *
 * The following operators and attributes are available for [filtering](/guides/Getting-Started/filtering) account memberships.
 *
 * | Operator | Description |
 * | :--- | :--- |
 * | `eq` | Checks whether the values of two operands are equal. If the values are equal, the condition is true. |
 * | `like` | Checks if the operand contains the specified string. You can use wildcard characters in operand. |
 *
 * | Attribute | Type | Operator | Example |
 * | :--- | :--- | :--- | :--- |
 * | `account_member_id` | `string` | `eq` / `like` | `eq(account_member_id,00000000-0000-1000-8000-0000000)` |
 */
export const getV2AccountsAccountIdAccountMemberships = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetV2AccountsAccountIdAccountMembershipsData, ThrowOnError>,
): RequestResult<
  GetV2AccountsAccountIdAccountMembershipsResponses,
  GetV2AccountsAccountIdAccountMembershipsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetV2AccountsAccountIdAccountMembershipsResponses,
    GetV2AccountsAccountIdAccountMembershipsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}/account-memberships",
    ...options,
  })

/**
 * Create an Account Membership
 *
 * :::caution
 *
 * You can only create up to 1000 account memberships in an account.
 *
 * :::
 *
 */
export const postV2AccountsAccountIdAccountMemberships = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostV2AccountsAccountIdAccountMembershipsData, ThrowOnError>,
): RequestResult<
  PostV2AccountsAccountIdAccountMembershipsResponses,
  PostV2AccountsAccountIdAccountMembershipsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostV2AccountsAccountIdAccountMembershipsResponses,
    PostV2AccountsAccountIdAccountMembershipsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}/account-memberships",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get a List of Account Memberships of Account Member
 *
 * You can also use `include=account` to retrieve details about the accounts associated with the account memberships. For more information see [including resources](/guides/Getting-Started/includes).
 *
 * You can use pagination with this resource. For more information, see [pagination](/guides/Getting-Started/pagination).
 *
 * ### Filtering
 *
 * The following operators and attributes are available for [filtering](/guides/Getting-Started/filtering) account memberships.
 *
 * | Operator | Description |
 * | :--- | :--- |
 * | `eq` | Checks whether the values of two operands are equal. If the values are equal, the condition is true. |
 * | `like` | Checks if the operand contains the specified string. You can use wildcard characters in operand. |
 *
 * | Attribute | Type | Operator | Example |
 * | :--- | :--- | :--- | :--- |
 * | `account_member_id` | `string` | `eq` / `like` | `eq(account_member_id,00000000-0000-1000-8000-0000000)` |
 *
 */
export const getV2AccountMembersAccountMemberIdAccountMemberships = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetV2AccountMembersAccountMemberIdAccountMembershipsData,
    ThrowOnError
  >,
): RequestResult<
  GetV2AccountMembersAccountMemberIdAccountMembershipsResponses,
  GetV2AccountMembersAccountMemberIdAccountMembershipsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetV2AccountMembersAccountMemberIdAccountMembershipsResponses,
    GetV2AccountMembersAccountMemberIdAccountMembershipsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-members/{accountMemberId}/account-memberships",
    ...options,
  })

/**
 * Get a List of Unassigned Account Members
 *
 * Use this resource to get a list of all account members that are not assigned to an account.
 *
 * ### Filtering
 *
 * The following operators and attributes are available for [filtering](/guides/Getting-Started/filtering) unassigned account members.
 *
 * | Operator | Description   |
 * | :------- | :--------------------------------------------------------------------------------------------------- |
 * | `eq`     | Checks whether the values of two operands are equal. If the values are equal, the condition is true. |
 * | `like`   | Checks if the operand contains the specified string. You can use wildcard characters in operand.     |
 *
 * | Attribute | Type     | Operator      | Example |
 * | :-------- | :------- | :------------ | :--------------------------------- |
 * | `email`   | `string` | `eq` / `like` | `eq(email,ronswanson@example.com)` |
 * | `name`    | `string` | `eq` / `like` | `like(name,*swan*)` |
 *
 * :::note
 *
 * You can use pagination with this resource. For more information, see [pagination](/guides/Getting-Started/pagination).
 *
 * :::
 */
export const getV2AccountsAccountIdAccountMembershipsUnassignedAccountMembers =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetV2AccountsAccountIdAccountMembershipsUnassignedAccountMembersData,
      ThrowOnError
    >,
  ): RequestResult<
    GetV2AccountsAccountIdAccountMembershipsUnassignedAccountMembersResponses,
    GetV2AccountsAccountIdAccountMembershipsUnassignedAccountMembersErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      GetV2AccountsAccountIdAccountMembershipsUnassignedAccountMembersResponses,
      GetV2AccountsAccountIdAccountMembershipsUnassignedAccountMembersErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v2/accounts/{accountID}/account-memberships/unassigned-account-members",
      ...options,
    })

/**
 * Delete an Account Membership
 *
 * Delete a membership from an account
 */
export const deleteV2AccountsAccountIdAccountMembershipsMembershipId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteV2AccountsAccountIdAccountMembershipsMembershipIdData,
    ThrowOnError
  >,
): RequestResult<
  DeleteV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
  DeleteV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
    DeleteV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}/account-memberships/{membershipID}",
    ...options,
  })

/**
 * Get an Account Membership
 *
 * Get an account membership from an account in your store.
 *
 * You can also use `include=account_member` to retrieve details about the account member associated with this account membership. With this option, you can get more information about the account member such as name and email in a single request. For more information see [including resources](/guides/Getting-Started/includes).
 *
 */
export const getV2AccountsAccountIdAccountMembershipsMembershipId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetV2AccountsAccountIdAccountMembershipsMembershipIdData,
    ThrowOnError
  >,
): RequestResult<
  GetV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
  GetV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
    GetV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}/account-memberships/{membershipID}",
    ...options,
  })

/**
 * Update an Account Membership
 *
 * You can update and extend an account member details using [core flows](/docs/api/flows/flows#extend-an-existing-resource). However, you cannot update the `account_member_id` of an account member.
 */
export const putV2AccountsAccountIdAccountMembershipsMembershipId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutV2AccountsAccountIdAccountMembershipsMembershipIdData,
    ThrowOnError
  >,
): RequestResult<
  PutV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
  PutV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutV2AccountsAccountIdAccountMembershipsMembershipIdResponses,
    PutV2AccountsAccountIdAccountMembershipsMembershipIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/accounts/{accountID}/account-memberships/{membershipID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get Account Membership Settings
 *
 * Use this endpoint to get all account membership settings.
 */
export const getV2SettingsAccountMembership = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetV2SettingsAccountMembershipData, ThrowOnError>,
): RequestResult<
  GetV2SettingsAccountMembershipResponses,
  GetV2SettingsAccountMembershipErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetV2SettingsAccountMembershipResponses,
    GetV2SettingsAccountMembershipErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/settings/account-membership",
    ...options,
  })

/**
 * Update Account Membership Settings
 *
 * Use this endpoint to update account membership settings.
 */
export const putV2SettingsAccountMembership = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PutV2SettingsAccountMembershipData, ThrowOnError>,
): RequestResult<
  PutV2SettingsAccountMembershipResponses,
  PutV2SettingsAccountMembershipErrors,
  ThrowOnError
> =>
  (options?.client ?? client).put<
    PutV2SettingsAccountMembershipResponses,
    PutV2SettingsAccountMembershipErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/settings/account-membership",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Get Account Authentication Settings
 *
 * Use this endpoint to view account authentication settings
 */
export const getV2SettingsAccountAuthentication = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetV2SettingsAccountAuthenticationData, ThrowOnError>,
): RequestResult<
  GetV2SettingsAccountAuthenticationResponses,
  GetV2SettingsAccountAuthenticationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetV2SettingsAccountAuthenticationResponses,
    GetV2SettingsAccountAuthenticationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/settings/account-authentication",
    ...options,
  })

/**
 * Update Account Authentication Settings
 *
 * Use this endpoint to update account authentication settings
 */
export const putV2SettingsAccountAuthentication = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PutV2SettingsAccountAuthenticationData, ThrowOnError>,
): RequestResult<
  PutV2SettingsAccountAuthenticationResponses,
  PutV2SettingsAccountAuthenticationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).put<
    PutV2SettingsAccountAuthenticationResponses,
    PutV2SettingsAccountAuthenticationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/settings/account-authentication",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Generate an Account Management Authentication Token
 *
 * Commerce provides authentication tokens for anyone using the Account Management APIs, including accounts and account members.
 *
 * For each element in the list returned by the account member authentication API, a token value is returned. In order for a shopper to authenticate as the account, this value should be set as the `EP-Account-Management-Authentication-Token` header when calling Commerce. This header grants access to additional resources associated with the account, such as [carts](/docs/api/carts/account-cart-associations), [orders](/docs/api/carts/orders), [catalogs with associated rules](/docs/api/pxm/catalog/rules), and [addresses](/docs/api/addresses/addresses-introduction).
 *
 * The set of permissions available to a shopper using an Account Management Authentication token is documented in [Permissions](/docs/authentication/tokens/permissions)
 *
 * Commerce provides authentication tokens for an account and an account member using:
 *
 * - OpenID Connect
 * - Username and password
 * - Self signup
 * - One-time password token
 * - Switch account token
 *
 */
export const postV2AccountMembersTokens = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostV2AccountMembersTokensData, ThrowOnError>,
): RequestResult<
  PostV2AccountMembersTokensResponses,
  PostV2AccountMembersTokensErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PostV2AccountMembersTokensResponses,
    PostV2AccountMembersTokensErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-members/tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * List Account Tags
 *
 * Retrieves a list of Account Tags
 *
 * ## Filtering
 * The following operators and attributes are available for [filtering](/guides/Getting-Started/filtering) Account Tags:
 *
 * | Attribute        | Operators                     | Example                                       |
 * |------------------|-------------------------------|-----------------------------------------------|
 * | `id`             | `lt`,`le`,`eq`,`gt`,`ge`,`in` | `eq(id,3fa85f64-5717-4562-b3fc-2c963f66afa6)` |
 * | `created_at`     | `lt`,`le`,`eq`,`gt`,`ge`      | `ge(created_at,2024-04-29T00:00:00.000Z)`     |
 * | `updated_at`     | `lt`,`le`,`eq`,`gt`,`ge`      | `le(updated_at,2024-04-29T00:00:00.000Z)`     |
 * | `name`           | `eq`,`like`                   | `eq(name,AccountName)`                        |
 *
 * ## Sorting
 * The following attributes are available for sorting. When specified, the results are sorted in ascending order based on the value of the field. To sort in descending order, prefix the attribute with `-`, for example, `-updated_at`. The default sort order is `created_at` in descending order.
 * - `id`
 * - `created_at`
 * - `updated_at`
 * - `name`
 *
 */
export const listAccountTags = <ThrowOnError extends boolean = false>(
  options?: Options<ListAccountTagsData, ThrowOnError>,
): RequestResult<
  ListAccountTagsResponses,
  ListAccountTagsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListAccountTagsResponses,
    ListAccountTagsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-tags",
    ...options,
  })

/**
 * Create an Account Tag
 *
 * Create an Account Tag
 */
export const createAnAccountTag = <ThrowOnError extends boolean = false>(
  options?: Options<CreateAnAccountTagData, ThrowOnError>,
): RequestResult<
  CreateAnAccountTagResponses,
  CreateAnAccountTagErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CreateAnAccountTagResponses,
    CreateAnAccountTagErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-tags",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete an Account Tag
 *
 * Delete an Account Tag
 */
export const deleteAnAccountTag = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAnAccountTagData, ThrowOnError>,
): RequestResult<
  DeleteAnAccountTagResponses,
  DeleteAnAccountTagErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteAnAccountTagResponses,
    DeleteAnAccountTagErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-tags/{tag_id}",
    ...options,
  })

/**
 * Get an Account Tag
 *
 * Get an Account Tag
 */
export const getAnAccountTag = <ThrowOnError extends boolean = false>(
  options: Options<GetAnAccountTagData, ThrowOnError>,
): RequestResult<
  GetAnAccountTagResponses,
  GetAnAccountTagErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAnAccountTagResponses,
    GetAnAccountTagErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-tags/{tag_id}",
    ...options,
  })

/**
 * Update an Account Tag
 *
 * Update an Account Tag
 */
export const updateAnAccountTag = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAnAccountTagData, ThrowOnError>,
): RequestResult<
  UpdateAnAccountTagResponses,
  UpdateAnAccountTagErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateAnAccountTagResponses,
    UpdateAnAccountTagErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v2/account-tags/{tag_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
