// This file is auto-generated by @hey-api/openapi-ts

import type { PostV2AccountMembersTokensResponse } from "./types.gen"

const accountManagementAuthenticationTokenResponseSchemaResponseTransformer = (
  data: any,
) => {
  if (data.expires) {
    data.expires = new Date(data.expires)
  }
  return data
}

export const postV2AccountMembersTokensResponseTransformer = async (
  data: any,
): Promise<PostV2AccountMembersTokensResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) => {
      return accountManagementAuthenticationTokenResponseSchemaResponseTransformer(
        item,
      )
    })
  }
  return data
}
