name: Run e2e tests for examples

on:
  workflow_run:
    workflows: ["Generate Examples"]
    branches-ignore:
      - main
      - changeset-release/main
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-e2e-basic:
    name: Run e2e tests for examples
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: examples/basic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Build Latest CLI and generate examples
        run: yarn test:ci:e2e